/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionSuggestion } from './CollectionSuggestion';
import {
    CollectionSuggestionFromJSON,
    CollectionSuggestionFromJSONTyped,
    CollectionSuggestionToJSON,
    CollectionSuggestionToJSONTyped,
} from './CollectionSuggestion';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * 
 * @export
 * @interface AcceptCollectionSuggestionResponse
 */
export interface AcceptCollectionSuggestionResponse {
    /**
     * The collection that now exists.
     * @type {Collection}
     * @memberof AcceptCollectionSuggestionResponse
     */
    collection: Collection;
    /**
     * 
     * @type {CollectionSuggestion}
     * @memberof AcceptCollectionSuggestionResponse
     */
    suggestion: CollectionSuggestion;
    /**
     * How many supporting bookmarks were actually filed. Lower than the supporter count when the user had already filed one of them by hand - accepting a proposal never overrides a human decision.
     * @type {number}
     * @memberof AcceptCollectionSuggestionResponse
     */
    filedCount: number;
}

/**
 * Check if a given object implements the AcceptCollectionSuggestionResponse interface.
 */
export function instanceOfAcceptCollectionSuggestionResponse(value: object): value is AcceptCollectionSuggestionResponse {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('suggestion' in value) || value['suggestion'] === undefined) return false;
    if (!('filedCount' in value) || value['filedCount'] === undefined) return false;
    return true;
}

export function AcceptCollectionSuggestionResponseFromJSON(json: any): AcceptCollectionSuggestionResponse {
    return AcceptCollectionSuggestionResponseFromJSONTyped(json, false);
}

export function AcceptCollectionSuggestionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptCollectionSuggestionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': CollectionFromJSON(json['collection']),
        'suggestion': CollectionSuggestionFromJSON(json['suggestion']),
        'filedCount': json['filedCount'],
    };
}

  export function AcceptCollectionSuggestionResponseToJSON(json: any): AcceptCollectionSuggestionResponse {
      return AcceptCollectionSuggestionResponseToJSONTyped(json, false);
  }

  export function AcceptCollectionSuggestionResponseToJSONTyped(value?: AcceptCollectionSuggestionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': CollectionToJSON(value['collection']),
        'suggestion': CollectionSuggestionToJSON(value['suggestion']),
        'filedCount': value['filedCount'],
    };
}

