/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockResponse
 */
export interface BlockResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BlockResponse
     */
    blocked: boolean;
}

/**
 * Check if a given object implements the BlockResponse interface.
 */
export function instanceOfBlockResponse(value: object): value is BlockResponse {
    if (!('blocked' in value) || value['blocked'] === undefined) return false;
    return true;
}

export function BlockResponseFromJSON(json: any): BlockResponse {
    return BlockResponseFromJSONTyped(json, false);
}

export function BlockResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'blocked': json['blocked'],
    };
}

  export function BlockResponseToJSON(json: any): BlockResponse {
      return BlockResponseToJSONTyped(json, false);
  }

  export function BlockResponseToJSONTyped(value?: BlockResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blocked': value['blocked'],
    };
}

