/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Processing timeline span kind
 * @export
 */
export const BookmarkProcessingEventKind = {
    Run: 'run',
    Phase: 'phase',
    Turn: 'turn'
} as const;
export type BookmarkProcessingEventKind = typeof BookmarkProcessingEventKind[keyof typeof BookmarkProcessingEventKind];


export function instanceOfBookmarkProcessingEventKind(value: any): boolean {
    for (const key in BookmarkProcessingEventKind) {
        if (Object.prototype.hasOwnProperty.call(BookmarkProcessingEventKind, key)) {
            if (BookmarkProcessingEventKind[key as keyof typeof BookmarkProcessingEventKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookmarkProcessingEventKindFromJSON(json: any): BookmarkProcessingEventKind {
    return BookmarkProcessingEventKindFromJSONTyped(json, false);
}

export function BookmarkProcessingEventKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkProcessingEventKind {
    return json as BookmarkProcessingEventKind;
}

export function BookmarkProcessingEventKindToJSON(value?: BookmarkProcessingEventKind | null): any {
    return value as any;
}

export function BookmarkProcessingEventKindToJSONTyped(value: any, ignoreDiscriminator: boolean): BookmarkProcessingEventKind {
    return value as BookmarkProcessingEventKind;
}

