/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Non-archived bookmarks filed in one collection.
 * @export
 * @interface BookmarkCollectionCount
 */
export interface BookmarkCollectionCount {
    /**
     * 
     * @type {string}
     * @memberof BookmarkCollectionCount
     */
    collectionId: string;
    /**
     * 
     * @type {number}
     * @memberof BookmarkCollectionCount
     */
    count: number;
}

/**
 * Check if a given object implements the BookmarkCollectionCount interface.
 */
export function instanceOfBookmarkCollectionCount(value: object): value is BookmarkCollectionCount {
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function BookmarkCollectionCountFromJSON(json: any): BookmarkCollectionCount {
    return BookmarkCollectionCountFromJSONTyped(json, false);
}

export function BookmarkCollectionCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkCollectionCount {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionId': json['collectionId'],
        'count': json['count'],
    };
}

  export function BookmarkCollectionCountToJSON(json: any): BookmarkCollectionCount {
      return BookmarkCollectionCountToJSONTyped(json, false);
  }

  export function BookmarkCollectionCountToJSONTyped(value?: BookmarkCollectionCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collectionId': value['collectionId'],
        'count': value['count'],
    };
}

