/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Durable processing timeline status for runs, phases, and turns
 * @export
 */
export const BookmarkProcessingTimelineStatus = {
    Running: 'running',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type BookmarkProcessingTimelineStatus = typeof BookmarkProcessingTimelineStatus[keyof typeof BookmarkProcessingTimelineStatus];


export function instanceOfBookmarkProcessingTimelineStatus(value: any): boolean {
    for (const key in BookmarkProcessingTimelineStatus) {
        if (Object.prototype.hasOwnProperty.call(BookmarkProcessingTimelineStatus, key)) {
            if (BookmarkProcessingTimelineStatus[key as keyof typeof BookmarkProcessingTimelineStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookmarkProcessingTimelineStatusFromJSON(json: any): BookmarkProcessingTimelineStatus {
    return BookmarkProcessingTimelineStatusFromJSONTyped(json, false);
}

export function BookmarkProcessingTimelineStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkProcessingTimelineStatus {
    return json as BookmarkProcessingTimelineStatus;
}

export function BookmarkProcessingTimelineStatusToJSON(value?: BookmarkProcessingTimelineStatus | null): any {
    return value as any;
}

export function BookmarkProcessingTimelineStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BookmarkProcessingTimelineStatus {
    return value as BookmarkProcessingTimelineStatus;
}

