/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Library ordering - docs/functional-spec/04-library.md § Ordering.
 * 
 * `newest` is chronological by `created_at` descending. It is the default and
 * must always be one click away: AI organisation is an overlay on that order,
 * never a replacement for it.
 * @export
 */
export const BookmarkSort = {
    Newest: 'newest',
    Oldest: 'oldest',
    RecentlyRead: 'recently_read',
    LongestUnread: 'longest_unread'
} as const;
export type BookmarkSort = typeof BookmarkSort[keyof typeof BookmarkSort];


export function instanceOfBookmarkSort(value: any): boolean {
    for (const key in BookmarkSort) {
        if (Object.prototype.hasOwnProperty.call(BookmarkSort, key)) {
            if (BookmarkSort[key as keyof typeof BookmarkSort] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookmarkSortFromJSON(json: any): BookmarkSort {
    return BookmarkSortFromJSONTyped(json, false);
}

export function BookmarkSortFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkSort {
    return json as BookmarkSort;
}

export function BookmarkSortToJSON(value?: BookmarkSort | null): any {
    return value as any;
}

export function BookmarkSortToJSONTyped(value: any, ignoreDiscriminator: boolean): BookmarkSort {
    return value as BookmarkSort;
}

