/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookmarkProcessingRun } from './BookmarkProcessingRun';
import {
    BookmarkProcessingRunFromJSON,
    BookmarkProcessingRunFromJSONTyped,
    BookmarkProcessingRunToJSON,
    BookmarkProcessingRunToJSONTyped,
} from './BookmarkProcessingRun';
import type { Bookmark } from './Bookmark';
import {
    BookmarkFromJSON,
    BookmarkFromJSONTyped,
    BookmarkToJSON,
    BookmarkToJSONTyped,
} from './Bookmark';
import type { BookmarkProcessingEvent } from './BookmarkProcessingEvent';
import {
    BookmarkProcessingEventFromJSON,
    BookmarkProcessingEventFromJSONTyped,
    BookmarkProcessingEventToJSON,
    BookmarkProcessingEventToJSONTyped,
} from './BookmarkProcessingEvent';

/**
 * 
 * @export
 * @interface BookmarkProcessingTimelineResponse
 */
export interface BookmarkProcessingTimelineResponse {
    /**
     * 
     * @type {Bookmark}
     * @memberof BookmarkProcessingTimelineResponse
     */
    bookmark: Bookmark;
    /**
     * 
     * @type {BookmarkProcessingRun}
     * @memberof BookmarkProcessingTimelineResponse
     */
    run?: BookmarkProcessingRun;
    /**
     * 
     * @type {Array<BookmarkProcessingEvent>}
     * @memberof BookmarkProcessingTimelineResponse
     */
    events: Array<BookmarkProcessingEvent>;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingTimelineResponse
     */
    pollAfterMs: number;
}

/**
 * Check if a given object implements the BookmarkProcessingTimelineResponse interface.
 */
export function instanceOfBookmarkProcessingTimelineResponse(value: object): value is BookmarkProcessingTimelineResponse {
    if (!('bookmark' in value) || value['bookmark'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('pollAfterMs' in value) || value['pollAfterMs'] === undefined) return false;
    return true;
}

export function BookmarkProcessingTimelineResponseFromJSON(json: any): BookmarkProcessingTimelineResponse {
    return BookmarkProcessingTimelineResponseFromJSONTyped(json, false);
}

export function BookmarkProcessingTimelineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkProcessingTimelineResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmark': BookmarkFromJSON(json['bookmark']),
        'run': json['run'] == null ? undefined : BookmarkProcessingRunFromJSON(json['run']),
        'events': ((json['events'] as Array<any>).map(BookmarkProcessingEventFromJSON)),
        'pollAfterMs': json['pollAfterMs'],
    };
}

  export function BookmarkProcessingTimelineResponseToJSON(json: any): BookmarkProcessingTimelineResponse {
      return BookmarkProcessingTimelineResponseToJSONTyped(json, false);
  }

  export function BookmarkProcessingTimelineResponseToJSONTyped(value?: BookmarkProcessingTimelineResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmark': BookmarkToJSON(value['bookmark']),
        'run': BookmarkProcessingRunToJSON(value['run']),
        'events': ((value['events'] as Array<any>).map(BookmarkProcessingEventToJSON)),
        'pollAfterMs': value['pollAfterMs'],
    };
}

