/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Which slice of the library a query is about - the Library rail's rows,
 * docs/functional-spec/04-library.md § Collections.
 * 
 * `all` is every non-archived save. `inbox` narrows that to the ones nothing
 * has filed yet (`collection_id IS NULL`). `archive` is the only scope that
 * returns `is_archived = true` rows, which is what makes archiving a way out
 * of the list rather than a delete.
 * @export
 */
export const BookmarkScope = {
    All: 'all',
    Inbox: 'inbox',
    Archive: 'archive'
} as const;
export type BookmarkScope = typeof BookmarkScope[keyof typeof BookmarkScope];


export function instanceOfBookmarkScope(value: any): boolean {
    for (const key in BookmarkScope) {
        if (Object.prototype.hasOwnProperty.call(BookmarkScope, key)) {
            if (BookmarkScope[key as keyof typeof BookmarkScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookmarkScopeFromJSON(json: any): BookmarkScope {
    return BookmarkScopeFromJSONTyped(json, false);
}

export function BookmarkScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkScope {
    return json as BookmarkScope;
}

export function BookmarkScopeToJSON(value?: BookmarkScope | null): any {
    return value as any;
}

export function BookmarkScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): BookmarkScope {
    return value as BookmarkScope;
}

