/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookmarkError
 */
export interface BookmarkError {
    /**
     * 
     * @type {string}
     * @memberof BookmarkError
     */
    error: string;
}

/**
 * Check if a given object implements the BookmarkError interface.
 */
export function instanceOfBookmarkError(value: object): value is BookmarkError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function BookmarkErrorFromJSON(json: any): BookmarkError {
    return BookmarkErrorFromJSONTyped(json, false);
}

export function BookmarkErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

  export function BookmarkErrorToJSON(json: any): BookmarkError {
      return BookmarkErrorToJSONTyped(json, false);
  }

  export function BookmarkErrorToJSONTyped(value?: BookmarkError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

