/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenGraphMetadata } from './OpenGraphMetadata';
import {
    OpenGraphMetadataFromJSON,
    OpenGraphMetadataFromJSONTyped,
    OpenGraphMetadataToJSON,
    OpenGraphMetadataToJSONTyped,
} from './OpenGraphMetadata';

/**
 * 
 * @export
 * @interface BookmarkMetadata
 */
export interface BookmarkMetadata {
    /**
     * 
     * @type {OpenGraphMetadata}
     * @memberof BookmarkMetadata
     */
    openGraph?: OpenGraphMetadata;
    /**
     * 
     * @type {number}
     * @memberof BookmarkMetadata
     */
    wordCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkMetadata
     */
    readingTime?: number;
    /**
     * The URL exactly as the user pasted it, before normalisation. `sourceUrl` holds the normalised form.
     * @type {string}
     * @memberof BookmarkMetadata
     */
    originalUrl?: string;
}

/**
 * Check if a given object implements the BookmarkMetadata interface.
 */
export function instanceOfBookmarkMetadata(value: object): value is BookmarkMetadata {
    return true;
}

export function BookmarkMetadataFromJSON(json: any): BookmarkMetadata {
    return BookmarkMetadataFromJSONTyped(json, false);
}

export function BookmarkMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'openGraph': json['openGraph'] == null ? undefined : OpenGraphMetadataFromJSON(json['openGraph']),
        'wordCount': json['wordCount'] == null ? undefined : json['wordCount'],
        'readingTime': json['readingTime'] == null ? undefined : json['readingTime'],
        'originalUrl': json['originalUrl'] == null ? undefined : json['originalUrl'],
    };
}

  export function BookmarkMetadataToJSON(json: any): BookmarkMetadata {
      return BookmarkMetadataToJSONTyped(json, false);
  }

  export function BookmarkMetadataToJSONTyped(value?: BookmarkMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openGraph': OpenGraphMetadataToJSON(value['openGraph']),
        'wordCount': value['wordCount'],
        'readingTime': value['readingTime'],
        'originalUrl': value['originalUrl'],
    };
}

