/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The pipeline's phases, in order - docs/functional-spec/03-ai-pipeline.md. Sequential, each independently retryable. `fetch` through `file` are surfaced in the UI as a five-line checklist; `embed` runs silently because it has no user-legible output.
 * @export
 */
export const BookmarkProcessingPhase = {
    Fetch: 'fetch',
    Extract: 'extract',
    Summarise: 'summarise',
    Tag: 'tag',
    File: 'file',
    Embed: 'embed'
} as const;
export type BookmarkProcessingPhase = typeof BookmarkProcessingPhase[keyof typeof BookmarkProcessingPhase];


export function instanceOfBookmarkProcessingPhase(value: any): boolean {
    for (const key in BookmarkProcessingPhase) {
        if (Object.prototype.hasOwnProperty.call(BookmarkProcessingPhase, key)) {
            if (BookmarkProcessingPhase[key as keyof typeof BookmarkProcessingPhase] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookmarkProcessingPhaseFromJSON(json: any): BookmarkProcessingPhase {
    return BookmarkProcessingPhaseFromJSONTyped(json, false);
}

export function BookmarkProcessingPhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkProcessingPhase {
    return json as BookmarkProcessingPhase;
}

export function BookmarkProcessingPhaseToJSON(value?: BookmarkProcessingPhase | null): any {
    return value as any;
}

export function BookmarkProcessingPhaseToJSONTyped(value: any, ignoreDiscriminator: boolean): BookmarkProcessingPhase {
    return value as BookmarkProcessingPhase;
}

