/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookmarkLink
 */
export interface BookmarkLink {
    /**
     * 
     * @type {string}
     * @memberof BookmarkLink
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkLink
     */
    relevance: string;
}

/**
 * Check if a given object implements the BookmarkLink interface.
 */
export function instanceOfBookmarkLink(value: object): value is BookmarkLink {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('relevance' in value) || value['relevance'] === undefined) return false;
    return true;
}

export function BookmarkLinkFromJSON(json: any): BookmarkLink {
    return BookmarkLinkFromJSONTyped(json, false);
}

export function BookmarkLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkLink {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'relevance': json['relevance'],
    };
}

  export function BookmarkLinkToJSON(json: any): BookmarkLink {
      return BookmarkLinkToJSONTyped(json, false);
  }

  export function BookmarkLinkToJSONTyped(value?: BookmarkLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'relevance': value['relevance'],
    };
}

