/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookmarkImage } from './BookmarkImage';
import {
    BookmarkImageFromJSON,
    BookmarkImageFromJSONTyped,
    BookmarkImageToJSON,
    BookmarkImageToJSONTyped,
} from './BookmarkImage';
import type { BookmarkLink } from './BookmarkLink';
import {
    BookmarkLinkFromJSON,
    BookmarkLinkFromJSONTyped,
    BookmarkLinkToJSON,
    BookmarkLinkToJSONTyped,
} from './BookmarkLink';
import type { CollectionPathItem } from './CollectionPathItem';
import {
    CollectionPathItemFromJSON,
    CollectionPathItemFromJSONTyped,
    CollectionPathItemToJSON,
    CollectionPathItemToJSONTyped,
} from './CollectionPathItem';
import type { BookmarkMetadata } from './BookmarkMetadata';
import {
    BookmarkMetadataFromJSON,
    BookmarkMetadataFromJSONTyped,
    BookmarkMetadataToJSON,
    BookmarkMetadataToJSONTyped,
} from './BookmarkMetadata';
import type { ProcessingStatus } from './ProcessingStatus';
import {
    ProcessingStatusFromJSON,
    ProcessingStatusFromJSONTyped,
    ProcessingStatusToJSON,
    ProcessingStatusToJSONTyped,
} from './ProcessingStatus';

/**
 * 
 * @export
 * @interface Bookmark
 */
export interface Bookmark {
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    sourceUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof Bookmark
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Bookmark
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    collectionId?: string;
    /**
     * 
     * @type {Array<CollectionPathItem>}
     * @memberof Bookmark
     */
    collectionPath?: Array<CollectionPathItem>;
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    title?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Bookmark
     */
    isArchived?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Bookmark
     */
    isFavorite?: boolean;
    /**
     * 
     * @type {Array<BookmarkImage>}
     * @memberof Bookmark
     */
    cosmicImages?: Array<BookmarkImage>;
    /**
     * 
     * @type {Array<BookmarkLink>}
     * @memberof Bookmark
     */
    cosmicLinks?: Array<BookmarkLink>;
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    cosmicSummary?: string;
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    cosmicBriefSummary?: string;
    /**
     * The full brief's key points - 2-5 findings of at most 140 characters, parsed out of `cosmicSummary` once by the pipeline. Rendered with a dot marker, never numbered.
     * @type {Array<string>}
     * @memberof Bookmark
     */
    cosmicKeyPoints?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Bookmark
     */
    cosmicTags?: Array<string>;
    /**
     * 
     * @type {BookmarkMetadata}
     * @memberof Bookmark
     */
    metadata?: BookmarkMetadata;
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    userId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Bookmark
     */
    isPrivateLink?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Bookmark
     */
    likeCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Bookmark
     */
    isLikedByCurrentUser?: boolean;
    /**
     * Live comments on this bookmark, tombstones excluded. Denormalised and maintained by trigger — the feed reads it on every item.
     * @type {number}
     * @memberof Bookmark
     */
    commentCount?: number;
    /**
     * Reshare provenance: the bookmark this one was saved from, when the save
     * came from someone else's. Absent on a save made from a URL.
     * 
     * It goes null rather than dangling when the original is deleted, so a
     * provenance row must degrade to the domain alone rather than assume the
     * original is still there.
     * @type {string}
     * @memberof Bookmark
     */
    savedFromBookmarkId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Bookmark
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    shareSlug?: string;
    /**
     * 
     * @type {Date}
     * @memberof Bookmark
     */
    readAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Bookmark
     */
    isRead?: boolean;
    /**
     * 
     * @type {ProcessingStatus}
     * @memberof Bookmark
     */
    processingStatus?: ProcessingStatus;
    /**
     * 
     * @type {Date}
     * @memberof Bookmark
     */
    processingStartedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Bookmark
     */
    processingCompletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Bookmark
     */
    processingError?: string;
}



/**
 * Check if a given object implements the Bookmark interface.
 */
export function instanceOfBookmark(value: object): value is Bookmark {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sourceUrl' in value) || value['sourceUrl'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function BookmarkFromJSON(json: any): Bookmark {
    return BookmarkFromJSONTyped(json, false);
}

export function BookmarkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bookmark {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sourceUrl': json['sourceUrl'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'collectionId': json['collectionId'] == null ? undefined : json['collectionId'],
        'collectionPath': json['collectionPath'] == null ? undefined : ((json['collectionPath'] as Array<any>).map(CollectionPathItemFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
        'isFavorite': json['isFavorite'] == null ? undefined : json['isFavorite'],
        'cosmicImages': json['cosmicImages'] == null ? undefined : ((json['cosmicImages'] as Array<any>).map(BookmarkImageFromJSON)),
        'cosmicLinks': json['cosmicLinks'] == null ? undefined : ((json['cosmicLinks'] as Array<any>).map(BookmarkLinkFromJSON)),
        'cosmicSummary': json['cosmicSummary'] == null ? undefined : json['cosmicSummary'],
        'cosmicBriefSummary': json['cosmicBriefSummary'] == null ? undefined : json['cosmicBriefSummary'],
        'cosmicKeyPoints': json['cosmicKeyPoints'] == null ? undefined : json['cosmicKeyPoints'],
        'cosmicTags': json['cosmicTags'] == null ? undefined : json['cosmicTags'],
        'metadata': json['metadata'] == null ? undefined : BookmarkMetadataFromJSON(json['metadata']),
        'userId': json['userId'],
        'isPrivateLink': json['isPrivateLink'] == null ? undefined : json['isPrivateLink'],
        'likeCount': json['likeCount'] == null ? undefined : json['likeCount'],
        'isLikedByCurrentUser': json['isLikedByCurrentUser'] == null ? undefined : json['isLikedByCurrentUser'],
        'commentCount': json['commentCount'] == null ? undefined : json['commentCount'],
        'savedFromBookmarkId': json['savedFromBookmarkId'] == null ? undefined : json['savedFromBookmarkId'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
        'shareSlug': json['shareSlug'] == null ? undefined : json['shareSlug'],
        'readAt': json['readAt'] == null ? undefined : (new Date(json['readAt'])),
        'isRead': json['isRead'] == null ? undefined : json['isRead'],
        'processingStatus': json['processingStatus'] == null ? undefined : ProcessingStatusFromJSON(json['processingStatus']),
        'processingStartedAt': json['processingStartedAt'] == null ? undefined : (new Date(json['processingStartedAt'])),
        'processingCompletedAt': json['processingCompletedAt'] == null ? undefined : (new Date(json['processingCompletedAt'])),
        'processingError': json['processingError'] == null ? undefined : json['processingError'],
    };
}

  export function BookmarkToJSON(json: any): Bookmark {
      return BookmarkToJSONTyped(json, false);
  }

  export function BookmarkToJSONTyped(value?: Bookmark | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sourceUrl': value['sourceUrl'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'collectionId': value['collectionId'],
        'collectionPath': value['collectionPath'] == null ? undefined : ((value['collectionPath'] as Array<any>).map(CollectionPathItemToJSON)),
        'title': value['title'],
        'isArchived': value['isArchived'],
        'isFavorite': value['isFavorite'],
        'cosmicImages': value['cosmicImages'] == null ? undefined : ((value['cosmicImages'] as Array<any>).map(BookmarkImageToJSON)),
        'cosmicLinks': value['cosmicLinks'] == null ? undefined : ((value['cosmicLinks'] as Array<any>).map(BookmarkLinkToJSON)),
        'cosmicSummary': value['cosmicSummary'],
        'cosmicBriefSummary': value['cosmicBriefSummary'],
        'cosmicKeyPoints': value['cosmicKeyPoints'],
        'cosmicTags': value['cosmicTags'],
        'metadata': BookmarkMetadataToJSON(value['metadata']),
        'userId': value['userId'],
        'isPrivateLink': value['isPrivateLink'],
        'likeCount': value['likeCount'],
        'isLikedByCurrentUser': value['isLikedByCurrentUser'],
        'commentCount': value['commentCount'],
        'savedFromBookmarkId': value['savedFromBookmarkId'],
        'isPublic': value['isPublic'],
        'shareSlug': value['shareSlug'],
        'readAt': value['readAt'] == null ? undefined : ((value['readAt']).toISOString()),
        'isRead': value['isRead'],
        'processingStatus': ProcessingStatusToJSON(value['processingStatus']),
        'processingStartedAt': value['processingStartedAt'] == null ? undefined : ((value['processingStartedAt']).toISOString()),
        'processingCompletedAt': value['processingCompletedAt'] == null ? undefined : ((value['processingCompletedAt']).toISOString()),
        'processingError': value['processingError'],
    };
}

