/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookmarkProcessingTimelineStatus } from './BookmarkProcessingTimelineStatus';
import {
    BookmarkProcessingTimelineStatusFromJSON,
    BookmarkProcessingTimelineStatusFromJSONTyped,
    BookmarkProcessingTimelineStatusToJSON,
    BookmarkProcessingTimelineStatusToJSONTyped,
} from './BookmarkProcessingTimelineStatus';

/**
 * 
 * @export
 * @interface BookmarkProcessingRun
 */
export interface BookmarkProcessingRun {
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingRun
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingRun
     */
    bookmarkId: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingRun
     */
    userId: string;
    /**
     * 
     * @type {BookmarkProcessingTimelineStatus}
     * @memberof BookmarkProcessingRun
     */
    status: BookmarkProcessingTimelineStatus;
    /**
     * 
     * @type {Date}
     * @memberof BookmarkProcessingRun
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookmarkProcessingRun
     */
    endedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingRun
     */
    durationMs?: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingRun
     */
    inputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingRun
     */
    outputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingRun
     */
    totalTokens: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingRun
     */
    reasoningTokens: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingRun
     */
    cachedInputTokens: number;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingRun
     */
    costUsd?: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingRun
     */
    error?: string;
    /**
     * 
     * @type {Date}
     * @memberof BookmarkProcessingRun
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookmarkProcessingRun
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the BookmarkProcessingRun interface.
 */
export function instanceOfBookmarkProcessingRun(value: object): value is BookmarkProcessingRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bookmarkId' in value) || value['bookmarkId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    if (!('reasoningTokens' in value) || value['reasoningTokens'] === undefined) return false;
    if (!('cachedInputTokens' in value) || value['cachedInputTokens'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BookmarkProcessingRunFromJSON(json: any): BookmarkProcessingRun {
    return BookmarkProcessingRunFromJSONTyped(json, false);
}

export function BookmarkProcessingRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkProcessingRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bookmarkId': json['bookmarkId'],
        'userId': json['userId'],
        'status': BookmarkProcessingTimelineStatusFromJSON(json['status']),
        'startedAt': (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'inputTokens': json['inputTokens'],
        'outputTokens': json['outputTokens'],
        'totalTokens': json['totalTokens'],
        'reasoningTokens': json['reasoningTokens'],
        'cachedInputTokens': json['cachedInputTokens'],
        'costUsd': json['costUsd'] == null ? undefined : json['costUsd'],
        'error': json['error'] == null ? undefined : json['error'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

  export function BookmarkProcessingRunToJSON(json: any): BookmarkProcessingRun {
      return BookmarkProcessingRunToJSONTyped(json, false);
  }

  export function BookmarkProcessingRunToJSONTyped(value?: BookmarkProcessingRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bookmarkId': value['bookmarkId'],
        'userId': value['userId'],
        'status': BookmarkProcessingTimelineStatusToJSON(value['status']),
        'startedAt': ((value['startedAt']).toISOString()),
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt']).toISOString()),
        'durationMs': value['durationMs'],
        'inputTokens': value['inputTokens'],
        'outputTokens': value['outputTokens'],
        'totalTokens': value['totalTokens'],
        'reasoningTokens': value['reasoningTokens'],
        'cachedInputTokens': value['cachedInputTokens'],
        'costUsd': value['costUsd'],
        'error': value['error'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

