/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookmarkCollectionCount } from './BookmarkCollectionCount';
import {
    BookmarkCollectionCountFromJSON,
    BookmarkCollectionCountFromJSONTyped,
    BookmarkCollectionCountToJSON,
    BookmarkCollectionCountToJSONTyped,
} from './BookmarkCollectionCount';

/**
 * The counts the Library rail renders beside its rows. One query rather than
 * one request per node - the rail has as many rows as the user has
 * collections, and a count per row would be a request per row.
 * @export
 * @interface BookmarkLibraryCounts
 */
export interface BookmarkLibraryCounts {
    /**
     * Every non-archived bookmark - the `All saves` row.
     * @type {number}
     * @memberof BookmarkLibraryCounts
     */
    all: number;
    /**
     * Non-archived with `collection_id IS NULL` - the `Inbox` row.
     * @type {number}
     * @memberof BookmarkLibraryCounts
     */
    inbox: number;
    /**
     * Non-archived with `read_at IS NULL` - the `Read later` row.
     * @type {number}
     * @memberof BookmarkLibraryCounts
     */
    unread: number;
    /**
     * `is_archived = true` - the `Archive` row.
     * @type {number}
     * @memberof BookmarkLibraryCounts
     */
    archived: number;
    /**
     * Per-collection counts. A collection holding nothing is absent, not zero.
     * @type {Array<BookmarkCollectionCount>}
     * @memberof BookmarkLibraryCounts
     */
    collections: Array<BookmarkCollectionCount>;
}

/**
 * Check if a given object implements the BookmarkLibraryCounts interface.
 */
export function instanceOfBookmarkLibraryCounts(value: object): value is BookmarkLibraryCounts {
    if (!('all' in value) || value['all'] === undefined) return false;
    if (!('inbox' in value) || value['inbox'] === undefined) return false;
    if (!('unread' in value) || value['unread'] === undefined) return false;
    if (!('archived' in value) || value['archived'] === undefined) return false;
    if (!('collections' in value) || value['collections'] === undefined) return false;
    return true;
}

export function BookmarkLibraryCountsFromJSON(json: any): BookmarkLibraryCounts {
    return BookmarkLibraryCountsFromJSONTyped(json, false);
}

export function BookmarkLibraryCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkLibraryCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'all': json['all'],
        'inbox': json['inbox'],
        'unread': json['unread'],
        'archived': json['archived'],
        'collections': ((json['collections'] as Array<any>).map(BookmarkCollectionCountFromJSON)),
    };
}

  export function BookmarkLibraryCountsToJSON(json: any): BookmarkLibraryCounts {
      return BookmarkLibraryCountsToJSONTyped(json, false);
  }

  export function BookmarkLibraryCountsToJSONTyped(value?: BookmarkLibraryCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'all': value['all'],
        'inbox': value['inbox'],
        'unread': value['unread'],
        'archived': value['archived'],
        'collections': ((value['collections'] as Array<any>).map(BookmarkCollectionCountToJSON)),
    };
}

