/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Read-state filter for bookmark library queries
 * @export
 */
export const BookmarkReadStatus = {
    All: 'all',
    Unread: 'unread',
    Read: 'read'
} as const;
export type BookmarkReadStatus = typeof BookmarkReadStatus[keyof typeof BookmarkReadStatus];


export function instanceOfBookmarkReadStatus(value: any): boolean {
    for (const key in BookmarkReadStatus) {
        if (Object.prototype.hasOwnProperty.call(BookmarkReadStatus, key)) {
            if (BookmarkReadStatus[key as keyof typeof BookmarkReadStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookmarkReadStatusFromJSON(json: any): BookmarkReadStatus {
    return BookmarkReadStatusFromJSONTyped(json, false);
}

export function BookmarkReadStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkReadStatus {
    return json as BookmarkReadStatus;
}

export function BookmarkReadStatusToJSON(value?: BookmarkReadStatus | null): any {
    return value as any;
}

export function BookmarkReadStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BookmarkReadStatus {
    return value as BookmarkReadStatus;
}

