/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookmarkImage
 */
export interface BookmarkImage {
    /**
     * 
     * @type {string}
     * @memberof BookmarkImage
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkImage
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkImage
     */
    description: string;
}

/**
 * Check if a given object implements the BookmarkImage interface.
 */
export function instanceOfBookmarkImage(value: object): value is BookmarkImage {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function BookmarkImageFromJSON(json: any): BookmarkImage {
    return BookmarkImageFromJSONTyped(json, false);
}

export function BookmarkImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkImage {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'title': json['title'],
        'description': json['description'],
    };
}

  export function BookmarkImageToJSON(json: any): BookmarkImage {
      return BookmarkImageToJSONTyped(json, false);
  }

  export function BookmarkImageToJSONTyped(value?: BookmarkImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'title': value['title'],
        'description': value['description'],
    };
}

