/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookmarkProcessingTimelineStatus } from './BookmarkProcessingTimelineStatus';
import {
    BookmarkProcessingTimelineStatusFromJSON,
    BookmarkProcessingTimelineStatusFromJSONTyped,
    BookmarkProcessingTimelineStatusToJSON,
    BookmarkProcessingTimelineStatusToJSONTyped,
} from './BookmarkProcessingTimelineStatus';
import type { BookmarkProcessingEventKind } from './BookmarkProcessingEventKind';
import {
    BookmarkProcessingEventKindFromJSON,
    BookmarkProcessingEventKindFromJSONTyped,
    BookmarkProcessingEventKindToJSON,
    BookmarkProcessingEventKindToJSONTyped,
} from './BookmarkProcessingEventKind';

/**
 * 
 * @export
 * @interface BookmarkProcessingEvent
 */
export interface BookmarkProcessingEvent {
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingEvent
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingEvent
     */
    parentEventId?: string;
    /**
     * 
     * @type {BookmarkProcessingEventKind}
     * @memberof BookmarkProcessingEvent
     */
    kind: BookmarkProcessingEventKind;
    /**
     * One of `BookmarkProcessingPhase` for a phase or turn span. Absent on the run span and on bookkeeping that was never a user-facing phase.
     * @type {string}
     * @memberof BookmarkProcessingEvent
     */
    phase?: string;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingEvent
     */
    name: string;
    /**
     * 
     * @type {BookmarkProcessingTimelineStatus}
     * @memberof BookmarkProcessingEvent
     */
    status: BookmarkProcessingTimelineStatus;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingEvent
     */
    sequence: number;
    /**
     * 
     * @type {Date}
     * @memberof BookmarkProcessingEvent
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookmarkProcessingEvent
     */
    endedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingEvent
     */
    durationMs?: number;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingEvent
     */
    modelId?: string;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingEvent
     */
    inputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingEvent
     */
    outputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingEvent
     */
    totalTokens: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingEvent
     */
    reasoningTokens: number;
    /**
     * 
     * @type {number}
     * @memberof BookmarkProcessingEvent
     */
    cachedInputTokens: number;
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingEvent
     */
    costUsd?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BookmarkProcessingEvent
     */
    providerMetadata?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BookmarkProcessingEvent
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof BookmarkProcessingEvent
     */
    error?: string;
    /**
     * 
     * @type {Date}
     * @memberof BookmarkProcessingEvent
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BookmarkProcessingEvent
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the BookmarkProcessingEvent interface.
 */
export function instanceOfBookmarkProcessingEvent(value: object): value is BookmarkProcessingEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('sequence' in value) || value['sequence'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    if (!('reasoningTokens' in value) || value['reasoningTokens'] === undefined) return false;
    if (!('cachedInputTokens' in value) || value['cachedInputTokens'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BookmarkProcessingEventFromJSON(json: any): BookmarkProcessingEvent {
    return BookmarkProcessingEventFromJSONTyped(json, false);
}

export function BookmarkProcessingEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkProcessingEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'runId': json['runId'],
        'parentEventId': json['parentEventId'] == null ? undefined : json['parentEventId'],
        'kind': BookmarkProcessingEventKindFromJSON(json['kind']),
        'phase': json['phase'] == null ? undefined : json['phase'],
        'name': json['name'],
        'status': BookmarkProcessingTimelineStatusFromJSON(json['status']),
        'sequence': json['sequence'],
        'startedAt': (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'modelId': json['modelId'] == null ? undefined : json['modelId'],
        'inputTokens': json['inputTokens'],
        'outputTokens': json['outputTokens'],
        'totalTokens': json['totalTokens'],
        'reasoningTokens': json['reasoningTokens'],
        'cachedInputTokens': json['cachedInputTokens'],
        'costUsd': json['costUsd'] == null ? undefined : json['costUsd'],
        'providerMetadata': json['providerMetadata'] == null ? undefined : json['providerMetadata'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'error': json['error'] == null ? undefined : json['error'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

  export function BookmarkProcessingEventToJSON(json: any): BookmarkProcessingEvent {
      return BookmarkProcessingEventToJSONTyped(json, false);
  }

  export function BookmarkProcessingEventToJSONTyped(value?: BookmarkProcessingEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'runId': value['runId'],
        'parentEventId': value['parentEventId'],
        'kind': BookmarkProcessingEventKindToJSON(value['kind']),
        'phase': value['phase'],
        'name': value['name'],
        'status': BookmarkProcessingTimelineStatusToJSON(value['status']),
        'sequence': value['sequence'],
        'startedAt': ((value['startedAt']).toISOString()),
        'endedAt': value['endedAt'] == null ? undefined : ((value['endedAt']).toISOString()),
        'durationMs': value['durationMs'],
        'modelId': value['modelId'],
        'inputTokens': value['inputTokens'],
        'outputTokens': value['outputTokens'],
        'totalTokens': value['totalTokens'],
        'reasoningTokens': value['reasoningTokens'],
        'cachedInputTokens': value['cachedInputTokens'],
        'costUsd': value['costUsd'],
        'providerMetadata': value['providerMetadata'],
        'metadata': value['metadata'],
        'error': value['error'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

