/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Path item for breadcrumb navigation in collection hierarchy
 * @export
 * @interface CollectionPathItem
 */
export interface CollectionPathItem {
    /**
     * 
     * @type {string}
     * @memberof CollectionPathItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionPathItem
     */
    name: string;
}

/**
 * Check if a given object implements the CollectionPathItem interface.
 */
export function instanceOfCollectionPathItem(value: object): value is CollectionPathItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CollectionPathItemFromJSON(json: any): CollectionPathItem {
    return CollectionPathItemFromJSONTyped(json, false);
}

export function CollectionPathItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionPathItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

  export function CollectionPathItemToJSON(json: any): CollectionPathItem {
      return CollectionPathItemToJSONTyped(json, false);
  }

  export function CollectionPathItemToJSONTyped(value?: CollectionPathItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

