/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionSuggestionStatus } from './CollectionSuggestionStatus';
import {
    CollectionSuggestionStatusFromJSON,
    CollectionSuggestionStatusFromJSONTyped,
    CollectionSuggestionStatusToJSON,
    CollectionSuggestionStatusToJSONTyped,
} from './CollectionSuggestionStatus';

/**
 * A collection the pipeline thinks should exist. It does not exist yet.
 * 
 * The `file` phase never creates a collection - it accumulates supporting
 * bookmarks against a proposed name. Only `POST /collections/suggestions/{id}/accept`
 * turns one into a collection.
 * @export
 * @interface CollectionSuggestion
 */
export interface CollectionSuggestion {
    /**
     * 
     * @type {string}
     * @memberof CollectionSuggestion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSuggestion
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSuggestion
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionSuggestion
     */
    parentId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CollectionSuggestion
     */
    bookmarkIds: Array<string>;
    /**
     * 
     * @type {CollectionSuggestionStatus}
     * @memberof CollectionSuggestion
     */
    status: CollectionSuggestionStatus;
    /**
     * Set when the proposal was dismissed. It is not re-offered before this instant - 30 days out.
     * @type {Date}
     * @memberof CollectionSuggestion
     */
    dismissedUntil?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CollectionSuggestion
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the CollectionSuggestion interface.
 */
export function instanceOfCollectionSuggestion(value: object): value is CollectionSuggestion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('bookmarkIds' in value) || value['bookmarkIds'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CollectionSuggestionFromJSON(json: any): CollectionSuggestion {
    return CollectionSuggestionFromJSONTyped(json, false);
}

export function CollectionSuggestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionSuggestion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'name': json['name'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'bookmarkIds': json['bookmarkIds'],
        'status': CollectionSuggestionStatusFromJSON(json['status']),
        'dismissedUntil': json['dismissedUntil'] == null ? undefined : (new Date(json['dismissedUntil'])),
        'createdAt': (new Date(json['createdAt'])),
    };
}

  export function CollectionSuggestionToJSON(json: any): CollectionSuggestion {
      return CollectionSuggestionToJSONTyped(json, false);
  }

  export function CollectionSuggestionToJSONTyped(value?: CollectionSuggestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'name': value['name'],
        'parentId': value['parentId'],
        'bookmarkIds': value['bookmarkIds'],
        'status': CollectionSuggestionStatusToJSON(value['status']),
        'dismissedUntil': value['dismissedUntil'] == null ? undefined : ((value['dismissedUntil']).toISOString()),
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

