/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Where a collection suggestion stands. `pending` is still the user's to answer; `accepted` became a real collection; `dismissed` is remembered until `dismissedUntil`.
 * @export
 */
export const CollectionSuggestionStatus = {
    Pending: 'pending',
    Accepted: 'accepted',
    Dismissed: 'dismissed'
} as const;
export type CollectionSuggestionStatus = typeof CollectionSuggestionStatus[keyof typeof CollectionSuggestionStatus];


export function instanceOfCollectionSuggestionStatus(value: any): boolean {
    for (const key in CollectionSuggestionStatus) {
        if (Object.prototype.hasOwnProperty.call(CollectionSuggestionStatus, key)) {
            if (CollectionSuggestionStatus[key as keyof typeof CollectionSuggestionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CollectionSuggestionStatusFromJSON(json: any): CollectionSuggestionStatus {
    return CollectionSuggestionStatusFromJSONTyped(json, false);
}

export function CollectionSuggestionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionSuggestionStatus {
    return json as CollectionSuggestionStatus;
}

export function CollectionSuggestionStatusToJSON(value?: CollectionSuggestionStatus | null): any {
    return value as any;
}

export function CollectionSuggestionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CollectionSuggestionStatus {
    return value as CollectionSuggestionStatus;
}

