/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Collection
 */
export interface Collection {
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    parentId?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    userId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Collection
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the Collection interface.
 */
export function instanceOfCollection(value: object): value is Collection {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CollectionFromJSON(json: any): Collection {
    return CollectionFromJSONTyped(json, false);
}

export function CollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Collection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'color': json['color'] == null ? undefined : json['color'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'userId': json['userId'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

  export function CollectionToJSON(json: any): Collection {
      return CollectionToJSONTyped(json, false);
  }

  export function CollectionToJSONTyped(value?: Collection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'color': value['color'],
        'icon': value['icon'],
        'parentId': value['parentId'],
        'userId': value['userId'],
        'isPublic': value['isPublic'],
    };
}

