/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionSuggestion } from './CollectionSuggestion';
import {
    CollectionSuggestionFromJSON,
    CollectionSuggestionFromJSONTyped,
    CollectionSuggestionToJSON,
    CollectionSuggestionToJSONTyped,
} from './CollectionSuggestion';

/**
 * 
 * @export
 * @interface CollectionSuggestionResponse
 */
export interface CollectionSuggestionResponse {
    /**
     * 
     * @type {CollectionSuggestion}
     * @memberof CollectionSuggestionResponse
     */
    suggestion: CollectionSuggestion;
}

/**
 * Check if a given object implements the CollectionSuggestionResponse interface.
 */
export function instanceOfCollectionSuggestionResponse(value: object): value is CollectionSuggestionResponse {
    if (!('suggestion' in value) || value['suggestion'] === undefined) return false;
    return true;
}

export function CollectionSuggestionResponseFromJSON(json: any): CollectionSuggestionResponse {
    return CollectionSuggestionResponseFromJSONTyped(json, false);
}

export function CollectionSuggestionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionSuggestionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestion': CollectionSuggestionFromJSON(json['suggestion']),
    };
}

  export function CollectionSuggestionResponseToJSON(json: any): CollectionSuggestionResponse {
      return CollectionSuggestionResponseToJSONTyped(json, false);
  }

  export function CollectionSuggestionResponseToJSONTyped(value?: CollectionSuggestionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestion': CollectionSuggestionToJSON(value['suggestion']),
    };
}

