/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The public identity behind a comment. Never carries an email — see `PublicProfile`.
 * @export
 * @interface CommentAuthor
 */
export interface CommentAuthor {
    /**
     * 
     * @type {string}
     * @memberof CommentAuthor
     */
    id: string;
    /**
     * Absent only in the degraded case where a handle could not be minted at signup.
     * @type {string}
     * @memberof CommentAuthor
     */
    handle?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentAuthor
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentAuthor
     */
    pictureUrl?: string;
}

/**
 * Check if a given object implements the CommentAuthor interface.
 */
export function instanceOfCommentAuthor(value: object): value is CommentAuthor {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CommentAuthorFromJSON(json: any): CommentAuthor {
    return CommentAuthorFromJSONTyped(json, false);
}

export function CommentAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentAuthor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'name': json['name'] == null ? undefined : json['name'],
        'pictureUrl': json['pictureUrl'] == null ? undefined : json['pictureUrl'],
    };
}

  export function CommentAuthorToJSON(json: any): CommentAuthor {
      return CommentAuthorToJSONTyped(json, false);
  }

  export function CommentAuthorToJSONTyped(value?: CommentAuthor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'handle': value['handle'],
        'name': value['name'],
        'pictureUrl': value['pictureUrl'],
    };
}

