/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentError
 */
export interface CommentError {
    /**
     * 
     * @type {string}
     * @memberof CommentError
     */
    error: string;
}

/**
 * Check if a given object implements the CommentError interface.
 */
export function instanceOfCommentError(value: object): value is CommentError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function CommentErrorFromJSON(json: any): CommentError {
    return CommentErrorFromJSONTyped(json, false);
}

export function CommentErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

  export function CommentErrorToJSON(json: any): CommentError {
      return CommentErrorToJSONTyped(json, false);
  }

  export function CommentErrorToJSONTyped(value?: CommentError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

