/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentAuthor } from './CommentAuthor';
import {
    CommentAuthorFromJSON,
    CommentAuthorFromJSONTyped,
    CommentAuthorToJSON,
    CommentAuthorToJSONTyped,
} from './CommentAuthor';

/**
 * A comment on a bookmark.
 * 
 * Plain text plus links — no rich text, no images, no embeds, and no field
 * here in which to put any. 2,000 characters.
 * 
 * **One level of nesting.** `parentId` is either absent (a top-level comment)
 * or the id of a top-level comment. It is never the id of a reply: a
 * `parentId` pointing at a reply is re-pointed server-side at that reply's own
 * parent, so the client's request succeeds and lands where a one-level thread
 * can hold it. Deep threads are where reading products turn into forums.
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    bookmarkId: string;
    /**
     * Absent on a top-level comment. Always a top-level comment's id when present.
     * @type {string}
     * @memberof Comment
     */
    parentId?: string;
    /**
     * Absent on a deleted comment, which carries `isDeleted: true` and renders
     * as "Comment deleted".
     * @type {string}
     * @memberof Comment
     */
    body?: string;
    /**
     * Absent on a deleted comment: a tombstone stands in the thread so its
     * replies still have a parent, and it credits nobody.
     * @type {CommentAuthor}
     * @memberof Comment
     */
    author?: CommentAuthor;
    /**
     * 
     * @type {Date}
     * @memberof Comment
     */
    createdAt: Date;
    /**
     * Equal to `createdAt` until edited. Editing is refused more than 15 minutes after `createdAt`.
     * @type {Date}
     * @memberof Comment
     */
    updatedAt: Date;
    /**
     * True when the body was edited after it was written.
     * @type {boolean}
     * @memberof Comment
     */
    isEdited: boolean;
    /**
     * A soft-deleted comment that still holds replies. It has no body and no
     * author, and it cannot be edited, replied to, or reported.
     * @type {boolean}
     * @memberof Comment
     */
    isDeleted: boolean;
    /**
     * True when the caller wrote this comment.
     * @type {boolean}
     * @memberof Comment
     */
    isOwn: boolean;
    /**
     * True while this comment is still inside its 15-minute edit window.
     * 
     * The server is the authority — it re-checks on every `PATCH` — but the
     * client needs it to decide whether to offer an Edit control at all,
     * rather than offering one that will be refused.
     * @type {boolean}
     * @memberof Comment
     */
    canEdit: boolean;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bookmarkId' in value) || value['bookmarkId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('isEdited' in value) || value['isEdited'] === undefined) return false;
    if (!('isDeleted' in value) || value['isDeleted'] === undefined) return false;
    if (!('isOwn' in value) || value['isOwn'] === undefined) return false;
    if (!('canEdit' in value) || value['canEdit'] === undefined) return false;
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bookmarkId': json['bookmarkId'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'body': json['body'] == null ? undefined : json['body'],
        'author': json['author'] == null ? undefined : CommentAuthorFromJSON(json['author']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'isEdited': json['isEdited'],
        'isDeleted': json['isDeleted'],
        'isOwn': json['isOwn'],
        'canEdit': json['canEdit'],
    };
}

  export function CommentToJSON(json: any): Comment {
      return CommentToJSONTyped(json, false);
  }

  export function CommentToJSONTyped(value?: Comment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bookmarkId': value['bookmarkId'],
        'parentId': value['parentId'],
        'body': value['body'],
        'author': CommentAuthorToJSON(value['author']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'isEdited': value['isEdited'],
        'isDeleted': value['isDeleted'],
        'isOwn': value['isOwn'],
        'canEdit': value['canEdit'],
    };
}

