/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * A thread, chronological.
 * 
 * There is no ranking, no "top comment" and no score, and no field here in
 * which to express one. Top-level comments are oldest first, and each one's
 * replies are oldest first beneath it — a conversation reads forwards.
 * @export
 * @interface CommentsResponse
 */
export interface CommentsResponse {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof CommentsResponse
     */
    comments: Array<Comment>;
    /**
     * Live comments on the bookmark, tombstones excluded. Matches `Bookmark.commentCount`.
     * @type {number}
     * @memberof CommentsResponse
     */
    commentCount: number;
}

/**
 * Check if a given object implements the CommentsResponse interface.
 */
export function instanceOfCommentsResponse(value: object): value is CommentsResponse {
    if (!('comments' in value) || value['comments'] === undefined) return false;
    if (!('commentCount' in value) || value['commentCount'] === undefined) return false;
    return true;
}

export function CommentsResponseFromJSON(json: any): CommentsResponse {
    return CommentsResponseFromJSONTyped(json, false);
}

export function CommentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': ((json['comments'] as Array<any>).map(CommentFromJSON)),
        'commentCount': json['commentCount'],
    };
}

  export function CommentsResponseToJSON(json: any): CommentsResponse {
      return CommentsResponseToJSONTyped(json, false);
  }

  export function CommentsResponseToJSONTyped(value?: CommentsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': ((value['comments'] as Array<any>).map(CommentToJSON)),
        'commentCount': value['commentCount'],
    };
}

