/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bookmark } from './Bookmark';
import {
    BookmarkFromJSON,
    BookmarkFromJSONTyped,
    BookmarkToJSON,
    BookmarkToJSONTyped,
} from './Bookmark';
import type { ReadingProgress } from './ReadingProgress';
import {
    ReadingProgressFromJSON,
    ReadingProgressFromJSONTyped,
    ReadingProgressToJSON,
    ReadingProgressToJSONTyped,
} from './ReadingProgress';

/**
 * A bookmark the reader is part-way through, for Home's Continue reading rail.
 * @export
 * @interface ContinueReadingItem
 */
export interface ContinueReadingItem {
    /**
     * 
     * @type {Bookmark}
     * @memberof ContinueReadingItem
     */
    bookmark: Bookmark;
    /**
     * 
     * @type {ReadingProgress}
     * @memberof ContinueReadingItem
     */
    progress: ReadingProgress;
}

/**
 * Check if a given object implements the ContinueReadingItem interface.
 */
export function instanceOfContinueReadingItem(value: object): value is ContinueReadingItem {
    if (!('bookmark' in value) || value['bookmark'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    return true;
}

export function ContinueReadingItemFromJSON(json: any): ContinueReadingItem {
    return ContinueReadingItemFromJSONTyped(json, false);
}

export function ContinueReadingItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContinueReadingItem {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmark': BookmarkFromJSON(json['bookmark']),
        'progress': ReadingProgressFromJSON(json['progress']),
    };
}

  export function ContinueReadingItemToJSON(json: any): ContinueReadingItem {
      return ContinueReadingItemToJSONTyped(json, false);
  }

  export function ContinueReadingItemToJSONTyped(value?: ContinueReadingItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmark': BookmarkToJSON(value['bookmark']),
        'progress': ReadingProgressToJSON(value['progress']),
    };
}

