/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContinueReadingItem } from './ContinueReadingItem';
import {
    ContinueReadingItemFromJSON,
    ContinueReadingItemFromJSONTyped,
    ContinueReadingItemToJSON,
    ContinueReadingItemToJSONTyped,
} from './ContinueReadingItem';

/**
 * 
 * @export
 * @interface ContinueReadingResponse
 */
export interface ContinueReadingResponse {
    /**
     * 
     * @type {Array<ContinueReadingItem>}
     * @memberof ContinueReadingResponse
     */
    items: Array<ContinueReadingItem>;
}

/**
 * Check if a given object implements the ContinueReadingResponse interface.
 */
export function instanceOfContinueReadingResponse(value: object): value is ContinueReadingResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ContinueReadingResponseFromJSON(json: any): ContinueReadingResponse {
    return ContinueReadingResponseFromJSONTyped(json, false);
}

export function ContinueReadingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContinueReadingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ContinueReadingItemFromJSON)),
    };
}

  export function ContinueReadingResponseToJSON(json: any): ContinueReadingResponse {
      return ContinueReadingResponseToJSONTyped(json, false);
  }

  export function ContinueReadingResponseToJSONTyped(value?: ContinueReadingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ContinueReadingItemToJSON)),
    };
}

