/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookmarkRequest
 */
export interface CreateBookmarkRequest {
    /**
     * The source URL to bookmark
     * @type {string}
     * @memberof CreateBookmarkRequest
     */
    sourceUrl: string;
    /**
     * Optional collection ID to add the bookmark to
     * @type {string}
     * @memberof CreateBookmarkRequest
     */
    collectionId?: string;
    /**
     * Optional title for the bookmark
     * @type {string}
     * @memberof CreateBookmarkRequest
     */
    title?: string;
    /**
     * Optional description for the bookmark
     * @type {string}
     * @memberof CreateBookmarkRequest
     */
    description?: string;
    /**
     * Optional tags for the bookmark
     * @type {Array<string>}
     * @memberof CreateBookmarkRequest
     */
    tags?: Array<string>;
    /**
     * Whether this is a private link that cannot be scraped
     * @type {boolean}
     * @memberof CreateBookmarkRequest
     */
    isPrivateLink?: boolean;
}

/**
 * Check if a given object implements the CreateBookmarkRequest interface.
 */
export function instanceOfCreateBookmarkRequest(value: object): value is CreateBookmarkRequest {
    if (!('sourceUrl' in value) || value['sourceUrl'] === undefined) return false;
    return true;
}

export function CreateBookmarkRequestFromJSON(json: any): CreateBookmarkRequest {
    return CreateBookmarkRequestFromJSONTyped(json, false);
}

export function CreateBookmarkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookmarkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceUrl': json['source_url'],
        'collectionId': json['collection_id'] == null ? undefined : json['collection_id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'isPrivateLink': json['is_private_link'] == null ? undefined : json['is_private_link'],
    };
}

  export function CreateBookmarkRequestToJSON(json: any): CreateBookmarkRequest {
      return CreateBookmarkRequestToJSONTyped(json, false);
  }

  export function CreateBookmarkRequestToJSONTyped(value?: CreateBookmarkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_url': value['sourceUrl'],
        'collection_id': value['collectionId'],
        'title': value['title'],
        'description': value['description'],
        'tags': value['tags'],
        'is_private_link': value['isPrivateLink'],
    };
}

