/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentRequest
 */
export interface CreateCommentRequest {
    /**
     * 1-2,000 characters of plain text. Leading and trailing whitespace is trimmed before the length is measured.
     * @type {string}
     * @memberof CreateCommentRequest
     */
    body: string;
    /**
     * The comment being replied to. A reply to a reply is re-pointed at that reply's parent rather than refused.
     * @type {string}
     * @memberof CreateCommentRequest
     */
    parentId?: string;
}

/**
 * Check if a given object implements the CreateCommentRequest interface.
 */
export function instanceOfCreateCommentRequest(value: object): value is CreateCommentRequest {
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CreateCommentRequestFromJSON(json: any): CreateCommentRequest {
    return CreateCommentRequestFromJSONTyped(json, false);
}

export function CreateCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
    };
}

  export function CreateCommentRequestToJSON(json: any): CreateCommentRequest {
      return CreateCommentRequestToJSONTyped(json, false);
  }

  export function CreateCommentRequestToJSONTyped(value?: CreateCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'parentId': value['parentId'],
    };
}

