/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A report of a public bookmark or a comment.
 * 
 * Exactly one target. Reported content **stays visible** pending review:
 * auto-hide is trivially weaponised, so nothing about filing this changes what
 * anyone can see.
 * @export
 * @interface CreateReportRequest
 */
export interface CreateReportRequest {
    /**
     * The bookmark being reported. Exactly one of `bookmarkId` and `commentId`.
     * @type {string}
     * @memberof CreateReportRequest
     */
    bookmarkId?: string;
    /**
     * The comment being reported. Exactly one of `bookmarkId` and `commentId`.
     * @type {string}
     * @memberof CreateReportRequest
     */
    commentId?: string;
    /**
     * Why. Free text, 1-1,000 characters — a fixed taxonomy would need a moderation product to consume it, and there is not one yet.
     * @type {string}
     * @memberof CreateReportRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the CreateReportRequest interface.
 */
export function instanceOfCreateReportRequest(value: object): value is CreateReportRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function CreateReportRequestFromJSON(json: any): CreateReportRequest {
    return CreateReportRequestFromJSONTyped(json, false);
}

export function CreateReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkId': json['bookmarkId'] == null ? undefined : json['bookmarkId'],
        'commentId': json['commentId'] == null ? undefined : json['commentId'],
        'reason': json['reason'],
    };
}

  export function CreateReportRequestToJSON(json: any): CreateReportRequest {
      return CreateReportRequestToJSONTyped(json, false);
  }

  export function CreateReportRequestToJSONTyped(value?: CreateReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmarkId': value['bookmarkId'],
        'commentId': value['commentId'],
        'reason': value['reason'],
    };
}

