/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NoteType } from './NoteType';
import {
    NoteTypeFromJSON,
    NoteTypeFromJSONTyped,
    NoteTypeToJSON,
    NoteTypeToJSONTyped,
} from './NoteType';

/**
 * 
 * @export
 * @interface CreateNoteRequest
 */
export interface CreateNoteRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNoteRequest
     */
    body: string;
    /**
     * 
     * @type {NoteType}
     * @memberof CreateNoteRequest
     */
    type: NoteType;
}



/**
 * Check if a given object implements the CreateNoteRequest interface.
 */
export function instanceOfCreateNoteRequest(value: object): value is CreateNoteRequest {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateNoteRequestFromJSON(json: any): CreateNoteRequest {
    return CreateNoteRequestFromJSONTyped(json, false);
}

export function CreateNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'type': NoteTypeFromJSON(json['type']),
    };
}

  export function CreateNoteRequestToJSON(json: any): CreateNoteRequest {
      return CreateNoteRequestToJSONTyped(json, false);
  }

  export function CreateNoteRequestToJSONTyped(value?: CreateNoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'type': NoteTypeToJSON(value['type']),
    };
}

