/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bookmark } from './Bookmark';
import {
    BookmarkFromJSON,
    BookmarkFromJSONTyped,
    BookmarkToJSON,
    BookmarkToJSONTyped,
} from './Bookmark';

/**
 * 
 * @export
 * @interface CreateBookmarkResponse
 */
export interface CreateBookmarkResponse {
    /**
     * 
     * @type {Bookmark}
     * @memberof CreateBookmarkResponse
     */
    bookmark: Bookmark;
    /**
     * 
     * @type {string}
     * @memberof CreateBookmarkResponse
     */
    message: string;
    /**
     * The user already had this URL. The bookmark returned is the existing one — nothing was created and nothing was re-queued. A duplicate paste is not an error.
     * @type {boolean}
     * @memberof CreateBookmarkResponse
     */
    alreadySaved?: boolean;
}

/**
 * Check if a given object implements the CreateBookmarkResponse interface.
 */
export function instanceOfCreateBookmarkResponse(value: object): value is CreateBookmarkResponse {
    if (!('bookmark' in value) || value['bookmark'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateBookmarkResponseFromJSON(json: any): CreateBookmarkResponse {
    return CreateBookmarkResponseFromJSONTyped(json, false);
}

export function CreateBookmarkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookmarkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmark': BookmarkFromJSON(json['bookmark']),
        'message': json['message'],
        'alreadySaved': json['alreadySaved'] == null ? undefined : json['alreadySaved'],
    };
}

  export function CreateBookmarkResponseToJSON(json: any): CreateBookmarkResponse {
      return CreateBookmarkResponseToJSONTyped(json, false);
  }

  export function CreateBookmarkResponseToJSONTyped(value?: CreateBookmarkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmark': BookmarkToJSON(value['bookmark']),
        'message': value['message'],
        'alreadySaved': value['alreadySaved'],
    };
}

