/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCollectionRequest
 */
export interface CreateCollectionRequest {
    /**
     * Display name. Required, trimmed, at most 120 characters.
     * @type {string}
     * @memberof CreateCollectionRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCollectionRequest
     */
    description?: string;
    /**
     * A design-system collection colour token name, never a hex value.
     * @type {string}
     * @memberof CreateCollectionRequest
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCollectionRequest
     */
    icon?: string;
    /**
     * Parent collection. Must be a root collection - the tree is capped at two levels.
     * @type {string}
     * @memberof CreateCollectionRequest
     */
    parentId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCollectionRequest
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the CreateCollectionRequest interface.
 */
export function instanceOfCreateCollectionRequest(value: object): value is CreateCollectionRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateCollectionRequestFromJSON(json: any): CreateCollectionRequest {
    return CreateCollectionRequestFromJSONTyped(json, false);
}

export function CreateCollectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCollectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'color': json['color'] == null ? undefined : json['color'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

  export function CreateCollectionRequestToJSON(json: any): CreateCollectionRequest {
      return CreateCollectionRequestToJSONTyped(json, false);
  }

  export function CreateCollectionRequestToJSONTyped(value?: CreateCollectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'color': value['color'],
        'icon': value['icon'],
        'parentId': value['parentId'],
        'isPublic': value['isPublic'],
    };
}

