/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Deliberately thin.
 * 
 * It says the report was received and nothing else. It does not say what will
 * happen, does not echo the target back, and — most importantly — carries no
 * signal that the reported content has changed state, because it has not.
 * @export
 * @interface CreateReportResponse
 */
export interface CreateReportResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateReportResponse
     */
    reported: boolean;
}

/**
 * Check if a given object implements the CreateReportResponse interface.
 */
export function instanceOfCreateReportResponse(value: object): value is CreateReportResponse {
    if (!('reported' in value) || value['reported'] === undefined) return false;
    return true;
}

export function CreateReportResponseFromJSON(json: any): CreateReportResponse {
    return CreateReportResponseFromJSONTyped(json, false);
}

export function CreateReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reported': json['reported'],
    };
}

  export function CreateReportResponseToJSON(json: any): CreateReportResponse {
      return CreateReportResponseToJSONTyped(json, false);
  }

  export function CreateReportResponseToJSONTyped(value?: CreateReportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reported': value['reported'],
    };
}

