/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHighlightRequest
 */
export interface CreateHighlightRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateHighlightRequest
     */
    quote: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHighlightRequest
     */
    prefix?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHighlightRequest
     */
    suffix?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHighlightRequest
     */
    note?: string;
}

/**
 * Check if a given object implements the CreateHighlightRequest interface.
 */
export function instanceOfCreateHighlightRequest(value: object): value is CreateHighlightRequest {
    if (!('quote' in value) || value['quote'] === undefined) return false;
    return true;
}

export function CreateHighlightRequestFromJSON(json: any): CreateHighlightRequest {
    return CreateHighlightRequestFromJSONTyped(json, false);
}

export function CreateHighlightRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHighlightRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quote': json['quote'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

  export function CreateHighlightRequestToJSON(json: any): CreateHighlightRequest {
      return CreateHighlightRequestToJSONTyped(json, false);
  }

  export function CreateHighlightRequestToJSONTyped(value?: CreateHighlightRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quote': value['quote'],
        'prefix': value['prefix'],
        'suffix': value['suffix'],
        'note': value['note'],
    };
}

