/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteHighlightResponse
 */
export interface DeleteHighlightResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteHighlightResponse
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteHighlightResponse interface.
 */
export function instanceOfDeleteHighlightResponse(value: object): value is DeleteHighlightResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteHighlightResponseFromJSON(json: any): DeleteHighlightResponse {
    return DeleteHighlightResponseFromJSONTyped(json, false);
}

export function DeleteHighlightResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteHighlightResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

  export function DeleteHighlightResponseToJSON(json: any): DeleteHighlightResponse {
      return DeleteHighlightResponseToJSONTyped(json, false);
  }

  export function DeleteHighlightResponseToJSONTyped(value?: DeleteHighlightResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

