/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteCollectionResponse
 */
export interface DeleteCollectionResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteCollectionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteCollectionResponse interface.
 */
export function instanceOfDeleteCollectionResponse(value: object): value is DeleteCollectionResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteCollectionResponseFromJSON(json: any): DeleteCollectionResponse {
    return DeleteCollectionResponseFromJSONTyped(json, false);
}

export function DeleteCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

  export function DeleteCollectionResponseToJSON(json: any): DeleteCollectionResponse {
      return DeleteCollectionResponseToJSONTyped(json, false);
  }

  export function DeleteCollectionResponseToJSONTyped(value?: DeleteCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

