/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * What happened to the comment.
 * 
 * A delete is one of two different things and the client has to render them
 * differently: a comment with replies becomes a tombstone that stays in the
 * thread, and a comment without replies stops existing.
 * @export
 * @interface DeleteCommentResponse
 */
export interface DeleteCommentResponse {
    /**
     * False when the comment was soft-deleted because it has replies; `comment` then carries the tombstone.
     * @type {boolean}
     * @memberof DeleteCommentResponse
     */
    deleted: boolean;
    /**
     * Present only on a soft delete. The tombstone, for the client to swap in place.
     * @type {Comment}
     * @memberof DeleteCommentResponse
     */
    comment?: Comment;
    /**
     * The parent bookmark's comment count after the call.
     * @type {number}
     * @memberof DeleteCommentResponse
     */
    commentCount: number;
}

/**
 * Check if a given object implements the DeleteCommentResponse interface.
 */
export function instanceOfDeleteCommentResponse(value: object): value is DeleteCommentResponse {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('commentCount' in value) || value['commentCount'] === undefined) return false;
    return true;
}

export function DeleteCommentResponseFromJSON(json: any): DeleteCommentResponse {
    return DeleteCommentResponseFromJSONTyped(json, false);
}

export function DeleteCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
        'comment': json['comment'] == null ? undefined : CommentFromJSON(json['comment']),
        'commentCount': json['commentCount'],
    };
}

  export function DeleteCommentResponseToJSON(json: any): DeleteCommentResponse {
      return DeleteCommentResponseToJSONTyped(json, false);
  }

  export function DeleteCommentResponseToJSONTyped(value?: DeleteCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
        'comment': CommentToJSON(value['comment']),
        'commentCount': value['commentCount'],
    };
}

