/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteBookmarkResponse
 */
export interface DeleteBookmarkResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteBookmarkResponse
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteBookmarkResponse interface.
 */
export function instanceOfDeleteBookmarkResponse(value: object): value is DeleteBookmarkResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteBookmarkResponseFromJSON(json: any): DeleteBookmarkResponse {
    return DeleteBookmarkResponseFromJSONTyped(json, false);
}

export function DeleteBookmarkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBookmarkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

  export function DeleteBookmarkResponseToJSON(json: any): DeleteBookmarkResponse {
      return DeleteBookmarkResponseToJSONTyped(json, false);
  }

  export function DeleteBookmarkResponseToJSONTyped(value?: DeleteBookmarkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

