/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One bookmark a digest was built from - docs/functional-spec/05-feed.md
 * § Digests.
 * 
 * This model is the contract behind the `Built from` provenance row, and the
 * reason it carries a `url` and a `domain` as well as an id: the row renders
 * a favicon chip and a domain *as a link*, and a client that had only the id
 * would have to fetch every source to draw the one line that makes the digest
 * trustworthy.
 * 
 * A digest names **every** bookmark it was built from. `Digest.sources` is
 * never truncated server-side; the `+n more` tail in the UI is a display
 * decision taken over a complete list.
 * @export
 * @interface DigestSource
 */
export interface DigestSource {
    /**
     * 
     * @type {string}
     * @memberof DigestSource
     */
    bookmarkId: string;
    /**
     * 
     * @type {string}
     * @memberof DigestSource
     */
    title: string;
    /**
     * The bookmark's `sourceUrl` — what the provenance link points at.
     * @type {string}
     * @memberof DigestSource
     */
    url: string;
    /**
     * Bare domain, e.g. `every.to`. Derived server-side from `url`.
     * @type {string}
     * @memberof DigestSource
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof DigestSource
     */
    faviconUrl?: string;
}

/**
 * Check if a given object implements the DigestSource interface.
 */
export function instanceOfDigestSource(value: object): value is DigestSource {
    if (!('bookmarkId' in value) || value['bookmarkId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function DigestSourceFromJSON(json: any): DigestSource {
    return DigestSourceFromJSONTyped(json, false);
}

export function DigestSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigestSource {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkId': json['bookmarkId'],
        'title': json['title'],
        'url': json['url'],
        'domain': json['domain'],
        'faviconUrl': json['faviconUrl'] == null ? undefined : json['faviconUrl'],
    };
}

  export function DigestSourceToJSON(json: any): DigestSource {
      return DigestSourceToJSONTyped(json, false);
  }

  export function DigestSourceToJSONTyped(value?: DigestSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmarkId': value['bookmarkId'],
        'title': value['title'],
        'url': value['url'],
        'domain': value['domain'],
        'faviconUrl': value['faviconUrl'],
    };
}

