/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigestError
 */
export interface DigestError {
    /**
     * 
     * @type {string}
     * @memberof DigestError
     */
    error: string;
}

/**
 * Check if a given object implements the DigestError interface.
 */
export function instanceOfDigestError(value: object): value is DigestError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function DigestErrorFromJSON(json: any): DigestError {
    return DigestErrorFromJSONTyped(json, false);
}

export function DigestErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigestError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

  export function DigestErrorToJSON(json: any): DigestError {
      return DigestErrorToJSONTyped(json, false);
  }

  export function DigestErrorToJSONTyped(value?: DigestError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

