/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One finding in a digest.
 * 
 * Findings, **not a sequence**: the UI renders them with a dot marker and
 * never numbers them, because numbering claims an order the content does not
 * have (docs/design-system/patterns.md § AI callout).
 * @export
 * @interface DigestKeyPoint
 */
export interface DigestKeyPoint {
    /**
     * Optional lead-in run, rendered in `--cd-fg`: "Memory beats context."
     * @type {string}
     * @memberof DigestKeyPoint
     */
    term?: string;
    /**
     * 
     * @type {string}
     * @memberof DigestKeyPoint
     */
    text: string;
}

/**
 * Check if a given object implements the DigestKeyPoint interface.
 */
export function instanceOfDigestKeyPoint(value: object): value is DigestKeyPoint {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function DigestKeyPointFromJSON(json: any): DigestKeyPoint {
    return DigestKeyPointFromJSONTyped(json, false);
}

export function DigestKeyPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigestKeyPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'term': json['term'] == null ? undefined : json['term'],
        'text': json['text'],
    };
}

  export function DigestKeyPointToJSON(json: any): DigestKeyPoint {
      return DigestKeyPointToJSONTyped(json, false);
  }

  export function DigestKeyPointToJSONTyped(value?: DigestKeyPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'term': value['term'],
        'text': value['text'],
    };
}

