/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DigestSource } from './DigestSource';
import {
    DigestSourceFromJSON,
    DigestSourceFromJSONTyped,
    DigestSourceToJSON,
    DigestSourceToJSONTyped,
} from './DigestSource';
import type { DigestKeyPoint } from './DigestKeyPoint';
import {
    DigestKeyPointFromJSON,
    DigestKeyPointFromJSONTyped,
    DigestKeyPointToJSON,
    DigestKeyPointToJSONTyped,
} from './DigestKeyPoint';

/**
 * An AI-authored feed item that groups 3-6 of the user's own recent saves
 * into a single observation - docs/functional-spec/05-feed.md § Digests.
 * 
 * Generated on a schedule per user by the worker, by clustering the last 14
 * days of saves on embedding proximity and asking the model for a thesis plus
 * 2-3 key points **only when the cluster is genuinely coherent**. A weak
 * cluster produces no digest at all, which is why there is no "confidence" or
 * "quality" field here: a digest that exists has already passed the bar, and
 * a digest that did not pass it was never written.
 * 
 * A digest is a **first-class social object**. It has its own likes, its own
 * share link, and its own detail route. Sharing one shares the digest, not
 * its sources: the source bookmarks' visibility is never touched by anything
 * done to the digest.
 * @export
 * @interface Digest
 */
export interface Digest {
    /**
     * 
     * @type {string}
     * @memberof Digest
     */
    id: string;
    /**
     * The observation, in one line: "Four of your saves are circling the same argument."
     * @type {string}
     * @memberof Digest
     */
    title: string;
    /**
     * A short paragraph stating the thesis the sources share.
     * @type {string}
     * @memberof Digest
     */
    summary: string;
    /**
     * 2-3 findings. Rendered with dots, never numbered.
     * @type {Array<DigestKeyPoint>}
     * @memberof Digest
     */
    keyPoints: Array<DigestKeyPoint>;
    /**
     * Every bookmark this digest was built from, in cluster order. Never truncated.
     * @type {Array<DigestSource>}
     * @memberof Digest
     */
    sources: Array<DigestSource>;
    /**
     * The measured mean pairwise cosine similarity of the cluster the digest
     * was written from, 0..1. Returned for the same reason `signals` is
     * returned on a feed item: so the threshold that produced this digest can
     * be read off a response rather than argued about.
     * @type {number}
     * @memberof Digest
     */
    coherence: number;
    /**
     * 
     * @type {Date}
     * @memberof Digest
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Digest
     */
    likeCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof Digest
     */
    isLikedByCurrentUser: boolean;
    /**
     * Whether the digest has been shared. A private digest is visible only to its owner.
     * @type {boolean}
     * @memberof Digest
     */
    isPublic: boolean;
    /**
     * Present once the digest has been shared.
     * @type {string}
     * @memberof Digest
     */
    shareUrl?: string;
}

/**
 * Check if a given object implements the Digest interface.
 */
export function instanceOfDigest(value: object): value is Digest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('keyPoints' in value) || value['keyPoints'] === undefined) return false;
    if (!('sources' in value) || value['sources'] === undefined) return false;
    if (!('coherence' in value) || value['coherence'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('likeCount' in value) || value['likeCount'] === undefined) return false;
    if (!('isLikedByCurrentUser' in value) || value['isLikedByCurrentUser'] === undefined) return false;
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    return true;
}

export function DigestFromJSON(json: any): Digest {
    return DigestFromJSONTyped(json, false);
}

export function DigestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Digest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'summary': json['summary'],
        'keyPoints': ((json['keyPoints'] as Array<any>).map(DigestKeyPointFromJSON)),
        'sources': ((json['sources'] as Array<any>).map(DigestSourceFromJSON)),
        'coherence': json['coherence'],
        'createdAt': (new Date(json['createdAt'])),
        'likeCount': json['likeCount'],
        'isLikedByCurrentUser': json['isLikedByCurrentUser'],
        'isPublic': json['isPublic'],
        'shareUrl': json['shareUrl'] == null ? undefined : json['shareUrl'],
    };
}

  export function DigestToJSON(json: any): Digest {
      return DigestToJSONTyped(json, false);
  }

  export function DigestToJSONTyped(value?: Digest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'summary': value['summary'],
        'keyPoints': ((value['keyPoints'] as Array<any>).map(DigestKeyPointToJSON)),
        'sources': ((value['sources'] as Array<any>).map(DigestSourceToJSON)),
        'coherence': value['coherence'],
        'createdAt': ((value['createdAt']).toISOString()),
        'likeCount': value['likeCount'],
        'isLikedByCurrentUser': value['isLikedByCurrentUser'],
        'isPublic': value['isPublic'],
        'shareUrl': value['shareUrl'],
    };
}

