/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedItem } from './FeedItem';
import {
    FeedItemFromJSON,
    FeedItemFromJSONTyped,
    FeedItemToJSON,
    FeedItemToJSONTyped,
} from './FeedItem';
import type { ExploreTopic } from './ExploreTopic';
import {
    ExploreTopicFromJSON,
    ExploreTopicFromJSONTyped,
    ExploreTopicToJSON,
    ExploreTopicToJSONTyped,
} from './ExploreTopic';

/**
 * A page of Explore - docs/design-system/pages.md § Explore.
 * 
 * The same `FeedItem` shape Home uses, ranked for **discovery** rather than
 * personal usefulness: engagement on public saves with a recency decay, over
 * everybody's public library rather than the reader's own and the people they
 * follow. `rankingReason` still comes from the server and is still never
 * synthesised on the client.
 * 
 * `topics` rides along with the page because the segmented control is part of
 * the same surface and a second request for six strings would reflow the page
 * once for nothing.
 * @export
 * @interface ExploreResponse
 */
export interface ExploreResponse {
    /**
     * 
     * @type {Array<FeedItem>}
     * @memberof ExploreResponse
     */
    items: Array<FeedItem>;
    /**
     * The topic segmented control's options, most-saved first. Empty when nothing public carries a tag.
     * @type {Array<ExploreTopic>}
     * @memberof ExploreResponse
     */
    topics: Array<ExploreTopic>;
    /**
     * Keyset cursor for the next page. Absent when this page is the last one.
     * @type {string}
     * @memberof ExploreResponse
     */
    nextCursor?: string;
    /**
     * When this page was computed.
     * @type {Date}
     * @memberof ExploreResponse
     */
    computedAt: Date;
}

/**
 * Check if a given object implements the ExploreResponse interface.
 */
export function instanceOfExploreResponse(value: object): value is ExploreResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('topics' in value) || value['topics'] === undefined) return false;
    if (!('computedAt' in value) || value['computedAt'] === undefined) return false;
    return true;
}

export function ExploreResponseFromJSON(json: any): ExploreResponse {
    return ExploreResponseFromJSONTyped(json, false);
}

export function ExploreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExploreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(FeedItemFromJSON)),
        'topics': ((json['topics'] as Array<any>).map(ExploreTopicFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'computedAt': (new Date(json['computedAt'])),
    };
}

  export function ExploreResponseToJSON(json: any): ExploreResponse {
      return ExploreResponseToJSONTyped(json, false);
  }

  export function ExploreResponseToJSONTyped(value?: ExploreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(FeedItemToJSON)),
        'topics': ((value['topics'] as Array<any>).map(ExploreTopicToJSON)),
        'nextCursor': value['nextCursor'],
        'computedAt': ((value['computedAt']).toISOString()),
    };
}

