/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrendingCollection } from './TrendingCollection';
import {
    TrendingCollectionFromJSON,
    TrendingCollectionFromJSONTyped,
    TrendingCollectionToJSON,
    TrendingCollectionToJSONTyped,
} from './TrendingCollection';
import type { TrendingPerson } from './TrendingPerson';
import {
    TrendingPersonFromJSON,
    TrendingPersonFromJSONTyped,
    TrendingPersonToJSON,
    TrendingPersonToJSONTyped,
} from './TrendingPerson';

/**
 * Explore's rail - docs/design-system/pages.md § Explore.
 * 
 * Both lists are empty until the social graph is populated, and the client is
 * expected to say so honestly rather than pad the column with the reader's
 * own material.
 * @export
 * @interface ExploreRailResponse
 */
export interface ExploreRailResponse {
    /**
     * 
     * @type {Array<TrendingCollection>}
     * @memberof ExploreRailResponse
     */
    collections: Array<TrendingCollection>;
    /**
     * 
     * @type {Array<TrendingPerson>}
     * @memberof ExploreRailResponse
     */
    people: Array<TrendingPerson>;
}

/**
 * Check if a given object implements the ExploreRailResponse interface.
 */
export function instanceOfExploreRailResponse(value: object): value is ExploreRailResponse {
    if (!('collections' in value) || value['collections'] === undefined) return false;
    if (!('people' in value) || value['people'] === undefined) return false;
    return true;
}

export function ExploreRailResponseFromJSON(json: any): ExploreRailResponse {
    return ExploreRailResponseFromJSONTyped(json, false);
}

export function ExploreRailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExploreRailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collections': ((json['collections'] as Array<any>).map(TrendingCollectionFromJSON)),
        'people': ((json['people'] as Array<any>).map(TrendingPersonFromJSON)),
    };
}

  export function ExploreRailResponseToJSON(json: any): ExploreRailResponse {
      return ExploreRailResponseToJSONTyped(json, false);
  }

  export function ExploreRailResponseToJSONTyped(value?: ExploreRailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collections': ((value['collections'] as Array<any>).map(TrendingCollectionToJSON)),
        'people': ((value['people'] as Array<any>).map(TrendingPersonToJSON)),
    };
}

