/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExploreError
 */
export interface ExploreError {
    /**
     * 
     * @type {string}
     * @memberof ExploreError
     */
    error: string;
}

/**
 * Check if a given object implements the ExploreError interface.
 */
export function instanceOfExploreError(value: object): value is ExploreError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ExploreErrorFromJSON(json: any): ExploreError {
    return ExploreErrorFromJSONTyped(json, false);
}

export function ExploreErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExploreError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

  export function ExploreErrorToJSON(json: any): ExploreError {
      return ExploreErrorToJSONTyped(json, false);
  }

  export function ExploreErrorToJSONTyped(value?: ExploreError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

