/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A topic the product as a whole has been saving, and how many public saves
 * carry it inside the discovery window.
 * 
 * This is **not** `FeedRailTopic`. That one counts the reader's own saves and
 * answers "what have I been reading"; this one counts everyone's public saves
 * and answers "what is the product reading". Same shape, different question,
 * and collapsing them would make Explore a mirror of Home — which is exactly
 * what Explore exists not to be.
 * @export
 * @interface ExploreTopic
 */
export interface ExploreTopic {
    /**
     * 
     * @type {string}
     * @memberof ExploreTopic
     */
    topic: string;
    /**
     * 
     * @type {number}
     * @memberof ExploreTopic
     */
    count: number;
}

/**
 * Check if a given object implements the ExploreTopic interface.
 */
export function instanceOfExploreTopic(value: object): value is ExploreTopic {
    if (!('topic' in value) || value['topic'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ExploreTopicFromJSON(json: any): ExploreTopic {
    return ExploreTopicFromJSONTyped(json, false);
}

export function ExploreTopicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExploreTopic {
    if (json == null) {
        return json;
    }
    return {
        
        'topic': json['topic'],
        'count': json['count'],
    };
}

  export function ExploreTopicToJSON(json: any): ExploreTopic {
      return ExploreTopicToJSONTyped(json, false);
  }

  export function ExploreTopicToJSONTyped(value?: ExploreTopic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topic': value['topic'],
        'count': value['count'],
    };
}

