/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RankingSignal } from './RankingSignal';
import {
    RankingSignalFromJSON,
    RankingSignalFromJSONTyped,
    RankingSignalToJSON,
    RankingSignalToJSONTyped,
} from './RankingSignal';
import type { Bookmark } from './Bookmark';
import {
    BookmarkFromJSON,
    BookmarkFromJSONTyped,
    BookmarkToJSON,
    BookmarkToJSONTyped,
} from './Bookmark';
import type { Digest } from './Digest';
import {
    DigestFromJSON,
    DigestFromJSONTyped,
    DigestToJSON,
    DigestToJSONTyped,
} from './Digest';
import type { FeedItemType } from './FeedItemType';
import {
    FeedItemTypeFromJSON,
    FeedItemTypeFromJSONTyped,
    FeedItemTypeToJSON,
    FeedItemTypeToJSONTyped,
} from './FeedItemType';
import type { FeedActor } from './FeedActor';
import {
    FeedActorFromJSON,
    FeedActorFromJSONTyped,
    FeedActorToJSON,
    FeedActorToJSONTyped,
} from './FeedActor';

/**
 * One row of the Home feed - docs/functional-spec/05-feed.md.
 * 
 * `rankingReason` is generated **server-side** from the top two contributing
 * signals and is never synthesised on the client: the client cannot know what
 * the ranker weighted, and a plausible-sounding wrong answer is worse than
 * none. It is absent on `pending`, which is pinned rather than ranked.
 * @export
 * @interface FeedItem
 */
export interface FeedItem {
    /**
     * 
     * @type {FeedItemType}
     * @memberof FeedItem
     */
    type: FeedItemType;
    /**
     * The bookmark, on every type except `digest`.
     * @type {Bookmark}
     * @memberof FeedItem
     */
    bookmark?: Bookmark;
    /**
     * The digest, on `digest` items and nothing else — it is exactly the
     * field `bookmark` is absent for.
     * 
     * It arrives complete, sources included, because the `Built from`
     * provenance row is not optional decoration: an AI output that cannot
     * name what it was built from does not get rendered
     * (docs/functional-spec/05-feed.md § Digests).
     * @type {Digest}
     * @memberof FeedItem
     */
    digest?: Digest;
    /**
     * Who this reached the user through - the saver, or the resharer. Absent on the user's own saves.
     * @type {FeedActor}
     * @memberof FeedItem
     */
    actor?: FeedActor;
    /**
     * "Why this appeared", in one sentence of plain second-person language.
     * @type {string}
     * @memberof FeedItem
     */
    rankingReason?: string;
    /**
     * Per-signal breakdown. Omitted in production responses.
     * @type {Array<RankingSignal>}
     * @memberof FeedItem
     */
    signals?: Array<RankingSignal>;
}



/**
 * Check if a given object implements the FeedItem interface.
 */
export function instanceOfFeedItem(value: object): value is FeedItem {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FeedItemFromJSON(json: any): FeedItem {
    return FeedItemFromJSONTyped(json, false);
}

export function FeedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'type': FeedItemTypeFromJSON(json['type']),
        'bookmark': json['bookmark'] == null ? undefined : BookmarkFromJSON(json['bookmark']),
        'digest': json['digest'] == null ? undefined : DigestFromJSON(json['digest']),
        'actor': json['actor'] == null ? undefined : FeedActorFromJSON(json['actor']),
        'rankingReason': json['rankingReason'] == null ? undefined : json['rankingReason'],
        'signals': json['signals'] == null ? undefined : ((json['signals'] as Array<any>).map(RankingSignalFromJSON)),
    };
}

  export function FeedItemToJSON(json: any): FeedItem {
      return FeedItemToJSONTyped(json, false);
  }

  export function FeedItemToJSONTyped(value?: FeedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': FeedItemTypeToJSON(value['type']),
        'bookmark': BookmarkToJSON(value['bookmark']),
        'digest': DigestToJSON(value['digest']),
        'actor': FeedActorToJSON(value['actor']),
        'rankingReason': value['rankingReason'],
        'signals': value['signals'] == null ? undefined : ((value['signals'] as Array<any>).map(RankingSignalToJSON)),
    };
}

