/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What a feed item *is* - docs/functional-spec/05-feed.md § Item types.
 * 
 * `pending` is a save still being processed. It is pinned to the top of the
 * feed regardless of score, because the user just created it and expects to
 * see it. `digest` is an AI-authored grouping of the user's own saves; it
 * carries a `digest` payload instead of a `bookmark`, and the ranker spaces
 * it at one per eight items, three per session.
 * @export
 */
export const FeedItemType = {
    OwnSave: 'own_save',
    FollowedSave: 'followed_save',
    Reshare: 'reshare',
    Digest: 'digest',
    Pending: 'pending'
} as const;
export type FeedItemType = typeof FeedItemType[keyof typeof FeedItemType];


export function instanceOfFeedItemType(value: any): boolean {
    for (const key in FeedItemType) {
        if (Object.prototype.hasOwnProperty.call(FeedItemType, key)) {
            if (FeedItemType[key as keyof typeof FeedItemType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FeedItemTypeFromJSON(json: any): FeedItemType {
    return FeedItemTypeFromJSONTyped(json, false);
}

export function FeedItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedItemType {
    return json as FeedItemType;
}

export function FeedItemTypeToJSON(value?: FeedItemType | null): any {
    return value as any;
}

export function FeedItemTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FeedItemType {
    return value as FeedItemType;
}

