/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What the reader said about an item they did not want -
 * docs/functional-spec/05-feed.md § Feedback.
 * 
 * Three kinds, and they are not three flavours of the same thing:
 * 
 *  - `not_interested` is about **this item**. It carries `bookmarkId` and
 *    nothing else, and the item never appears again in any scope.
 *  - `fewer_domain` is about a **source**. It carries `domain`, and it is a
 *    weight rather than a ban — "fewer", not "none", is what the menu says
 *    and what the ranker does.
 *  - `mute_topic` is about a **subject**. It carries `topic`, and everything
 *    tagged with it leaves the feed until the user unmutes it.
 * 
 * Dismissal outweighs any positive signal by three to one
 * (`dismissalWeight`), because a person who takes the trouble to tell a feed
 * it is wrong is giving it better evidence than a click ever does.
 * @export
 */
export const FeedFeedbackKind = {
    NotInterested: 'not_interested',
    FewerDomain: 'fewer_domain',
    MuteTopic: 'mute_topic'
} as const;
export type FeedFeedbackKind = typeof FeedFeedbackKind[keyof typeof FeedFeedbackKind];


export function instanceOfFeedFeedbackKind(value: any): boolean {
    for (const key in FeedFeedbackKind) {
        if (Object.prototype.hasOwnProperty.call(FeedFeedbackKind, key)) {
            if (FeedFeedbackKind[key as keyof typeof FeedFeedbackKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FeedFeedbackKindFromJSON(json: any): FeedFeedbackKind {
    return FeedFeedbackKindFromJSONTyped(json, false);
}

export function FeedFeedbackKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedFeedbackKind {
    return json as FeedFeedbackKind;
}

export function FeedFeedbackKindToJSON(value?: FeedFeedbackKind | null): any {
    return value as any;
}

export function FeedFeedbackKindToJSONTyped(value: any, ignoreDiscriminator: boolean): FeedFeedbackKind {
    return value as FeedFeedbackKind;
}

