/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedFeedbackKind } from './FeedFeedbackKind';
import {
    FeedFeedbackKindFromJSON,
    FeedFeedbackKindFromJSONTyped,
    FeedFeedbackKindToJSON,
    FeedFeedbackKindToJSONTyped,
} from './FeedFeedbackKind';

/**
 * One piece of feedback. Exactly one target field is required, and which one
 * is decided by `kind` — a `fewer_domain` with only a `bookmarkId` is a 400,
 * not a best effort, because guessing which domain the reader meant is
 * exactly the kind of "helpfulness" that mutes the wrong source.
 * @export
 * @interface FeedFeedbackRequest
 */
export interface FeedFeedbackRequest {
    /**
     * 
     * @type {FeedFeedbackKind}
     * @memberof FeedFeedbackRequest
     */
    kind: FeedFeedbackKind;
    /**
     * Required for `not_interested`. The item being dismissed.
     * @type {string}
     * @memberof FeedFeedbackRequest
     */
    bookmarkId?: string;
    /**
     * Required for `fewer_domain`. Bare host, `www.` stripped: `every.to`.
     * @type {string}
     * @memberof FeedFeedbackRequest
     */
    domain?: string;
    /**
     * Required for `mute_topic`. One `cosmicTags` entry, matched case-insensitively.
     * @type {string}
     * @memberof FeedFeedbackRequest
     */
    topic?: string;
}



/**
 * Check if a given object implements the FeedFeedbackRequest interface.
 */
export function instanceOfFeedFeedbackRequest(value: object): value is FeedFeedbackRequest {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function FeedFeedbackRequestFromJSON(json: any): FeedFeedbackRequest {
    return FeedFeedbackRequestFromJSONTyped(json, false);
}

export function FeedFeedbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedFeedbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': FeedFeedbackKindFromJSON(json['kind']),
        'bookmarkId': json['bookmarkId'] == null ? undefined : json['bookmarkId'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'topic': json['topic'] == null ? undefined : json['topic'],
    };
}

  export function FeedFeedbackRequestToJSON(json: any): FeedFeedbackRequest {
      return FeedFeedbackRequestToJSONTyped(json, false);
  }

  export function FeedFeedbackRequestToJSONTyped(value?: FeedFeedbackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': FeedFeedbackKindToJSON(value['kind']),
        'bookmarkId': value['bookmarkId'],
        'domain': value['domain'],
        'topic': value['topic'],
    };
}

