/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Which slice of the Home feed a request is about -
 * docs/functional-spec/05-feed.md § Scopes.
 * 
 * `for_you` is the default and the only one that mixes sources: own unread
 * saves, saves from followed users, and AI digests, ranked. `following` is
 * the same ranking over followed saves alone. `unread` is the user's own
 * unread saves in reverse chronological order with **no ranking at all** —
 * which is what makes it the place an item the ranker has stopped serving is
 * still reachable.
 * @export
 */
export const FeedScope = {
    ForYou: 'for_you',
    Following: 'following',
    Unread: 'unread'
} as const;
export type FeedScope = typeof FeedScope[keyof typeof FeedScope];


export function instanceOfFeedScope(value: any): boolean {
    for (const key in FeedScope) {
        if (Object.prototype.hasOwnProperty.call(FeedScope, key)) {
            if (FeedScope[key as keyof typeof FeedScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FeedScopeFromJSON(json: any): FeedScope {
    return FeedScopeFromJSONTyped(json, false);
}

export function FeedScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedScope {
    return json as FeedScope;
}

export function FeedScopeToJSON(value?: FeedScope | null): any {
    return value as any;
}

export function FeedScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): FeedScope {
    return value as FeedScope;
}

