/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedFeedbackKind } from './FeedFeedbackKind';
import {
    FeedFeedbackKindFromJSON,
    FeedFeedbackKindFromJSONTyped,
    FeedFeedbackKindToJSON,
    FeedFeedbackKindToJSONTyped,
} from './FeedFeedbackKind';

/**
 * What was recorded, echoed back.
 * 
 * Idempotent: sending the same feedback twice records one row and returns the
 * same answer. The ranked head is dropped as part of the write, which is what
 * makes "takes effect on the next request" true rather than aspirational —
 * without it the reader would keep seeing the dismissed item for the
 * remainder of the five-minute cache and reasonably conclude nothing
 * happened.
 * @export
 * @interface FeedFeedbackResponse
 */
export interface FeedFeedbackResponse {
    /**
     * 
     * @type {FeedFeedbackKind}
     * @memberof FeedFeedbackResponse
     */
    kind: FeedFeedbackKind;
    /**
     * 
     * @type {string}
     * @memberof FeedFeedbackResponse
     */
    bookmarkId?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedFeedbackResponse
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedFeedbackResponse
     */
    topic?: string;
    /**
     * True when the cached ranking was dropped, so the next request is recomputed.
     * @type {boolean}
     * @memberof FeedFeedbackResponse
     */
    rankingInvalidated: boolean;
}



/**
 * Check if a given object implements the FeedFeedbackResponse interface.
 */
export function instanceOfFeedFeedbackResponse(value: object): value is FeedFeedbackResponse {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('rankingInvalidated' in value) || value['rankingInvalidated'] === undefined) return false;
    return true;
}

export function FeedFeedbackResponseFromJSON(json: any): FeedFeedbackResponse {
    return FeedFeedbackResponseFromJSONTyped(json, false);
}

export function FeedFeedbackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedFeedbackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': FeedFeedbackKindFromJSON(json['kind']),
        'bookmarkId': json['bookmarkId'] == null ? undefined : json['bookmarkId'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'topic': json['topic'] == null ? undefined : json['topic'],
        'rankingInvalidated': json['rankingInvalidated'],
    };
}

  export function FeedFeedbackResponseToJSON(json: any): FeedFeedbackResponse {
      return FeedFeedbackResponseToJSONTyped(json, false);
  }

  export function FeedFeedbackResponseToJSONTyped(value?: FeedFeedbackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': FeedFeedbackKindToJSON(value['kind']),
        'bookmarkId': value['bookmarkId'],
        'domain': value['domain'],
        'topic': value['topic'],
        'rankingInvalidated': value['rankingInvalidated'],
    };
}

