/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedItem } from './FeedItem';
import {
    FeedItemFromJSON,
    FeedItemFromJSONTyped,
    FeedItemToJSON,
    FeedItemToJSONTyped,
} from './FeedItem';

/**
 * 
 * @export
 * @interface FeedResponse
 */
export interface FeedResponse {
    /**
     * 
     * @type {Array<FeedItem>}
     * @memberof FeedResponse
     */
    items: Array<FeedItem>;
    /**
     * Opaque cursor for the next page. Absent when this page is the last one.
     * 
     * It carries the ranking session it was produced under, not a position in
     * a list: the candidate set is re-ranked between requests, so an offset
     * would duplicate and skip.
     * @type {string}
     * @memberof FeedResponse
     */
    nextCursor?: string;
    /**
     * When this ranking was computed. Drives Home's "Updated n min ago".
     * @type {Date}
     * @memberof FeedResponse
     */
    computedAt: Date;
}

/**
 * Check if a given object implements the FeedResponse interface.
 */
export function instanceOfFeedResponse(value: object): value is FeedResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('computedAt' in value) || value['computedAt'] === undefined) return false;
    return true;
}

export function FeedResponseFromJSON(json: any): FeedResponse {
    return FeedResponseFromJSONTyped(json, false);
}

export function FeedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(FeedItemFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'computedAt': (new Date(json['computedAt'])),
    };
}

  export function FeedResponseToJSON(json: any): FeedResponse {
      return FeedResponseToJSONTyped(json, false);
  }

  export function FeedResponseToJSONTyped(value?: FeedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(FeedItemToJSON)),
        'nextCursor': value['nextCursor'],
        'computedAt': ((value['computedAt']).toISOString()),
    };
}

