/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The person a feed item reached the viewer through — everything the
 * provenance row draws, and nothing else.
 * 
 * Deliberately **not** `PublicProfile`. A page of 20 items can carry 20
 * distinct authors, and a `PublicProfile` carries four counts that cost a
 * query each; 80 count queries to render a name and a 22px avatar is not a
 * trade worth making. The handle is here, so the profile — counts and all —
 * is one link away at `GET /users/{handle}`.
 * @export
 * @interface FeedActor
 */
export interface FeedActor {
    /**
     * 
     * @type {string}
     * @memberof FeedActor
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FeedActor
     */
    handle: string;
    /**
     * 
     * @type {string}
     * @memberof FeedActor
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedActor
     */
    pictureUrl?: string;
}

/**
 * Check if a given object implements the FeedActor interface.
 */
export function instanceOfFeedActor(value: object): value is FeedActor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('handle' in value) || value['handle'] === undefined) return false;
    return true;
}

export function FeedActorFromJSON(json: any): FeedActor {
    return FeedActorFromJSONTyped(json, false);
}

export function FeedActorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedActor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'handle': json['handle'],
        'name': json['name'] == null ? undefined : json['name'],
        'pictureUrl': json['pictureUrl'] == null ? undefined : json['pictureUrl'],
    };
}

  export function FeedActorToJSON(json: any): FeedActor {
      return FeedActorToJSONTyped(json, false);
  }

  export function FeedActorToJSONTyped(value?: FeedActor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'handle': value['handle'],
        'name': value['name'],
        'pictureUrl': value['pictureUrl'],
    };
}

