/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedRailTopic } from './FeedRailTopic';
import {
    FeedRailTopicFromJSON,
    FeedRailTopicFromJSONTyped,
    FeedRailTopicToJSON,
    FeedRailTopicToJSONTyped,
} from './FeedRailTopic';
import type { FeedRailPerson } from './FeedRailPerson';
import {
    FeedRailPersonFromJSON,
    FeedRailPersonFromJSONTyped,
    FeedRailPersonToJSON,
    FeedRailPersonToJSONTyped,
} from './FeedRailPerson';

/**
 * Home's rail, in one request - docs/design-system/pages.md § Home.
 * 
 * Continue reading is deliberately **not** here: it already has a route
 * (`GET /bookmarks/continue-reading`) and duplicating it would give the same
 * list two definitions of "part-way through".
 * 
 * Nothing in the rail is unique to it. Below 900px the rail is not rendered
 * at all, and every destination it offers is reachable from Library, search,
 * or a profile — so a failure here dims a column rather than costing the
 * reader anything.
 * @export
 * @interface FeedRailResponse
 */
export interface FeedRailResponse {
    /**
     * 
     * @type {Array<FeedRailTopic>}
     * @memberof FeedRailResponse
     */
    topics: Array<FeedRailTopic>;
    /**
     * 
     * @type {Array<FeedRailPerson>}
     * @memberof FeedRailResponse
     */
    people: Array<FeedRailPerson>;
}

/**
 * Check if a given object implements the FeedRailResponse interface.
 */
export function instanceOfFeedRailResponse(value: object): value is FeedRailResponse {
    if (!('topics' in value) || value['topics'] === undefined) return false;
    if (!('people' in value) || value['people'] === undefined) return false;
    return true;
}

export function FeedRailResponseFromJSON(json: any): FeedRailResponse {
    return FeedRailResponseFromJSONTyped(json, false);
}

export function FeedRailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedRailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'topics': ((json['topics'] as Array<any>).map(FeedRailTopicFromJSON)),
        'people': ((json['people'] as Array<any>).map(FeedRailPersonFromJSON)),
    };
}

  export function FeedRailResponseToJSON(json: any): FeedRailResponse {
      return FeedRailResponseToJSONTyped(json, false);
  }

  export function FeedRailResponseToJSONTyped(value?: FeedRailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topics': ((value['topics'] as Array<any>).map(FeedRailTopicToJSON)),
        'people': ((value['people'] as Array<any>).map(FeedRailPersonToJSON)),
    };
}

