/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A tag the reader has been saving this week, and how many times.
 * @export
 * @interface FeedRailTopic
 */
export interface FeedRailTopic {
    /**
     * 
     * @type {string}
     * @memberof FeedRailTopic
     */
    topic: string;
    /**
     * 
     * @type {number}
     * @memberof FeedRailTopic
     */
    count: number;
}

/**
 * Check if a given object implements the FeedRailTopic interface.
 */
export function instanceOfFeedRailTopic(value: object): value is FeedRailTopic {
    if (!('topic' in value) || value['topic'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function FeedRailTopicFromJSON(json: any): FeedRailTopic {
    return FeedRailTopicFromJSONTyped(json, false);
}

export function FeedRailTopicFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedRailTopic {
    if (json == null) {
        return json;
    }
    return {
        
        'topic': json['topic'],
        'count': json['count'],
    };
}

  export function FeedRailTopicToJSON(json: any): FeedRailTopic {
      return FeedRailTopicToJSONTyped(json, false);
  }

  export function FeedRailTopicToJSONTyped(value?: FeedRailTopic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topic': value['topic'],
        'count': value['count'],
    };
}

