/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedError
 */
export interface FeedError {
    /**
     * 
     * @type {string}
     * @memberof FeedError
     */
    error: string;
}

/**
 * Check if a given object implements the FeedError interface.
 */
export function instanceOfFeedError(value: object): value is FeedError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function FeedErrorFromJSON(json: any): FeedError {
    return FeedErrorFromJSONTyped(json, false);
}

export function FeedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

  export function FeedErrorToJSON(json: any): FeedError {
      return FeedErrorToJSONTyped(json, false);
  }

  export function FeedErrorToJSONTyped(value?: FeedError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

