/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The state after the call, so an optimistic client can reconcile rather than guess.
 * @export
 * @interface FollowResponse
 */
export interface FollowResponse {
    /**
     * 
     * @type {boolean}
     * @memberof FollowResponse
     */
    following: boolean;
    /**
     * The target's follower count after the call.
     * @type {number}
     * @memberof FollowResponse
     */
    followerCount: number;
}

/**
 * Check if a given object implements the FollowResponse interface.
 */
export function instanceOfFollowResponse(value: object): value is FollowResponse {
    if (!('following' in value) || value['following'] === undefined) return false;
    if (!('followerCount' in value) || value['followerCount'] === undefined) return false;
    return true;
}

export function FollowResponseFromJSON(json: any): FollowResponse {
    return FollowResponseFromJSONTyped(json, false);
}

export function FollowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'following': json['following'],
        'followerCount': json['followerCount'],
    };
}

  export function FollowResponseToJSON(json: any): FollowResponse {
      return FollowResponseToJSONTyped(json, false);
  }

  export function FollowResponseToJSONTyped(value?: FollowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'following': value['following'],
        'followerCount': value['followerCount'],
    };
}

