/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionSuggestion } from './CollectionSuggestion';
import {
    CollectionSuggestionFromJSON,
    CollectionSuggestionFromJSONTyped,
    CollectionSuggestionToJSON,
    CollectionSuggestionToJSONTyped,
} from './CollectionSuggestion';

/**
 * 
 * @export
 * @interface GetCollectionSuggestionsResponse
 */
export interface GetCollectionSuggestionsResponse {
    /**
     * 
     * @type {Array<CollectionSuggestion>}
     * @memberof GetCollectionSuggestionsResponse
     */
    suggestions: Array<CollectionSuggestion>;
}

/**
 * Check if a given object implements the GetCollectionSuggestionsResponse interface.
 */
export function instanceOfGetCollectionSuggestionsResponse(value: object): value is GetCollectionSuggestionsResponse {
    if (!('suggestions' in value) || value['suggestions'] === undefined) return false;
    return true;
}

export function GetCollectionSuggestionsResponseFromJSON(json: any): GetCollectionSuggestionsResponse {
    return GetCollectionSuggestionsResponseFromJSONTyped(json, false);
}

export function GetCollectionSuggestionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCollectionSuggestionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestions': ((json['suggestions'] as Array<any>).map(CollectionSuggestionFromJSON)),
    };
}

  export function GetCollectionSuggestionsResponseToJSON(json: any): GetCollectionSuggestionsResponse {
      return GetCollectionSuggestionsResponseToJSONTyped(json, false);
  }

  export function GetCollectionSuggestionsResponseToJSONTyped(value?: GetCollectionSuggestionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestions': ((value['suggestions'] as Array<any>).map(CollectionSuggestionToJSON)),
    };
}

