/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * 
 * @export
 * @interface GetCollectionsResponse
 */
export interface GetCollectionsResponse {
    /**
     * 
     * @type {Array<Collection>}
     * @memberof GetCollectionsResponse
     */
    collections: Array<Collection>;
}

/**
 * Check if a given object implements the GetCollectionsResponse interface.
 */
export function instanceOfGetCollectionsResponse(value: object): value is GetCollectionsResponse {
    if (!('collections' in value) || value['collections'] === undefined) return false;
    return true;
}

export function GetCollectionsResponseFromJSON(json: any): GetCollectionsResponse {
    return GetCollectionsResponseFromJSONTyped(json, false);
}

export function GetCollectionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCollectionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collections': ((json['collections'] as Array<any>).map(CollectionFromJSON)),
    };
}

  export function GetCollectionsResponseToJSON(json: any): GetCollectionsResponse {
      return GetCollectionsResponseToJSONTyped(json, false);
  }

  export function GetCollectionsResponseToJSONTyped(value?: GetCollectionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collections': ((value['collections'] as Array<any>).map(CollectionToJSON)),
    };
}

