/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Highlight } from './Highlight';
import {
    HighlightFromJSON,
    HighlightFromJSONTyped,
    HighlightToJSON,
    HighlightToJSONTyped,
} from './Highlight';

/**
 * 
 * @export
 * @interface GetHighlightsResponse
 */
export interface GetHighlightsResponse {
    /**
     * 
     * @type {Array<Highlight>}
     * @memberof GetHighlightsResponse
     */
    highlights: Array<Highlight>;
}

/**
 * Check if a given object implements the GetHighlightsResponse interface.
 */
export function instanceOfGetHighlightsResponse(value: object): value is GetHighlightsResponse {
    if (!('highlights' in value) || value['highlights'] === undefined) return false;
    return true;
}

export function GetHighlightsResponseFromJSON(json: any): GetHighlightsResponse {
    return GetHighlightsResponseFromJSONTyped(json, false);
}

export function GetHighlightsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHighlightsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'highlights': ((json['highlights'] as Array<any>).map(HighlightFromJSON)),
    };
}

  export function GetHighlightsResponseToJSON(json: any): GetHighlightsResponse {
      return GetHighlightsResponseToJSONTyped(json, false);
  }

  export function GetHighlightsResponseToJSONTyped(value?: GetHighlightsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'highlights': ((value['highlights'] as Array<any>).map(HighlightToJSON)),
    };
}

