/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReadingProgress } from './ReadingProgress';
import {
    ReadingProgressFromJSON,
    ReadingProgressFromJSONTyped,
    ReadingProgressToJSON,
    ReadingProgressToJSONTyped,
} from './ReadingProgress';

/**
 * Where the reader left off, or nothing if they never started.
 * 
 * `null` and a `percent` of 0 are different answers: the first says the
 * bookmark has never been opened, the second that it was opened and not
 * scrolled. The reader restores a scroll position for the second and not for
 * the first.
 * @export
 * @interface GetReadingProgressResponse
 */
export interface GetReadingProgressResponse {
    /**
     * 
     * @type {ReadingProgress}
     * @memberof GetReadingProgressResponse
     */
    progress: ReadingProgress | null;
}

/**
 * Check if a given object implements the GetReadingProgressResponse interface.
 */
export function instanceOfGetReadingProgressResponse(value: object): value is GetReadingProgressResponse {
    if (!('progress' in value) || value['progress'] === undefined) return false;
    return true;
}

export function GetReadingProgressResponseFromJSON(json: any): GetReadingProgressResponse {
    return GetReadingProgressResponseFromJSONTyped(json, false);
}

export function GetReadingProgressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReadingProgressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'progress': ReadingProgressFromJSON(json['progress']),
    };
}

  export function GetReadingProgressResponseToJSON(json: any): GetReadingProgressResponse {
      return GetReadingProgressResponseToJSONTyped(json, false);
  }

  export function GetReadingProgressResponseToJSONTyped(value?: GetReadingProgressResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'progress': ReadingProgressToJSON(value['progress']),
    };
}

