/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A span of extracted content the reader kept.
 * 
 * Anchored by `quote` plus a short `prefix` and `suffix`, never by character
 * offsets: the pipeline re-extracts a page on every reprocess and offsets
 * would then point silently at the wrong sentence. Resolution against the
 * current extraction happens on the client, in shared code, so a highlight
 * that can no longer be placed is reported as orphaned rather than drawn in
 * the wrong place.
 * 
 * Private to its author even when the bookmark is public.
 * @export
 * @interface Highlight
 */
export interface Highlight {
    /**
     * 
     * @type {string}
     * @memberof Highlight
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Highlight
     */
    bookmarkId: string;
    /**
     * 
     * @type {string}
     * @memberof Highlight
     */
    userId: string;
    /**
     * The selected text, whitespace-normalised. At most 2000 characters.
     * @type {string}
     * @memberof Highlight
     */
    quote: string;
    /**
     * ~32 characters immediately before the quote. Disambiguates a quote that occurs twice, and re-finds one whose own words changed.
     * @type {string}
     * @memberof Highlight
     */
    prefix?: string;
    /**
     * ~32 characters immediately after the quote.
     * @type {string}
     * @memberof Highlight
     */
    suffix?: string;
    /**
     * The reader's own note. The only mutable field on a highlight.
     * @type {string}
     * @memberof Highlight
     */
    note?: string;
    /**
     * 
     * @type {Date}
     * @memberof Highlight
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Highlight interface.
 */
export function instanceOfHighlight(value: object): value is Highlight {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bookmarkId' in value) || value['bookmarkId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('quote' in value) || value['quote'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function HighlightFromJSON(json: any): Highlight {
    return HighlightFromJSONTyped(json, false);
}

export function HighlightFromJSONTyped(json: any, ignoreDiscriminator: boolean): Highlight {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bookmarkId': json['bookmarkId'],
        'userId': json['userId'],
        'quote': json['quote'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'note': json['note'] == null ? undefined : json['note'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

  export function HighlightToJSON(json: any): Highlight {
      return HighlightToJSONTyped(json, false);
  }

  export function HighlightToJSONTyped(value?: Highlight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bookmarkId': value['bookmarkId'],
        'userId': value['userId'],
        'quote': value['quote'],
        'prefix': value['prefix'],
        'suffix': value['suffix'],
        'note': value['note'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

