/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HybridSearchResultItem } from './HybridSearchResultItem';
import {
    HybridSearchResultItemFromJSON,
    HybridSearchResultItemFromJSONTyped,
    HybridSearchResultItemToJSON,
    HybridSearchResultItemToJSONTyped,
} from './HybridSearchResultItem';

/**
 * 
 * @export
 * @interface HybridSearchResponse
 */
export interface HybridSearchResponse {
    /**
     * 
     * @type {Array<HybridSearchResultItem>}
     * @memberof HybridSearchResponse
     */
    results: Array<HybridSearchResultItem>;
}

/**
 * Check if a given object implements the HybridSearchResponse interface.
 */
export function instanceOfHybridSearchResponse(value: object): value is HybridSearchResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function HybridSearchResponseFromJSON(json: any): HybridSearchResponse {
    return HybridSearchResponseFromJSONTyped(json, false);
}

export function HybridSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HybridSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(HybridSearchResultItemFromJSON)),
    };
}

  export function HybridSearchResponseToJSON(json: any): HybridSearchResponse {
      return HybridSearchResponseToJSONTyped(json, false);
  }

  export function HybridSearchResponseToJSONTyped(value?: HybridSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(HybridSearchResultItemToJSON)),
    };
}

