/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeResponse
 */
export interface LikeResponse {
    /**
     * 
     * @type {number}
     * @memberof LikeResponse
     */
    likeCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof LikeResponse
     */
    isLikedByCurrentUser: boolean;
}

/**
 * Check if a given object implements the LikeResponse interface.
 */
export function instanceOfLikeResponse(value: object): value is LikeResponse {
    if (!('likeCount' in value) || value['likeCount'] === undefined) return false;
    if (!('isLikedByCurrentUser' in value) || value['isLikedByCurrentUser'] === undefined) return false;
    return true;
}

export function LikeResponseFromJSON(json: any): LikeResponse {
    return LikeResponseFromJSONTyped(json, false);
}

export function LikeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'likeCount': json['likeCount'],
        'isLikedByCurrentUser': json['isLikedByCurrentUser'],
    };
}

  export function LikeResponseToJSON(json: any): LikeResponse {
      return LikeResponseToJSONTyped(json, false);
  }

  export function LikeResponseToJSONTyped(value?: LikeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'likeCount': value['likeCount'],
        'isLikedByCurrentUser': value['isLikedByCurrentUser'],
    };
}

