/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NoteSectionType = {
    Text: 'text'
} as const;
export type NoteSectionType = typeof NoteSectionType[keyof typeof NoteSectionType];


export function instanceOfNoteSectionType(value: any): boolean {
    for (const key in NoteSectionType) {
        if (Object.prototype.hasOwnProperty.call(NoteSectionType, key)) {
            if (NoteSectionType[key as keyof typeof NoteSectionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NoteSectionTypeFromJSON(json: any): NoteSectionType {
    return NoteSectionTypeFromJSONTyped(json, false);
}

export function NoteSectionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteSectionType {
    return json as NoteSectionType;
}

export function NoteSectionTypeToJSON(value?: NoteSectionType | null): any {
    return value as any;
}

export function NoteSectionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): NoteSectionType {
    return value as NoteSectionType;
}

