/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NoteType = {
    Fup: 'fup',
    Chatter: 'chatter',
    Knowledge: 'knowledge',
    Task: 'task'
} as const;
export type NoteType = typeof NoteType[keyof typeof NoteType];


export function instanceOfNoteType(value: any): boolean {
    for (const key in NoteType) {
        if (Object.prototype.hasOwnProperty.call(NoteType, key)) {
            if (NoteType[key as keyof typeof NoteType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NoteTypeFromJSON(json: any): NoteType {
    return NoteTypeFromJSONTyped(json, false);
}

export function NoteTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteType {
    return json as NoteType;
}

export function NoteTypeToJSON(value?: NoteType | null): any {
    return value as any;
}

export function NoteTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): NoteType {
    return value as NoteType;
}

