/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NoteType } from './NoteType';
import {
    NoteTypeFromJSON,
    NoteTypeFromJSONTyped,
    NoteTypeToJSON,
    NoteTypeToJSONTyped,
} from './NoteType';
import type { Resource } from './Resource';
import {
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
    ResourceToJSONTyped,
} from './Resource';

/**
 * 
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    documentId?: number;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    body: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Note
     */
    tags?: Array<string>;
    /**
     * 
     * @type {NoteType}
     * @memberof Note
     */
    type: NoteType;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    createdAt: string;
    /**
     * 
     * @type {Array<Resource>}
     * @memberof Note
     */
    resources?: Array<Resource>;
}



/**
 * Check if a given object implements the Note interface.
 */
export function instanceOfNote(value: object): value is Note {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function NoteFromJSON(json: any): Note {
    return NoteFromJSONTyped(json, false);
}

export function NoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Note {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'documentId': json['documentId'] == null ? undefined : json['documentId'],
        'title': json['title'],
        'summary': json['summary'],
        'body': json['body'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'type': NoteTypeFromJSON(json['type']),
        'userId': json['userId'],
        'createdAt': json['createdAt'],
        'resources': json['resources'] == null ? undefined : ((json['resources'] as Array<any>).map(ResourceFromJSON)),
    };
}

  export function NoteToJSON(json: any): Note {
      return NoteToJSONTyped(json, false);
  }

  export function NoteToJSONTyped(value?: Note | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'documentId': value['documentId'],
        'title': value['title'],
        'summary': value['summary'],
        'body': value['body'],
        'tags': value['tags'],
        'type': NoteTypeToJSON(value['type']),
        'userId': value['userId'],
        'createdAt': value['createdAt'],
        'resources': value['resources'] == null ? undefined : ((value['resources'] as Array<any>).map(ResourceToJSON)),
    };
}

