/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenGraphMetadata
 */
export interface OpenGraphMetadata {
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    favicon?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    siteName?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    articleAuthor?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    articlePublishedTime?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    articleModifiedTime?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraphMetadata
     */
    articleSection?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OpenGraphMetadata
     */
    articleTag?: Array<string>;
}

/**
 * Check if a given object implements the OpenGraphMetadata interface.
 */
export function instanceOfOpenGraphMetadata(value: object): value is OpenGraphMetadata {
    return true;
}

export function OpenGraphMetadataFromJSON(json: any): OpenGraphMetadata {
    return OpenGraphMetadataFromJSONTyped(json, false);
}

export function OpenGraphMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenGraphMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'favicon': json['favicon'] == null ? undefined : json['favicon'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'] == null ? undefined : json['image'],
        'url': json['url'] == null ? undefined : json['url'],
        'siteName': json['site_name'] == null ? undefined : json['site_name'],
        'type': json['type'] == null ? undefined : json['type'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'articleAuthor': json['article_author'] == null ? undefined : json['article_author'],
        'articlePublishedTime': json['article_published_time'] == null ? undefined : json['article_published_time'],
        'articleModifiedTime': json['article_modified_time'] == null ? undefined : json['article_modified_time'],
        'articleSection': json['article_section'] == null ? undefined : json['article_section'],
        'articleTag': json['article_tag'] == null ? undefined : json['article_tag'],
    };
}

  export function OpenGraphMetadataToJSON(json: any): OpenGraphMetadata {
      return OpenGraphMetadataToJSONTyped(json, false);
  }

  export function OpenGraphMetadataToJSONTyped(value?: OpenGraphMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'favicon': value['favicon'],
        'title': value['title'],
        'description': value['description'],
        'image': value['image'],
        'url': value['url'],
        'site_name': value['siteName'],
        'type': value['type'],
        'locale': value['locale'],
        'article_author': value['articleAuthor'],
        'article_published_time': value['articlePublishedTime'],
        'article_modified_time': value['articleModifiedTime'],
        'article_section': value['articleSection'],
        'article_tag': value['articleTag'],
    };
}

