/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpenGraph
 */
export interface OpenGraph {
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    siteName?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    imageAlt?: string;
    /**
     * 
     * @type {number}
     * @memberof OpenGraph
     */
    imageWidth?: number;
    /**
     * 
     * @type {number}
     * @memberof OpenGraph
     */
    imageHeight?: number;
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    articlePublishedTime?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenGraph
     */
    articleModifiedTime?: string;
}

/**
 * Check if a given object implements the OpenGraph interface.
 */
export function instanceOfOpenGraph(value: object): value is OpenGraph {
    return true;
}

export function OpenGraphFromJSON(json: any): OpenGraph {
    return OpenGraphFromJSONTyped(json, false);
}

export function OpenGraphFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenGraph {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'] == null ? undefined : json['url'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'siteName': json['siteName'] == null ? undefined : json['siteName'],
        'image': json['image'] == null ? undefined : json['image'],
        'imageAlt': json['imageAlt'] == null ? undefined : json['imageAlt'],
        'imageWidth': json['imageWidth'] == null ? undefined : json['imageWidth'],
        'imageHeight': json['imageHeight'] == null ? undefined : json['imageHeight'],
        'articlePublishedTime': json['articlePublishedTime'] == null ? undefined : json['articlePublishedTime'],
        'articleModifiedTime': json['articleModifiedTime'] == null ? undefined : json['articleModifiedTime'],
    };
}

  export function OpenGraphToJSON(json: any): OpenGraph {
      return OpenGraphToJSONTyped(json, false);
  }

  export function OpenGraphToJSONTyped(value?: OpenGraph | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'url': value['url'],
        'title': value['title'],
        'description': value['description'],
        'siteName': value['siteName'],
        'image': value['image'],
        'imageAlt': value['imageAlt'],
        'imageWidth': value['imageWidth'],
        'imageHeight': value['imageHeight'],
        'articlePublishedTime': value['articlePublishedTime'],
        'articleModifiedTime': value['articleModifiedTime'],
    };
}

