/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PipelineStatus = {
    Pending: 'pending',
    Running: 'running',
    Complete: 'complete',
    Failed: 'failed'
} as const;
export type PipelineStatus = typeof PipelineStatus[keyof typeof PipelineStatus];


export function instanceOfPipelineStatus(value: any): boolean {
    for (const key in PipelineStatus) {
        if (Object.prototype.hasOwnProperty.call(PipelineStatus, key)) {
            if (PipelineStatus[key as keyof typeof PipelineStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PipelineStatusFromJSON(json: any): PipelineStatus {
    return PipelineStatusFromJSONTyped(json, false);
}

export function PipelineStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineStatus {
    return json as PipelineStatus;
}

export function PipelineStatusToJSON(value?: PipelineStatus | null): any {
    return value as any;
}

export function PipelineStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PipelineStatus {
    return value as PipelineStatus;
}

