/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineStatus } from './PipelineStatus';
import {
    PipelineStatusFromJSON,
    PipelineStatusFromJSONTyped,
    PipelineStatusToJSON,
    PipelineStatusToJSONTyped,
} from './PipelineStatus';

/**
 * 
 * @export
 * @interface PipelineStage
 */
export interface PipelineStage {
    /**
     * 
     * @type {number}
     * @memberof PipelineStage
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PipelineStage
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineStage
     */
    key: string;
    /**
     * 
     * @type {PipelineStatus}
     * @memberof PipelineStage
     */
    status: PipelineStatus;
    /**
     * 
     * @type {Date}
     * @memberof PipelineStage
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PipelineStage
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the PipelineStage interface.
 */
export function instanceOfPipelineStage(value: object): value is PipelineStage {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PipelineStageFromJSON(json: any): PipelineStage {
    return PipelineStageFromJSONTyped(json, false);
}

export function PipelineStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineStage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'key': json['key'],
        'status': PipelineStatusFromJSON(json['status']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

  export function PipelineStageToJSON(json: any): PipelineStage {
      return PipelineStageToJSONTyped(json, false);
  }

  export function PipelineStageToJSONTyped(value?: PipelineStage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'key': value['key'],
        'status': PipelineStatusToJSON(value['status']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

