/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineStatus } from './PipelineStatus';
import {
    PipelineStatusFromJSON,
    PipelineStatusFromJSONTyped,
    PipelineStatusToJSON,
    PipelineStatusToJSONTyped,
} from './PipelineStatus';
import type { PipelineStage } from './PipelineStage';
import {
    PipelineStageFromJSON,
    PipelineStageFromJSONTyped,
    PipelineStageToJSON,
    PipelineStageToJSONTyped,
} from './PipelineStage';

/**
 * 
 * @export
 * @interface Pipeline
 */
export interface Pipeline {
    /**
     * 
     * @type {number}
     * @memberof Pipeline
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Pipeline
     */
    refId?: number;
    /**
     * 
     * @type {Array<PipelineStage>}
     * @memberof Pipeline
     */
    stages: Array<PipelineStage>;
    /**
     * 
     * @type {PipelineStatus}
     * @memberof Pipeline
     */
    status: PipelineStatus;
    /**
     * 
     * @type {Date}
     * @memberof Pipeline
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Pipeline interface.
 */
export function instanceOfPipeline(value: object): value is Pipeline {
    if (!('stages' in value) || value['stages'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PipelineFromJSON(json: any): Pipeline {
    return PipelineFromJSONTyped(json, false);
}

export function PipelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pipeline {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'refId': json['refId'] == null ? undefined : json['refId'],
        'stages': ((json['stages'] as Array<any>).map(PipelineStageFromJSON)),
        'status': PipelineStatusFromJSON(json['status']),
        'createdAt': (new Date(json['createdAt'])),
    };
}

  export function PipelineToJSON(json: any): Pipeline {
      return PipelineToJSONTyped(json, false);
  }

  export function PipelineToJSONTyped(value?: Pipeline | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'refId': value['refId'],
        'stages': ((value['stages'] as Array<any>).map(PipelineStageToJSON)),
        'status': PipelineStatusToJSON(value['status']),
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

