/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreviewMetadata
 */
export interface PreviewMetadata {
    /**
     * 
     * @type {string}
     * @memberof PreviewMetadata
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PreviewMetadata
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PreviewMetadata
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof PreviewMetadata
     */
    favicon?: string;
    /**
     * 
     * @type {string}
     * @memberof PreviewMetadata
     */
    siteName?: string;
    /**
     * 
     * @type {string}
     * @memberof PreviewMetadata
     */
    url: string;
}

/**
 * Check if a given object implements the PreviewMetadata interface.
 */
export function instanceOfPreviewMetadata(value: object): value is PreviewMetadata {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PreviewMetadataFromJSON(json: any): PreviewMetadata {
    return PreviewMetadataFromJSONTyped(json, false);
}

export function PreviewMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'] == null ? undefined : json['image'],
        'favicon': json['favicon'] == null ? undefined : json['favicon'],
        'siteName': json['siteName'] == null ? undefined : json['siteName'],
        'url': json['url'],
    };
}

  export function PreviewMetadataToJSON(json: any): PreviewMetadata {
      return PreviewMetadataToJSONTyped(json, false);
  }

  export function PreviewMetadataToJSONTyped(value?: PreviewMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'image': value['image'],
        'favicon': value['favicon'],
        'siteName': value['siteName'],
        'url': value['url'],
    };
}

