/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PreviewMetadata } from './PreviewMetadata';
import {
    PreviewMetadataFromJSON,
    PreviewMetadataFromJSONTyped,
    PreviewMetadataToJSON,
    PreviewMetadataToJSONTyped,
} from './PreviewMetadata';

/**
 * 
 * @export
 * @interface PreviewResponse
 */
export interface PreviewResponse {
    /**
     * 
     * @type {PreviewMetadata}
     * @memberof PreviewResponse
     */
    metadata: PreviewMetadata;
    /**
     * 
     * @type {boolean}
     * @memberof PreviewResponse
     */
    scrapable: boolean;
}

/**
 * Check if a given object implements the PreviewResponse interface.
 */
export function instanceOfPreviewResponse(value: object): value is PreviewResponse {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('scrapable' in value) || value['scrapable'] === undefined) return false;
    return true;
}

export function PreviewResponseFromJSON(json: any): PreviewResponse {
    return PreviewResponseFromJSONTyped(json, false);
}

export function PreviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': PreviewMetadataFromJSON(json['metadata']),
        'scrapable': json['scrapable'],
    };
}

  export function PreviewResponseToJSON(json: any): PreviewResponse {
      return PreviewResponseToJSONTyped(json, false);
  }

  export function PreviewResponseToJSONTyped(value?: PreviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': PreviewMetadataToJSON(value['metadata']),
        'scrapable': value['scrapable'],
    };
}

