/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The caller's own profile.
 * 
 * The only profile shape that carries an email, because it is the caller's
 * own. Everything anyone else sees is a `PublicProfile`.
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    pictureUrl?: string;
    /**
     * Absent only in the degraded case where a handle could not be minted at signup.
     * @type {string}
     * @memberof Profile
     */
    handle?: string;
    /**
     * False when the handle was reserved from the email local part at signup
     * or by the backfill, and never confirmed by a person.
     * 
     * This is what the claim prompt hangs off: existing accounts were given a
     * working handle so `/u/{handle}` and `/my/profile` never broke, and are
     * asked to confirm or change it once.
     * @type {boolean}
     * @memberof Profile
     */
    handleClaimed: boolean;
    /**
     * When the handle may next be changed. Absent when it may be changed now. Confirming a reserved handle unchanged is not a change and does not start the clock.
     * @type {Date}
     * @memberof Profile
     */
    handleChangeAvailableAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Profile
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Profile
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): value is Profile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('handleClaimed' in value) || value['handleClaimed'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'pictureUrl': json['pictureUrl'] == null ? undefined : json['pictureUrl'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'handleClaimed': json['handleClaimed'],
        'handleChangeAvailableAt': json['handleChangeAvailableAt'] == null ? undefined : (new Date(json['handleChangeAvailableAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

  export function ProfileToJSON(json: any): Profile {
      return ProfileToJSONTyped(json, false);
  }

  export function ProfileToJSONTyped(value?: Profile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'pictureUrl': value['pictureUrl'],
        'handle': value['handle'],
        'handleClaimed': value['handleClaimed'],
        'handleChangeAvailableAt': value['handleChangeAvailableAt'] == null ? undefined : ((value['handleChangeAvailableAt']).toISOString()),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

