/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A collection as anyone is allowed to see it.
 * 
 * `saveCount` counts **public, non-archived** saves only. The size of the
 * private half of a public collection is not a number anyone else gets, which
 * is why this is not `Collection` with a field removed.
 * @export
 * @interface PublicCollection
 */
export interface PublicCollection {
    /**
     * 
     * @type {string}
     * @memberof PublicCollection
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCollection
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCollection
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PublicCollection
     */
    saveCount: number;
    /**
     * 
     * @type {Date}
     * @memberof PublicCollection
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PublicCollection interface.
 */
export function instanceOfPublicCollection(value: object): value is PublicCollection {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('saveCount' in value) || value['saveCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PublicCollectionFromJSON(json: any): PublicCollection {
    return PublicCollectionFromJSONTyped(json, false);
}

export function PublicCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'saveCount': json['saveCount'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

  export function PublicCollectionToJSON(json: any): PublicCollection {
      return PublicCollectionToJSONTyped(json, false);
  }

  export function PublicCollectionToJSONTyped(value?: PublicCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'saveCount': value['saveCount'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

