/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicProfileCounts } from './PublicProfileCounts';
import {
    PublicProfileCountsFromJSON,
    PublicProfileCountsFromJSONTyped,
    PublicProfileCountsToJSON,
    PublicProfileCountsToJSONTyped,
} from './PublicProfileCounts';

/**
 * A profile as anyone is allowed to see it.
 * 
 * **There is no `email` field here, and there must never be one**
 * (docs/functional-spec/06-social.md § Profiles). This is not a rule the
 * handlers remember to apply: the repository selects an explicit column list
 * that omits `email`, `PublicProfile` in `packages/shared` is a standalone
 * type rather than an `Omit<Profile, "email">` that would inherit new fields
 * for free, and a compile-time assertion fails the build if the field ever
 * appears. This model is the fourth lock, and the one a client can see.
 * @export
 * @interface PublicProfile
 */
export interface PublicProfile {
    /**
     * 
     * @type {string}
     * @memberof PublicProfile
     */
    id: string;
    /**
     * The stable public identity. `/u/{handle}` is the canonical profile URL.
     * @type {string}
     * @memberof PublicProfile
     */
    handle: string;
    /**
     * 
     * @type {string}
     * @memberof PublicProfile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicProfile
     */
    pictureUrl?: string;
    /**
     * When the account was created. The only date a public profile carries.
     * @type {Date}
     * @memberof PublicProfile
     */
    joinedAt: Date;
    /**
     * 
     * @type {PublicProfileCounts}
     * @memberof PublicProfile
     */
    counts: PublicProfileCounts;
    /**
     * True when this profile is the caller's own.
     * @type {boolean}
     * @memberof PublicProfile
     */
    isSelf: boolean;
    /**
     * True when the caller follows this profile. Absent on anonymous reads and in list responses, where the relationship is not computed per row.
     * @type {boolean}
     * @memberof PublicProfile
     */
    isFollowedByViewer?: boolean;
    /**
     * True when this profile follows the caller.
     * @type {boolean}
     * @memberof PublicProfile
     */
    followsViewer?: boolean;
    /**
     * True when the caller has blocked this profile. A blocked profile stays reachable so the block can be undone from it; its saves do not.
     * @type {boolean}
     * @memberof PublicProfile
     */
    isBlockedByViewer?: boolean;
}

/**
 * Check if a given object implements the PublicProfile interface.
 */
export function instanceOfPublicProfile(value: object): value is PublicProfile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('handle' in value) || value['handle'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    if (!('counts' in value) || value['counts'] === undefined) return false;
    if (!('isSelf' in value) || value['isSelf'] === undefined) return false;
    return true;
}

export function PublicProfileFromJSON(json: any): PublicProfile {
    return PublicProfileFromJSONTyped(json, false);
}

export function PublicProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'handle': json['handle'],
        'name': json['name'] == null ? undefined : json['name'],
        'pictureUrl': json['pictureUrl'] == null ? undefined : json['pictureUrl'],
        'joinedAt': (new Date(json['joinedAt'])),
        'counts': PublicProfileCountsFromJSON(json['counts']),
        'isSelf': json['isSelf'],
        'isFollowedByViewer': json['isFollowedByViewer'] == null ? undefined : json['isFollowedByViewer'],
        'followsViewer': json['followsViewer'] == null ? undefined : json['followsViewer'],
        'isBlockedByViewer': json['isBlockedByViewer'] == null ? undefined : json['isBlockedByViewer'],
    };
}

  export function PublicProfileToJSON(json: any): PublicProfile {
      return PublicProfileToJSONTyped(json, false);
  }

  export function PublicProfileToJSONTyped(value?: PublicProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'handle': value['handle'],
        'name': value['name'],
        'pictureUrl': value['pictureUrl'],
        'joinedAt': ((value['joinedAt']).toISOString()),
        'counts': PublicProfileCountsToJSON(value['counts']),
        'isSelf': value['isSelf'],
        'isFollowedByViewer': value['isFollowedByViewer'],
        'followsViewer': value['followsViewer'],
        'isBlockedByViewer': value['isBlockedByViewer'],
    };
}

