/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicCollection } from './PublicCollection';
import {
    PublicCollectionFromJSON,
    PublicCollectionFromJSONTyped,
    PublicCollectionToJSON,
    PublicCollectionToJSONTyped,
} from './PublicCollection';

/**
 * 
 * @export
 * @interface PublicCollectionListResponse
 */
export interface PublicCollectionListResponse {
    /**
     * 
     * @type {Array<PublicCollection>}
     * @memberof PublicCollectionListResponse
     */
    collections: Array<PublicCollection>;
    /**
     * Absent when this page is the last one.
     * @type {string}
     * @memberof PublicCollectionListResponse
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the PublicCollectionListResponse interface.
 */
export function instanceOfPublicCollectionListResponse(value: object): value is PublicCollectionListResponse {
    if (!('collections' in value) || value['collections'] === undefined) return false;
    return true;
}

export function PublicCollectionListResponseFromJSON(json: any): PublicCollectionListResponse {
    return PublicCollectionListResponseFromJSONTyped(json, false);
}

export function PublicCollectionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCollectionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collections': ((json['collections'] as Array<any>).map(PublicCollectionFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
    };
}

  export function PublicCollectionListResponseToJSON(json: any): PublicCollectionListResponse {
      return PublicCollectionListResponseToJSONTyped(json, false);
  }

  export function PublicCollectionListResponseToJSONTyped(value?: PublicCollectionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collections': ((value['collections'] as Array<any>).map(PublicCollectionToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

