/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Public counts only. The size of someone's private library is theirs.
 * @export
 * @interface PublicProfileCounts
 */
export interface PublicProfileCounts {
    /**
     * 
     * @type {number}
     * @memberof PublicProfileCounts
     */
    followers: number;
    /**
     * 
     * @type {number}
     * @memberof PublicProfileCounts
     */
    following: number;
    /**
     * 
     * @type {number}
     * @memberof PublicProfileCounts
     */
    publicSaves: number;
    /**
     * 
     * @type {number}
     * @memberof PublicProfileCounts
     */
    collections: number;
}

/**
 * Check if a given object implements the PublicProfileCounts interface.
 */
export function instanceOfPublicProfileCounts(value: object): value is PublicProfileCounts {
    if (!('followers' in value) || value['followers'] === undefined) return false;
    if (!('following' in value) || value['following'] === undefined) return false;
    if (!('publicSaves' in value) || value['publicSaves'] === undefined) return false;
    if (!('collections' in value) || value['collections'] === undefined) return false;
    return true;
}

export function PublicProfileCountsFromJSON(json: any): PublicProfileCounts {
    return PublicProfileCountsFromJSONTyped(json, false);
}

export function PublicProfileCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicProfileCounts {
    if (json == null) {
        return json;
    }
    return {
        
        'followers': json['followers'],
        'following': json['following'],
        'publicSaves': json['publicSaves'],
        'collections': json['collections'],
    };
}

  export function PublicProfileCountsToJSON(json: any): PublicProfileCounts {
      return PublicProfileCountsToJSONTyped(json, false);
  }

  export function PublicProfileCountsToJSONTyped(value?: PublicProfileCounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'followers': value['followers'],
        'following': value['following'],
        'publicSaves': value['publicSaves'],
        'collections': value['collections'],
    };
}

