/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicProfile } from './PublicProfile';
import {
    PublicProfileFromJSON,
    PublicProfileFromJSONTyped,
    PublicProfileToJSON,
    PublicProfileToJSONTyped,
} from './PublicProfile';

/**
 * 
 * @export
 * @interface PublicProfileListResponse
 */
export interface PublicProfileListResponse {
    /**
     * 
     * @type {Array<PublicProfile>}
     * @memberof PublicProfileListResponse
     */
    profiles: Array<PublicProfile>;
    /**
     * Absent when this page is the last one.
     * @type {string}
     * @memberof PublicProfileListResponse
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the PublicProfileListResponse interface.
 */
export function instanceOfPublicProfileListResponse(value: object): value is PublicProfileListResponse {
    if (!('profiles' in value) || value['profiles'] === undefined) return false;
    return true;
}

export function PublicProfileListResponseFromJSON(json: any): PublicProfileListResponse {
    return PublicProfileListResponseFromJSONTyped(json, false);
}

export function PublicProfileListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicProfileListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'profiles': ((json['profiles'] as Array<any>).map(PublicProfileFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
    };
}

  export function PublicProfileListResponseToJSON(json: any): PublicProfileListResponse {
      return PublicProfileListResponseToJSONTyped(json, false);
  }

  export function PublicProfileListResponseToJSONTyped(value?: PublicProfileListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profiles': ((value['profiles'] as Array<any>).map(PublicProfileToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

