/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bookmark } from './Bookmark';
import {
    BookmarkFromJSON,
    BookmarkFromJSONTyped,
    BookmarkToJSON,
    BookmarkToJSONTyped,
} from './Bookmark';

/**
 * 
 * @export
 * @interface PublicSavesResponse
 */
export interface PublicSavesResponse {
    /**
     * 
     * @type {Array<Bookmark>}
     * @memberof PublicSavesResponse
     */
    bookmarks: Array<Bookmark>;
    /**
     * Absent when this page is the last one.
     * @type {string}
     * @memberof PublicSavesResponse
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the PublicSavesResponse interface.
 */
export function instanceOfPublicSavesResponse(value: object): value is PublicSavesResponse {
    if (!('bookmarks' in value) || value['bookmarks'] === undefined) return false;
    return true;
}

export function PublicSavesResponseFromJSON(json: any): PublicSavesResponse {
    return PublicSavesResponseFromJSONTyped(json, false);
}

export function PublicSavesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSavesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarks': ((json['bookmarks'] as Array<any>).map(BookmarkFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
    };
}

  export function PublicSavesResponseToJSON(json: any): PublicSavesResponse {
      return PublicSavesResponseToJSONTyped(json, false);
  }

  export function PublicSavesResponseToJSONTyped(value?: PublicSavesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmarks': ((value['bookmarks'] as Array<any>).map(BookmarkToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

