/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One signal's contribution to one item's score. Debugging only - present
 * outside production, absent in it. Never the source of the reason string:
 * `rankingReason` is written by the ranker, which is the only thing that
 * knows what it actually weighted.
 * @export
 * @interface RankingSignal
 */
export interface RankingSignal {
    /**
     * `topic_affinity`, `source_affinity`, `recency`, `social_proof`, `effort_fit`, `novelty`.
     * @type {string}
     * @memberof RankingSignal
     */
    name: string;
    /**
     * The configured weight, from the ranking configuration row for this environment.
     * @type {number}
     * @memberof RankingSignal
     */
    weight: number;
    /**
     * The signal's own value for this item, normalised to 0..1.
     * @type {number}
     * @memberof RankingSignal
     */
    value: number;
    /**
     * `weight * value` - what actually moved this item.
     * @type {number}
     * @memberof RankingSignal
     */
    contribution: number;
}

/**
 * Check if a given object implements the RankingSignal interface.
 */
export function instanceOfRankingSignal(value: object): value is RankingSignal {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('contribution' in value) || value['contribution'] === undefined) return false;
    return true;
}

export function RankingSignalFromJSON(json: any): RankingSignal {
    return RankingSignalFromJSONTyped(json, false);
}

export function RankingSignalFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankingSignal {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'weight': json['weight'],
        'value': json['value'],
        'contribution': json['contribution'],
    };
}

  export function RankingSignalToJSON(json: any): RankingSignal {
      return RankingSignalToJSONTyped(json, false);
  }

  export function RankingSignalToJSONTyped(value?: RankingSignal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'weight': value['weight'],
        'value': value['value'],
        'contribution': value['contribution'],
    };
}

