/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * How far into a bookmark the reader has got.
 * 
 * Separate from `Bookmark.readAt`, which stays the only record of *read*.
 * Progress is evidence; read state is a decision. The reader may suggest
 * marking read at 90%, and never sets it silently.
 * @export
 * @interface ReadingProgress
 */
export interface ReadingProgress {
    /**
     * 
     * @type {string}
     * @memberof ReadingProgress
     */
    bookmarkId: string;
    /**
     * 0-100. Monotonic server-side: a lower value is refused, not stored.
     * @type {number}
     * @memberof ReadingProgress
     */
    percent: number;
    /**
     * Pixels from the top of the reader. Advisory - a re-extraction changes the document's height and the client falls back to `percent`.
     * @type {number}
     * @memberof ReadingProgress
     */
    scrollOffset?: number;
    /**
     * 
     * @type {Date}
     * @memberof ReadingProgress
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ReadingProgress interface.
 */
export function instanceOfReadingProgress(value: object): value is ReadingProgress {
    if (!('bookmarkId' in value) || value['bookmarkId'] === undefined) return false;
    if (!('percent' in value) || value['percent'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ReadingProgressFromJSON(json: any): ReadingProgress {
    return ReadingProgressFromJSONTyped(json, false);
}

export function ReadingProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadingProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkId': json['bookmarkId'],
        'percent': json['percent'],
        'scrollOffset': json['scrollOffset'] == null ? undefined : json['scrollOffset'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

  export function ReadingProgressToJSON(json: any): ReadingProgress {
      return ReadingProgressToJSONTyped(json, false);
  }

  export function ReadingProgressToJSONTyped(value?: ReadingProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmarkId': value['bookmarkId'],
        'percent': value['percent'],
        'scrollOffset': value['scrollOffset'],
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

