/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefileBookmarkRequest
 */
export interface RefileBookmarkRequest {
    /**
     * The collection to move the bookmark into. `null` moves it to Inbox.
     * @type {string}
     * @memberof RefileBookmarkRequest
     */
    collectionId?: string | null;
}

/**
 * Check if a given object implements the RefileBookmarkRequest interface.
 */
export function instanceOfRefileBookmarkRequest(value: object): value is RefileBookmarkRequest {
    return true;
}

export function RefileBookmarkRequestFromJSON(json: any): RefileBookmarkRequest {
    return RefileBookmarkRequestFromJSONTyped(json, false);
}

export function RefileBookmarkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefileBookmarkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionId': json['collectionId'] == null ? undefined : json['collectionId'],
    };
}

  export function RefileBookmarkRequestToJSON(json: any): RefileBookmarkRequest {
      return RefileBookmarkRequestToJSONTyped(json, false);
  }

  export function RefileBookmarkRequestToJSONTyped(value?: RefileBookmarkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collectionId': value['collectionId'],
    };
}

