/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bookmark } from './Bookmark';
import {
    BookmarkFromJSON,
    BookmarkFromJSONTyped,
    BookmarkToJSON,
    BookmarkToJSONTyped,
} from './Bookmark';

/**
 * 
 * @export
 * @interface ReprocessBookmarkResponse
 */
export interface ReprocessBookmarkResponse {
    /**
     * 
     * @type {Bookmark}
     * @memberof ReprocessBookmarkResponse
     */
    bookmark: Bookmark;
    /**
     * 
     * @type {string}
     * @memberof ReprocessBookmarkResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ReprocessBookmarkResponse interface.
 */
export function instanceOfReprocessBookmarkResponse(value: object): value is ReprocessBookmarkResponse {
    if (!('bookmark' in value) || value['bookmark'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ReprocessBookmarkResponseFromJSON(json: any): ReprocessBookmarkResponse {
    return ReprocessBookmarkResponseFromJSONTyped(json, false);
}

export function ReprocessBookmarkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReprocessBookmarkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmark': BookmarkFromJSON(json['bookmark']),
        'message': json['message'],
    };
}

  export function ReprocessBookmarkResponseToJSON(json: any): ReprocessBookmarkResponse {
      return ReprocessBookmarkResponseToJSONTyped(json, false);
  }

  export function ReprocessBookmarkResponseToJSONTyped(value?: ReprocessBookmarkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmark': BookmarkToJSON(value['bookmark']),
        'message': value['message'],
    };
}

