/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookmarkProcessingPhase } from './BookmarkProcessingPhase';
import {
    BookmarkProcessingPhaseFromJSON,
    BookmarkProcessingPhaseFromJSONTyped,
    BookmarkProcessingPhaseToJSON,
    BookmarkProcessingPhaseToJSONTyped,
} from './BookmarkProcessingPhase';

/**
 * 
 * @export
 * @interface ReprocessBookmarkRequest
 */
export interface ReprocessBookmarkRequest {
    /**
     * Run only this phase. Absent reprocesses the whole pipeline.
     * @type {BookmarkProcessingPhase}
     * @memberof ReprocessBookmarkRequest
     */
    phase?: BookmarkProcessingPhase;
}



/**
 * Check if a given object implements the ReprocessBookmarkRequest interface.
 */
export function instanceOfReprocessBookmarkRequest(value: object): value is ReprocessBookmarkRequest {
    return true;
}

export function ReprocessBookmarkRequestFromJSON(json: any): ReprocessBookmarkRequest {
    return ReprocessBookmarkRequestFromJSONTyped(json, false);
}

export function ReprocessBookmarkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReprocessBookmarkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phase': json['phase'] == null ? undefined : BookmarkProcessingPhaseFromJSON(json['phase']),
    };
}

  export function ReprocessBookmarkRequestToJSON(json: any): ReprocessBookmarkRequest {
      return ReprocessBookmarkRequestToJSONTyped(json, false);
  }

  export function ReprocessBookmarkRequestToJSONTyped(value?: ReprocessBookmarkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phase': BookmarkProcessingPhaseToJSON(value['phase']),
    };
}

