/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceType } from './ResourceType';
import {
    ResourceTypeFromJSON,
    ResourceTypeFromJSONTyped,
    ResourceTypeToJSON,
    ResourceTypeToJSONTyped,
} from './ResourceType';
import type { OpenGraph } from './OpenGraph';
import {
    OpenGraphFromJSON,
    OpenGraphFromJSONTyped,
    OpenGraphToJSON,
    OpenGraphToJSONTyped,
} from './OpenGraph';

/**
 * 
 * @export
 * @interface Resource
 */
export interface Resource {
    /**
     * 
     * @type {ResourceType}
     * @memberof Resource
     */
    type: ResourceType;
    /**
     * 
     * @type {OpenGraph}
     * @memberof Resource
     */
    openGraph?: OpenGraph;
}



/**
 * Check if a given object implements the Resource interface.
 */
export function instanceOfResource(value: object): value is Resource {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ResourceFromJSON(json: any): Resource {
    return ResourceFromJSONTyped(json, false);
}

export function ResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resource {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ResourceTypeFromJSON(json['type']),
        'openGraph': json['openGraph'] == null ? undefined : OpenGraphFromJSON(json['openGraph']),
    };
}

  export function ResourceToJSON(json: any): Resource {
      return ResourceToJSONTyped(json, false);
  }

  export function ResourceToJSONTyped(value?: Resource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ResourceTypeToJSON(value['type']),
        'openGraph': OpenGraphToJSON(value['openGraph']),
    };
}

