/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveReadingProgressRequest
 */
export interface SaveReadingProgressRequest {
    /**
     * 0-100. Values a little outside the range are clamped rather than refused - the client derives this from a layout that is still settling.
     * @type {number}
     * @memberof SaveReadingProgressRequest
     */
    percent: number;
    /**
     * 
     * @type {number}
     * @memberof SaveReadingProgressRequest
     */
    scrollOffset?: number | null;
}

/**
 * Check if a given object implements the SaveReadingProgressRequest interface.
 */
export function instanceOfSaveReadingProgressRequest(value: object): value is SaveReadingProgressRequest {
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function SaveReadingProgressRequestFromJSON(json: any): SaveReadingProgressRequest {
    return SaveReadingProgressRequestFromJSONTyped(json, false);
}

export function SaveReadingProgressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveReadingProgressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'percent': json['percent'],
        'scrollOffset': json['scrollOffset'] == null ? undefined : json['scrollOffset'],
    };
}

  export function SaveReadingProgressRequestToJSON(json: any): SaveReadingProgressRequest {
      return SaveReadingProgressRequestToJSONTyped(json, false);
  }

  export function SaveReadingProgressRequestToJSONTyped(value?: SaveReadingProgressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'percent': value['percent'],
        'scrollOffset': value['scrollOffset'],
    };
}

