/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Read-state filter for search. Mirrors `BookmarkReadStatus`.
 * @export
 */
export const SearchReadStatus = {
    All: 'all',
    Unread: 'unread',
    Read: 'read'
} as const;
export type SearchReadStatus = typeof SearchReadStatus[keyof typeof SearchReadStatus];


export function instanceOfSearchReadStatus(value: any): boolean {
    for (const key in SearchReadStatus) {
        if (Object.prototype.hasOwnProperty.call(SearchReadStatus, key)) {
            if (SearchReadStatus[key as keyof typeof SearchReadStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SearchReadStatusFromJSON(json: any): SearchReadStatus {
    return SearchReadStatusFromJSONTyped(json, false);
}

export function SearchReadStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchReadStatus {
    return json as SearchReadStatus;
}

export function SearchReadStatusToJSON(value?: SearchReadStatus | null): any {
    return value as any;
}

export function SearchReadStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): SearchReadStatus {
    return value as SearchReadStatus;
}

