/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How a result earned its place in the list.
 * 
 * `keyword` — the query's words are literally in the save. `semantic` — the
 * save was reached only through vector similarity, so nothing the reader
 * typed appears in it. The distinction is carried to the client because a
 * row with no visible match has to explain itself: `/search` renders a
 * `Related` tag on the semantic ones (docs/design-system/pages.md § Search).
 * @export
 */
export const SearchMatchKind = {
    Keyword: 'keyword',
    Semantic: 'semantic'
} as const;
export type SearchMatchKind = typeof SearchMatchKind[keyof typeof SearchMatchKind];


export function instanceOfSearchMatchKind(value: any): boolean {
    for (const key in SearchMatchKind) {
        if (Object.prototype.hasOwnProperty.call(SearchMatchKind, key)) {
            if (SearchMatchKind[key as keyof typeof SearchMatchKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SearchMatchKindFromJSON(json: any): SearchMatchKind {
    return SearchMatchKindFromJSONTyped(json, false);
}

export function SearchMatchKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMatchKind {
    return json as SearchMatchKind;
}

export function SearchMatchKindToJSON(value?: SearchMatchKind | null): any {
    return value as any;
}

export function SearchMatchKindToJSONTyped(value: any, ignoreDiscriminator: boolean): SearchMatchKind {
    return value as SearchMatchKind;
}

