/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One bookmark an answer was built from.
 * 
 * Rule 8: no AI output ships without naming its sources, and a source that is
 * not a link is not provenance — `bookmarkId` is what makes each one
 * clickable. An answer with an empty `sources` array is not an answer and the
 * server does not stream one.
 * @export
 * @interface SearchAnswerSource
 */
export interface SearchAnswerSource {
    /**
     * 
     * @type {string}
     * @memberof SearchAnswerSource
     */
    bookmarkId: string;
    /**
     * 
     * @type {string}
     * @memberof SearchAnswerSource
     */
    title: string;
    /**
     * Bare host — `every.to`, not `https://every.to/`.
     * @type {string}
     * @memberof SearchAnswerSource
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof SearchAnswerSource
     */
    faviconUrl?: string;
}

/**
 * Check if a given object implements the SearchAnswerSource interface.
 */
export function instanceOfSearchAnswerSource(value: object): value is SearchAnswerSource {
    if (!('bookmarkId' in value) || value['bookmarkId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function SearchAnswerSourceFromJSON(json: any): SearchAnswerSource {
    return SearchAnswerSourceFromJSONTyped(json, false);
}

export function SearchAnswerSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAnswerSource {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkId': json['bookmarkId'],
        'title': json['title'],
        'domain': json['domain'],
        'faviconUrl': json['faviconUrl'] == null ? undefined : json['faviconUrl'],
    };
}

  export function SearchAnswerSourceToJSON(json: any): SearchAnswerSource {
      return SearchAnswerSourceToJSONTyped(json, false);
  }

  export function SearchAnswerSourceToJSONTyped(value?: SearchAnswerSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmarkId': value['bookmarkId'],
        'title': value['title'],
        'domain': value['domain'],
        'faviconUrl': value['faviconUrl'],
    };
}

