/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchAnswerSource } from './SearchAnswerSource';
import {
    SearchAnswerSourceFromJSON,
    SearchAnswerSourceFromJSONTyped,
    SearchAnswerSourceToJSON,
    SearchAnswerSourceToJSONTyped,
} from './SearchAnswerSource';

/**
 * One frame of the `/search/ask` stream.
 * 
 * The stream is SSE and the `event:` name carries the discriminator:
 * 
 *   `sources` — always first, and always before any `chunk`. Empty means the
 *               query matched nothing, and no `chunk` follows it.
 *   `chunk`   — a fragment of the answer, in order.
 *   `done`    — the stream is complete.
 *   `error`   — the run failed; nothing more follows.
 * 
 * Modelled rather than left as an opaque `string` so `SearchAnswerSource`
 * reaches the generated client, which is where the "an answer names its
 * sources" rule has to be typed for a client to be able to honour it.
 * @export
 * @interface SearchAskEvent
 */
export interface SearchAskEvent {
    /**
     * `sources` | `chunk` | `done` | `error`
     * @type {string}
     * @memberof SearchAskEvent
     */
    event: string;
    /**
     * Present on `sources`. Empty means nothing was found and no answer follows.
     * @type {Array<SearchAnswerSource>}
     * @memberof SearchAskEvent
     */
    sources?: Array<SearchAnswerSource>;
    /**
     * Present on `chunk`.
     * @type {string}
     * @memberof SearchAskEvent
     */
    text?: string;
    /**
     * Present on `error`.
     * @type {string}
     * @memberof SearchAskEvent
     */
    error?: string;
}

/**
 * Check if a given object implements the SearchAskEvent interface.
 */
export function instanceOfSearchAskEvent(value: object): value is SearchAskEvent {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function SearchAskEventFromJSON(json: any): SearchAskEvent {
    return SearchAskEventFromJSONTyped(json, false);
}

export function SearchAskEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAskEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'],
        'sources': json['sources'] == null ? undefined : ((json['sources'] as Array<any>).map(SearchAnswerSourceFromJSON)),
        'text': json['text'] == null ? undefined : json['text'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

  export function SearchAskEventToJSON(json: any): SearchAskEvent {
      return SearchAskEventToJSONTyped(json, false);
  }

  export function SearchAskEventToJSONTyped(value?: SearchAskEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': value['event'],
        'sources': value['sources'] == null ? undefined : ((value['sources'] as Array<any>).map(SearchAnswerSourceToJSON)),
        'text': value['text'],
        'error': value['error'],
    };
}

