/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How far back a search looks, by the save's own `createdAt`.
 * 
 * A coarse range rather than a pair of dates: the question a reader actually
 * asks of their own library is "recently" or "ever", and two date pickers
 * buy precision nobody uses at the price of a form.
 * @export
 */
export const SearchDateRange = {
    Any: 'any',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type SearchDateRange = typeof SearchDateRange[keyof typeof SearchDateRange];


export function instanceOfSearchDateRange(value: any): boolean {
    for (const key in SearchDateRange) {
        if (Object.prototype.hasOwnProperty.call(SearchDateRange, key)) {
            if (SearchDateRange[key as keyof typeof SearchDateRange] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SearchDateRangeFromJSON(json: any): SearchDateRange {
    return SearchDateRangeFromJSONTyped(json, false);
}

export function SearchDateRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDateRange {
    return json as SearchDateRange;
}

export function SearchDateRangeToJSON(value?: SearchDateRange | null): any {
    return value as any;
}

export function SearchDateRangeToJSONTyped(value: any, ignoreDiscriminator: boolean): SearchDateRange {
    return value as SearchDateRange;
}

