/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bookmark } from './Bookmark';
import {
    BookmarkFromJSON,
    BookmarkFromJSONTyped,
    BookmarkToJSON,
    BookmarkToJSONTyped,
} from './Bookmark';

/**
 * 
 * @export
 * @interface SearchBookmarksResponse
 */
export interface SearchBookmarksResponse {
    /**
     * 
     * @type {Array<Bookmark>}
     * @memberof SearchBookmarksResponse
     */
    bookmarks: Array<Bookmark>;
    /**
     * 
     * @type {number}
     * @memberof SearchBookmarksResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the SearchBookmarksResponse interface.
 */
export function instanceOfSearchBookmarksResponse(value: object): value is SearchBookmarksResponse {
    if (!('bookmarks' in value) || value['bookmarks'] === undefined) return false;
    return true;
}

export function SearchBookmarksResponseFromJSON(json: any): SearchBookmarksResponse {
    return SearchBookmarksResponseFromJSONTyped(json, false);
}

export function SearchBookmarksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchBookmarksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarks': ((json['bookmarks'] as Array<any>).map(BookmarkFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

  export function SearchBookmarksResponseToJSON(json: any): SearchBookmarksResponse {
      return SearchBookmarksResponseToJSONTyped(json, false);
  }

  export function SearchBookmarksResponseToJSONTyped(value?: SearchBookmarksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmarks': ((value['bookmarks'] as Array<any>).map(BookmarkToJSON)),
        'total': value['total'],
    };
}

