/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareDigestResponse
 */
export interface ShareDigestResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ShareDigestResponse
     */
    isPublic: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShareDigestResponse
     */
    shareUrl: string;
}

/**
 * Check if a given object implements the ShareDigestResponse interface.
 */
export function instanceOfShareDigestResponse(value: object): value is ShareDigestResponse {
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    if (!('shareUrl' in value) || value['shareUrl'] === undefined) return false;
    return true;
}

export function ShareDigestResponseFromJSON(json: any): ShareDigestResponse {
    return ShareDigestResponseFromJSONTyped(json, false);
}

export function ShareDigestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareDigestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isPublic': json['isPublic'],
        'shareUrl': json['shareUrl'],
    };
}

  export function ShareDigestResponseToJSON(json: any): ShareDigestResponse {
      return ShareDigestResponseToJSONTyped(json, false);
  }

  export function ShareDigestResponseToJSONTyped(value?: ShareDigestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPublic': value['isPublic'],
        'shareUrl': value['shareUrl'],
    };
}

