/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareBookmarkResponse
 */
export interface ShareBookmarkResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ShareBookmarkResponse
     */
    isPublic: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShareBookmarkResponse
     */
    shareUrl: string;
}

/**
 * Check if a given object implements the ShareBookmarkResponse interface.
 */
export function instanceOfShareBookmarkResponse(value: object): value is ShareBookmarkResponse {
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    if (!('shareUrl' in value) || value['shareUrl'] === undefined) return false;
    return true;
}

export function ShareBookmarkResponseFromJSON(json: any): ShareBookmarkResponse {
    return ShareBookmarkResponseFromJSONTyped(json, false);
}

export function ShareBookmarkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareBookmarkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isPublic': json['isPublic'],
        'shareUrl': json['shareUrl'],
    };
}

  export function ShareBookmarkResponseToJSON(json: any): ShareBookmarkResponse {
      return ShareBookmarkResponseToJSONTyped(json, false);
  }

  export function ShareBookmarkResponseToJSONTyped(value?: ShareBookmarkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPublic': value['isPublic'],
        'shareUrl': value['shareUrl'],
    };
}

