/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialError
 */
export interface SocialError {
    /**
     * 
     * @type {string}
     * @memberof SocialError
     */
    error: string;
}

/**
 * Check if a given object implements the SocialError interface.
 */
export function instanceOfSocialError(value: object): value is SocialError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function SocialErrorFromJSON(json: any): SocialError {
    return SocialErrorFromJSONTyped(json, false);
}

export function SocialErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

  export function SocialErrorToJSON(json: any): SocialError {
      return SocialErrorToJSONTyped(json, false);
  }

  export function SocialErrorToJSONTyped(value?: SocialError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

