/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedActor } from './FeedActor';
import {
    FeedActorFromJSON,
    FeedActorFromJSONTyped,
    FeedActorToJSON,
    FeedActorToJSONTyped,
} from './FeedActor';

/**
 * Someone worth following, with their public output for the window.
 * 
 * `isFollowedByViewer` is computed for this list because it is short and
 * bounded (the rail renders five) — unlike `/users/{handle}/followers`, where
 * a relationship per row would be a query per row.
 * @export
 * @interface TrendingPerson
 */
export interface TrendingPerson {
    /**
     * 
     * @type {FeedActor}
     * @memberof TrendingPerson
     */
    person: FeedActor;
    /**
     * Public saves inside the discovery window.
     * @type {number}
     * @memberof TrendingPerson
     */
    savesThisWeek: number;
    /**
     * Follower count — the only global number Explore reports about a person.
     * @type {number}
     * @memberof TrendingPerson
     */
    followers: number;
    /**
     * 
     * @type {boolean}
     * @memberof TrendingPerson
     */
    isFollowedByViewer: boolean;
}

/**
 * Check if a given object implements the TrendingPerson interface.
 */
export function instanceOfTrendingPerson(value: object): value is TrendingPerson {
    if (!('person' in value) || value['person'] === undefined) return false;
    if (!('savesThisWeek' in value) || value['savesThisWeek'] === undefined) return false;
    if (!('followers' in value) || value['followers'] === undefined) return false;
    if (!('isFollowedByViewer' in value) || value['isFollowedByViewer'] === undefined) return false;
    return true;
}

export function TrendingPersonFromJSON(json: any): TrendingPerson {
    return TrendingPersonFromJSONTyped(json, false);
}

export function TrendingPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendingPerson {
    if (json == null) {
        return json;
    }
    return {
        
        'person': FeedActorFromJSON(json['person']),
        'savesThisWeek': json['savesThisWeek'],
        'followers': json['followers'],
        'isFollowedByViewer': json['isFollowedByViewer'],
    };
}

  export function TrendingPersonToJSON(json: any): TrendingPerson {
      return TrendingPersonToJSONTyped(json, false);
  }

  export function TrendingPersonToJSONTyped(value?: TrendingPerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'person': FeedActorToJSON(value['person']),
        'savesThisWeek': value['savesThisWeek'],
        'followers': value['followers'],
        'isFollowedByViewer': value['isFollowedByViewer'],
    };
}

