/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rename, recolour, or reparent. Every field is optional; an absent field is
 * left alone. `parentId: null` moves the collection back to the root.
 * @export
 * @interface UpdateCollectionRequest
 */
export interface UpdateCollectionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    parentId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCollectionRequest
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the UpdateCollectionRequest interface.
 */
export function instanceOfUpdateCollectionRequest(value: object): value is UpdateCollectionRequest {
    return true;
}

export function UpdateCollectionRequestFromJSON(json: any): UpdateCollectionRequest {
    return UpdateCollectionRequestFromJSONTyped(json, false);
}

export function UpdateCollectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCollectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'color': json['color'] == null ? undefined : json['color'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

  export function UpdateCollectionRequestToJSON(json: any): UpdateCollectionRequest {
      return UpdateCollectionRequestToJSONTyped(json, false);
  }

  export function UpdateCollectionRequestToJSONTyped(value?: UpdateCollectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'color': value['color'],
        'icon': value['icon'],
        'parentId': value['parentId'],
        'isPublic': value['isPublic'],
    };
}

