/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Name, picture and handle. Every field is optional; an absent field is left
 * alone and an explicit `null` on name or picture clears it.
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    pictureUrl?: string | null;
    /**
     * Lowercase letters, numbers and underscores, 3-30 characters. Changeable once every 30 days.
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    handle?: string;
}

/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): value is UpdateProfileRequest {
    return true;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'pictureUrl': json['pictureUrl'] == null ? undefined : json['pictureUrl'],
        'handle': json['handle'] == null ? undefined : json['handle'],
    };
}

  export function UpdateProfileRequestToJSON(json: any): UpdateProfileRequest {
      return UpdateProfileRequestToJSONTyped(json, false);
  }

  export function UpdateProfileRequestToJSONTyped(value?: UpdateProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'pictureUrl': value['pictureUrl'],
        'handle': value['handle'],
    };
}

