/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Only the note is editable. The anchor is what the reader selected and is not rewritten after the fact.
 * @export
 * @interface UpdateHighlightRequest
 */
export interface UpdateHighlightRequest {
    /**
     * `null` clears the note.
     * @type {string}
     * @memberof UpdateHighlightRequest
     */
    note?: string | null;
}

/**
 * Check if a given object implements the UpdateHighlightRequest interface.
 */
export function instanceOfUpdateHighlightRequest(value: object): value is UpdateHighlightRequest {
    return true;
}

export function UpdateHighlightRequestFromJSON(json: any): UpdateHighlightRequest {
    return UpdateHighlightRequestFromJSONTyped(json, false);
}

export function UpdateHighlightRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateHighlightRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
    };
}

  export function UpdateHighlightRequestToJSON(json: any): UpdateHighlightRequest {
      return UpdateHighlightRequestToJSONTyped(json, false);
  }

  export function UpdateHighlightRequestToJSONTyped(value?: UpdateHighlightRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
    };
}

