export const BOOKMARK_SERVICE = Symbol("BOOKMARK_SERVICE");
export const BOOKMARK_PROCESSOR_SERVICE = Symbol("BOOKMARK_PROCESSOR_SERVICE");
export const WEB_SCRAPING_SERVICE = Symbol("WEB_SCRAPING_SERVICE");
