version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - JWT_SECRET=dev-secret-key
    volumes:
      - ./packages/api:/app/packages/api
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/packages/api/node_modules
    command: npm run dev --workspace=packages/api

  worker:
    build:
      context: .
      dockerfile: packages/worker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./packages/worker:/app/packages/worker
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/packages/worker/node_modules
    command: npm run start:dev --workspace=packages/worker