version: '3.8'

services:
  postgres-test:
    image: pgvector/pgvector:pg15
    container_name: cosmic-dolphin-test-db
    environment:
      POSTGRES_DB: cosmic_dolphin_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - ./supabase/migrations:/supabase/migrations:ro
      - ./packages/shared/scripts/init-test-db.sh:/docker-entrypoint-initdb.d/01-init-migrations.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d cosmic_dolphin_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - test-network

networks:
  test-network:
    driver: bridge