CREATE TABLE resources (
    id bigint primary key generated always as identity,
    type VARCHAR(50) NOT NULL,
    source TEXT NOT NULL,
    created_at timestamp with time zone default now(),
    user_id VARCHAR(255) NOT NULL
);

CREATE TABLE documents (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    resource_id BIGINT NOT NULL,
    title TEXT[] NOT NULL,
    content TEXT NOT NULL,
    images JSONB,
    embeddings vector (3072),
    user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);