alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: api.cosmic-dolphin.com
  type: PRIMARY
  zone: cosmic-dolphin.com
envs:
- key: OPENAI_API_KEY
  scope: RUN_AND_BUILD_TIME
  value: ${OPENAI_API_KEY}
- key: PG_CONN
  scope: RUN_AND_BUILD_TIME
  value: ${PG_CONN}
- key: ENV
  scope: RUN_AND_BUILD_TIME
  value: production
- key: JWT_SECRET
  scope: RUN_AND_BUILD_TIME
  value: ${JWT_SECRET}
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: cosmic-dolphin
    match:
      path:
        prefix: /
name: cosmic-dolphin-api
region: nyc
services:
- environment_slug: go
  github:
    branch: main
    deploy_on_push: false
    repo: pffreitas/cosmic-dolphin
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: cosmic-dolphin
  run_command: bin/cosmic-dolphin
  source_dir: /
