alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

domains:
- domain: api-nodejs.cosmic-dolphin.com
  type: PRIMARY
  zone: cosmic-dolphin.com

envs:
- key: NODE_ENV
  scope: RUN_AND_BUILD_TIME
  value: production
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: ${DATABASE_URL}
- key: REDIS_URL
  scope: RUN_AND_BUILD_TIME
  value: ${REDIS_URL}
- key: JWT_SECRET
  scope: RUN_AND_BUILD_TIME
  value: ${JWT_SECRET}
- key: SUPABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: ${SUPABASE_URL}
- key: SUPABASE_SERVICE_ROLE_KEY
  scope: RUN_AND_BUILD_TIME
  value: ${SUPABASE_SERVICE_ROLE_KEY}

ingress:
  rules:
  - component:
      name: cosmic-dolphin-api-nodejs
    match:
      path:
        prefix: /

name: cosmic-dolphin-api-nodejs
region: nyc

services:
- name: cosmic-dolphin-api-nodejs
  image:
    registry_type: DOCR
    repository: cosmic-dolphin-api
    tag: ${IMAGE_TAG}
  http_port: 3000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb