/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Bookmark,
  BookmarkError,
  BookmarkLibraryCounts,
  BookmarkProcessingTimelineResponse,
  BookmarkReadStatus,
  BookmarkScope,
  BookmarkSort,
  CreateBookmarkRequest,
  CreateBookmarkResponse,
  DeleteBookmarkResponse,
  FeedResponse,
  FeedScope,
  GetBookmarksResponse,
  LikeResponse,
  PreviewRequest,
  PreviewResponse,
  RefileBookmarkRequest,
  ReprocessBookmarkRequest,
  ReprocessBookmarkResponse,
  SearchBookmarksResponse,
  ShareBookmarkResponse,
  UpdateBookmarkRequest,
} from '../models/index';
import {
    BookmarkFromJSON,
    BookmarkToJSON,
    BookmarkErrorFromJSON,
    BookmarkErrorToJSON,
    BookmarkLibraryCountsFromJSON,
    BookmarkLibraryCountsToJSON,
    BookmarkProcessingTimelineResponseFromJSON,
    BookmarkProcessingTimelineResponseToJSON,
    BookmarkReadStatusFromJSON,
    BookmarkReadStatusToJSON,
    BookmarkScopeFromJSON,
    BookmarkScopeToJSON,
    BookmarkSortFromJSON,
    BookmarkSortToJSON,
    CreateBookmarkRequestFromJSON,
    CreateBookmarkRequestToJSON,
    CreateBookmarkResponseFromJSON,
    CreateBookmarkResponseToJSON,
    DeleteBookmarkResponseFromJSON,
    DeleteBookmarkResponseToJSON,
    FeedResponseFromJSON,
    FeedResponseToJSON,
    FeedScopeFromJSON,
    FeedScopeToJSON,
    GetBookmarksResponseFromJSON,
    GetBookmarksResponseToJSON,
    LikeResponseFromJSON,
    LikeResponseToJSON,
    PreviewRequestFromJSON,
    PreviewRequestToJSON,
    PreviewResponseFromJSON,
    PreviewResponseToJSON,
    RefileBookmarkRequestFromJSON,
    RefileBookmarkRequestToJSON,
    ReprocessBookmarkRequestFromJSON,
    ReprocessBookmarkRequestToJSON,
    ReprocessBookmarkResponseFromJSON,
    ReprocessBookmarkResponseToJSON,
    SearchBookmarksResponseFromJSON,
    SearchBookmarksResponseToJSON,
    ShareBookmarkResponseFromJSON,
    ShareBookmarkResponseToJSON,
    UpdateBookmarkRequestFromJSON,
    UpdateBookmarkRequestToJSON,
} from '../models/index';

export interface BookmarksCreateRequest {
    createBookmarkRequest: CreateBookmarkRequest;
}

export interface BookmarksFeedRequest {
    scope?: FeedScope;
    cursor?: string;
    limit?: number;
}

export interface BookmarksFindByIdRequest {
    id: string;
}

export interface BookmarksGetProcessingTimelineRequest {
    id: string;
}

export interface BookmarksLikeRequest {
    id: string;
}

export interface BookmarksListRequest {
    collectionId?: string;
    limit?: number;
    offset?: number;
    readStatus?: BookmarkReadStatus;
    scope?: BookmarkScope;
    sort?: BookmarkSort;
    cursor?: string;
}

export interface BookmarksMarkReadRequest {
    id: string;
}

export interface BookmarksMarkUnreadRequest {
    id: string;
}

export interface BookmarksPreviewRequest {
    previewRequest: PreviewRequest;
}

export interface BookmarksRefileRequest {
    id: string;
    refileBookmarkRequest: RefileBookmarkRequest;
}

export interface BookmarksRemoveRequest {
    id: string;
}

export interface BookmarksReprocessRequest {
    id: string;
    reprocessBookmarkRequest: ReprocessBookmarkRequest;
}

export interface BookmarksReshareRequest {
    id: string;
}

export interface BookmarksSearchRequest {
    query: string;
    limit?: number;
    offset?: number;
}

export interface BookmarksShareRequest {
    id: string;
}

export interface BookmarksUnlikeRequest {
    id: string;
}

export interface BookmarksUnshareRequest {
    id: string;
}

export interface BookmarksUpdateRequest {
    id: string;
    updateBookmarkRequest: UpdateBookmarkRequest;
}

/**
 * 
 */
export class BookmarksApi extends runtime.BaseAPI {

    /**
     * The counts beside every row of the Library rail, in one query.
     */
    async bookmarksCountsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookmarkLibraryCounts>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/counts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkLibraryCountsFromJSON(jsonValue));
    }

    /**
     * The counts beside every row of the Library rail, in one query.
     */
    async bookmarksCounts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookmarkLibraryCounts> {
        const response = await this.bookmarksCountsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new bookmark.  The URL is normalised before anything else (lowercased scheme and host, trailing slash stripped, `utm_*`/`fbclid`/`gclid`/`ref`/`mc_cid` dropped); the normalised form is stored in `sourceUrl` and the paste is preserved in `metadata.originalUrl`.  If the caller already has that normalised URL, this returns 200 with `alreadySaved: true` and the existing bookmark — a duplicate paste is not an error and never a 409.  The handler writes the row and enqueues; fetching, extraction, summarising, tagging and filing all happen in the worker. Nothing is awaited that touches the network or a model.
     */
    async bookmarksCreateRaw(requestParameters: BookmarksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateBookmarkResponse>> {
        if (requestParameters['createBookmarkRequest'] == null) {
            throw new runtime.RequiredError(
                'createBookmarkRequest',
                'Required parameter "createBookmarkRequest" was null or undefined when calling bookmarksCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBookmarkRequestToJSON(requestParameters['createBookmarkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBookmarkResponseFromJSON(jsonValue));
    }

    /**
     * Create a new bookmark.  The URL is normalised before anything else (lowercased scheme and host, trailing slash stripped, `utm_*`/`fbclid`/`gclid`/`ref`/`mc_cid` dropped); the normalised form is stored in `sourceUrl` and the paste is preserved in `metadata.originalUrl`.  If the caller already has that normalised URL, this returns 200 with `alreadySaved: true` and the existing bookmark — a duplicate paste is not an error and never a 409.  The handler writes the row and enqueues; fetching, extraction, summarising, tagging and filing all happen in the worker. Nothing is awaited that touches the network or a model.
     */
    async bookmarksCreate(requestParameters: BookmarksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateBookmarkResponse> {
        const response = await this.bookmarksCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The ranked Home feed — docs/functional-spec/05-feed.md.  Not a bookmark list. Each row is a `FeedItem` that says what it is, who it came through, and — in one sentence the server wrote — why it is here.  **Cursor-based, never offset.** The candidate set is re-ranked between requests; an offset into a list that has been reordered duplicates some items and skips others. Hand `nextCursor` back verbatim.  The ranking\'s head is cached per user for five minutes, which is what `computedAt` reports. Bookmarks saved after that point bypass the cache and are prepended, so a save the user just made is on the first page whatever the cache says.
     */
    async bookmarksFeedRaw(requestParameters: BookmarksFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedResponse>> {
        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/feed`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedResponseFromJSON(jsonValue));
    }

    /**
     * The ranked Home feed — docs/functional-spec/05-feed.md.  Not a bookmark list. Each row is a `FeedItem` that says what it is, who it came through, and — in one sentence the server wrote — why it is here.  **Cursor-based, never offset.** The candidate set is re-ranked between requests; an offset into a list that has been reordered duplicates some items and skips others. Hand `nextCursor` back verbatim.  The ranking\'s head is cached per user for five minutes, which is what `computedAt` reports. Bookmarks saved after that point bypass the cache and are prepended, so a save the user just made is on the first page whatever the cache says.
     */
    async bookmarksFeed(requestParameters: BookmarksFeedRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedResponse> {
        const response = await this.bookmarksFeedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a bookmark by ID
     */
    async bookmarksFindByIdRaw(requestParameters: BookmarksFindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bookmark>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksFindById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkFromJSON(jsonValue));
    }

    /**
     * Get a bookmark by ID
     */
    async bookmarksFindById(requestParameters: BookmarksFindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bookmark> {
        const response = await this.bookmarksFindByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the durable processing timeline for a bookmark
     */
    async bookmarksGetProcessingTimelineRaw(requestParameters: BookmarksGetProcessingTimelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookmarkProcessingTimelineResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksGetProcessingTimeline().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/processing-timeline`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkProcessingTimelineResponseFromJSON(jsonValue));
    }

    /**
     * Get the durable processing timeline for a bookmark
     */
    async bookmarksGetProcessingTimeline(requestParameters: BookmarksGetProcessingTimelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookmarkProcessingTimelineResponse> {
        const response = await this.bookmarksGetProcessingTimelineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Like a bookmark
     */
    async bookmarksLikeRaw(requestParameters: BookmarksLikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LikeResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksLike().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/like`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LikeResponseFromJSON(jsonValue));
    }

    /**
     * Like a bookmark
     */
    async bookmarksLike(requestParameters: BookmarksLikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LikeResponse> {
        const response = await this.bookmarksLikeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the caller\'s bookmarks.  Ordered by `sort`, which defaults to `newest` - chronological, the order the Library falls back to and the one every other ordering is an overlay on.  Paging is keyset: read `nextCursor` off the response and hand it back as `cursor`. `offset` remains for callers that have not moved over, but it is not safe on a list being written to while it is paged.
     */
    async bookmarksListRaw(requestParameters: BookmarksListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBookmarksResponse>> {
        const queryParameters: any = {};

        if (requestParameters['collectionId'] != null) {
            queryParameters['collection_id'] = requestParameters['collectionId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['readStatus'] != null) {
            queryParameters['read_status'] = requestParameters['readStatus'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBookmarksResponseFromJSON(jsonValue));
    }

    /**
     * Get the caller\'s bookmarks.  Ordered by `sort`, which defaults to `newest` - chronological, the order the Library falls back to and the one every other ordering is an overlay on.  Paging is keyset: read `nextCursor` off the response and hand it back as `cursor`. `offset` remains for callers that have not moved over, but it is not safe on a list being written to while it is paged.
     */
    async bookmarksList(requestParameters: BookmarksListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBookmarksResponse> {
        const response = await this.bookmarksListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Mark a bookmark as read
     */
    async bookmarksMarkReadRaw(requestParameters: BookmarksMarkReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bookmark>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksMarkRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/read`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkFromJSON(jsonValue));
    }

    /**
     * Mark a bookmark as read
     */
    async bookmarksMarkRead(requestParameters: BookmarksMarkReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bookmark> {
        const response = await this.bookmarksMarkReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Mark a bookmark as unread
     */
    async bookmarksMarkUnreadRaw(requestParameters: BookmarksMarkUnreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bookmark>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksMarkUnread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/read`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkFromJSON(jsonValue));
    }

    /**
     * Mark a bookmark as unread
     */
    async bookmarksMarkUnread(requestParameters: BookmarksMarkUnreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bookmark> {
        const response = await this.bookmarksMarkUnreadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Preview a URL and get metadata without saving
     */
    async bookmarksPreviewRaw(requestParameters: BookmarksPreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PreviewResponse>> {
        if (requestParameters['previewRequest'] == null) {
            throw new runtime.RequiredError(
                'previewRequest',
                'Required parameter "previewRequest" was null or undefined when calling bookmarksPreview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/preview`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PreviewRequestToJSON(requestParameters['previewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PreviewResponseFromJSON(jsonValue));
    }

    /**
     * Preview a URL and get metadata without saving
     */
    async bookmarksPreview(requestParameters: BookmarksPreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PreviewResponse> {
        const response = await this.bookmarksPreviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Move a bookmark into a collection, or to Inbox with `collectionId: null`.  This is the override endpoint. It sets `filing_source = \'user\'` in the same statement as the move, so the pipeline\'s `file` phase will never touch this bookmark again. A refile the pipeline can undo on its next run is worse than no refile at all.
     */
    async bookmarksRefileRaw(requestParameters: BookmarksRefileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bookmark>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksRefile().'
            );
        }

        if (requestParameters['refileBookmarkRequest'] == null) {
            throw new runtime.RequiredError(
                'refileBookmarkRequest',
                'Required parameter "refileBookmarkRequest" was null or undefined when calling bookmarksRefile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/collection`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RefileBookmarkRequestToJSON(requestParameters['refileBookmarkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkFromJSON(jsonValue));
    }

    /**
     * Move a bookmark into a collection, or to Inbox with `collectionId: null`.  This is the override endpoint. It sets `filing_source = \'user\'` in the same statement as the move, so the pipeline\'s `file` phase will never touch this bookmark again. A refile the pipeline can undo on its next run is worse than no refile at all.
     */
    async bookmarksRefile(requestParameters: BookmarksRefileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bookmark> {
        const response = await this.bookmarksRefileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a bookmark and all associated data
     */
    async bookmarksRemoveRaw(requestParameters: BookmarksRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteBookmarkResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteBookmarkResponseFromJSON(jsonValue));
    }

    /**
     * Delete a bookmark and all associated data
     */
    async bookmarksRemove(requestParameters: BookmarksRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteBookmarkResponse> {
        const response = await this.bookmarksRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a fresh processing run for a bookmark, optionally scoped to one phase. Appends to the existing timeline rather than replacing it, so the run the user already watched stays on screen. Also the **Summarise now** action on a bookmark left `idle` by the daily processing budget: an explicit request is never refused for budget.
     */
    async bookmarksReprocessRaw(requestParameters: BookmarksReprocessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReprocessBookmarkResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksReprocess().'
            );
        }

        if (requestParameters['reprocessBookmarkRequest'] == null) {
            throw new runtime.RequiredError(
                'reprocessBookmarkRequest',
                'Required parameter "reprocessBookmarkRequest" was null or undefined when calling bookmarksReprocess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/reprocess`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReprocessBookmarkRequestToJSON(requestParameters['reprocessBookmarkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReprocessBookmarkResponseFromJSON(jsonValue));
    }

    /**
     * Start a fresh processing run for a bookmark, optionally scoped to one phase. Appends to the existing timeline rather than replacing it, so the run the user already watched stays on screen. Also the **Summarise now** action on a bookmark left `idle` by the daily processing budget: an explicit request is never refused for budget.
     */
    async bookmarksReprocess(requestParameters: BookmarksReprocessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReprocessBookmarkResponse> {
        const response = await this.bookmarksReprocessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reshare a bookmark into the caller\'s own library — the feed\'s **Save** action, docs/functional-spec/06-social.md § Reshare.  The new bookmark is the caller\'s: it inherits only the source URL and carries `savedFromBookmarkId` pointing at the original. Nothing else travels. The pipeline runs again for the new owner, so the summary, tags and filing are theirs and not the original saver\'s, and the comment thread stays on the original — a reshare starts at zero.  Because it inherits the URL it meets the same per-user uniqueness constraint `POST /bookmarks` does: resharing something already in the library returns 200 with `alreadySaved: true` and the row the caller already has. Nothing is created and nothing is re-queued.  404 covers \"no such bookmark\", \"not public\", and \"blocked in either direction\" alike — the same refusal the social routes make, for the same reason.
     */
    async bookmarksReshareRaw(requestParameters: BookmarksReshareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateBookmarkResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksReshare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/reshare`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBookmarkResponseFromJSON(jsonValue));
    }

    /**
     * Reshare a bookmark into the caller\'s own library — the feed\'s **Save** action, docs/functional-spec/06-social.md § Reshare.  The new bookmark is the caller\'s: it inherits only the source URL and carries `savedFromBookmarkId` pointing at the original. Nothing else travels. The pipeline runs again for the new owner, so the summary, tags and filing are theirs and not the original saver\'s, and the comment thread stays on the original — a reshare starts at zero.  Because it inherits the URL it meets the same per-user uniqueness constraint `POST /bookmarks` does: resharing something already in the library returns 200 with `alreadySaved: true` and the row the caller already has. Nothing is created and nothing is re-queued.  404 covers \"no such bookmark\", \"not public\", and \"blocked in either direction\" alike — the same refusal the social routes make, for the same reason.
     */
    async bookmarksReshare(requestParameters: BookmarksReshareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateBookmarkResponse> {
        const response = await this.bookmarksReshareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search bookmarks
     */
    async bookmarksSearchRaw(requestParameters: BookmarksSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchBookmarksResponse>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling bookmarksSearch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchBookmarksResponseFromJSON(jsonValue));
    }

    /**
     * Search bookmarks
     */
    async bookmarksSearch(requestParameters: BookmarksSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchBookmarksResponse> {
        const response = await this.bookmarksSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Share a bookmark (make it public)
     */
    async bookmarksShareRaw(requestParameters: BookmarksShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShareBookmarkResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/share`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShareBookmarkResponseFromJSON(jsonValue));
    }

    /**
     * Share a bookmark (make it public)
     */
    async bookmarksShare(requestParameters: BookmarksShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShareBookmarkResponse> {
        const response = await this.bookmarksShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlike a bookmark
     */
    async bookmarksUnlikeRaw(requestParameters: BookmarksUnlikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LikeResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksUnlike().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/like`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LikeResponseFromJSON(jsonValue));
    }

    /**
     * Unlike a bookmark
     */
    async bookmarksUnlike(requestParameters: BookmarksUnlikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LikeResponse> {
        const response = await this.bookmarksUnlikeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unshare a bookmark (make it private)
     */
    async bookmarksUnshareRaw(requestParameters: BookmarksUnshareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShareBookmarkResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksUnshare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/share`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShareBookmarkResponseFromJSON(jsonValue));
    }

    /**
     * Unshare a bookmark (make it private)
     */
    async bookmarksUnshare(requestParameters: BookmarksUnshareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShareBookmarkResponse> {
        const response = await this.bookmarksUnshareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a bookmark\'s title, tags, or archived flag.  This is what the Library\'s bulk bar writes through for **Archive** and **Add tag**. It takes the whole tag list rather than a delta so the 8-second undo can put back exactly what was there.
     */
    async bookmarksUpdateRaw(requestParameters: BookmarksUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bookmark>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarksUpdate().'
            );
        }

        if (requestParameters['updateBookmarkRequest'] == null) {
            throw new runtime.RequiredError(
                'updateBookmarkRequest',
                'Required parameter "updateBookmarkRequest" was null or undefined when calling bookmarksUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateBookmarkRequestToJSON(requestParameters['updateBookmarkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkFromJSON(jsonValue));
    }

    /**
     * Update a bookmark\'s title, tags, or archived flag.  This is what the Library\'s bulk bar writes through for **Archive** and **Add tag**. It takes the whole tag list rather than a delta so the 8-second undo can put back exactly what was there.
     */
    async bookmarksUpdate(requestParameters: BookmarksUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bookmark> {
        const response = await this.bookmarksUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
