/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcceptCollectionSuggestionResponse,
  BookmarkError,
  Collection,
  CollectionSuggestionResponse,
  CreateCollectionRequest,
  DeleteCollectionResponse,
  GetCollectionSuggestionsResponse,
  GetCollectionsResponse,
  UpdateCollectionRequest,
} from '../models/index';
import {
    AcceptCollectionSuggestionResponseFromJSON,
    AcceptCollectionSuggestionResponseToJSON,
    BookmarkErrorFromJSON,
    BookmarkErrorToJSON,
    CollectionFromJSON,
    CollectionToJSON,
    CollectionSuggestionResponseFromJSON,
    CollectionSuggestionResponseToJSON,
    CreateCollectionRequestFromJSON,
    CreateCollectionRequestToJSON,
    DeleteCollectionResponseFromJSON,
    DeleteCollectionResponseToJSON,
    GetCollectionSuggestionsResponseFromJSON,
    GetCollectionSuggestionsResponseToJSON,
    GetCollectionsResponseFromJSON,
    GetCollectionsResponseToJSON,
    UpdateCollectionRequestFromJSON,
    UpdateCollectionRequestToJSON,
} from '../models/index';

export interface CollectionsAcceptSuggestionRequest {
    id: string;
}

export interface CollectionsCreateRequest {
    createCollectionRequest: CreateCollectionRequest;
}

export interface CollectionsDismissSuggestionRequest {
    id: string;
}

export interface CollectionsRemoveRequest {
    id: string;
}

export interface CollectionsUpdateRequest {
    id: string;
    updateCollectionRequest: UpdateCollectionRequest;
}

/**
 * 
 */
export class CollectionsApi extends runtime.BaseAPI {

    /**
     * Accept a proposal: create the collection and file its supporting bookmarks into it. The only path by which a proposal becomes a collection.
     */
    async collectionsAcceptSuggestionRaw(requestParameters: CollectionsAcceptSuggestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptCollectionSuggestionResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionsAcceptSuggestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections/suggestions/{id}/accept`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AcceptCollectionSuggestionResponseFromJSON(jsonValue));
    }

    /**
     * Accept a proposal: create the collection and file its supporting bookmarks into it. The only path by which a proposal becomes a collection.
     */
    async collectionsAcceptSuggestion(requestParameters: CollectionsAcceptSuggestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptCollectionSuggestionResponse> {
        const response = await this.collectionsAcceptSuggestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a collection.  The tree is capped at two levels: `parentId` must name a root collection the caller owns. A deeper parent is rejected with 422.
     */
    async collectionsCreateRaw(requestParameters: CollectionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Collection>> {
        if (requestParameters['createCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'createCollectionRequest',
                'Required parameter "createCollectionRequest" was null or undefined when calling collectionsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCollectionRequestToJSON(requestParameters['createCollectionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionFromJSON(jsonValue));
    }

    /**
     * Create a collection.  The tree is capped at two levels: `parentId` must name a root collection the caller owns. A deeper parent is rejected with 422.
     */
    async collectionsCreate(requestParameters: CollectionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Collection> {
        const response = await this.collectionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Decline a proposal. Remembered for 30 days, not forever.
     */
    async collectionsDismissSuggestionRaw(requestParameters: CollectionsDismissSuggestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionSuggestionResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionsDismissSuggestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections/suggestions/{id}/dismiss`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionSuggestionResponseFromJSON(jsonValue));
    }

    /**
     * Decline a proposal. Remembered for 30 days, not forever.
     */
    async collectionsDismissSuggestion(requestParameters: CollectionsDismissSuggestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionSuggestionResponse> {
        const response = await this.collectionsDismissSuggestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s collections
     */
    async collectionsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCollectionsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCollectionsResponseFromJSON(jsonValue));
    }

    /**
     * Get user\'s collections
     */
    async collectionsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCollectionsResponse> {
        const response = await this.collectionsListRaw(initOverrides);
        return await response.value();
    }

    /**
     * The AI collection proposals worth answering: pending, and supported by enough bookmarks to be worth the interruption.
     */
    async collectionsListSuggestionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCollectionSuggestionsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections/suggestions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCollectionSuggestionsResponseFromJSON(jsonValue));
    }

    /**
     * The AI collection proposals worth answering: pending, and supported by enough bookmarks to be worth the interruption.
     */
    async collectionsListSuggestions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCollectionSuggestionsResponse> {
        const response = await this.collectionsListSuggestionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete a collection. Its bookmarks move to Inbox - they are never deleted. Child collections are removed with it, and their bookmarks move to Inbox too.
     */
    async collectionsRemoveRaw(requestParameters: CollectionsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteCollectionResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionsRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteCollectionResponseFromJSON(jsonValue));
    }

    /**
     * Delete a collection. Its bookmarks move to Inbox - they are never deleted. Child collections are removed with it, and their bookmarks move to Inbox too.
     */
    async collectionsRemove(requestParameters: CollectionsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteCollectionResponse> {
        const response = await this.collectionsRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rename, recolour, or reparent a collection.  Reparenting is checked against the same two-level cap as creation, from both ends: the new parent must be a root collection, and a collection that has children of its own cannot be moved under anything.
     */
    async collectionsUpdateRaw(requestParameters: CollectionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Collection>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling collectionsUpdate().'
            );
        }

        if (requestParameters['updateCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCollectionRequest',
                'Required parameter "updateCollectionRequest" was null or undefined when calling collectionsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/collections/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCollectionRequestToJSON(requestParameters['updateCollectionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionFromJSON(jsonValue));
    }

    /**
     * Rename, recolour, or reparent a collection.  Reparenting is checked against the same two-level cap as creation, from both ends: the new parent must be a root collection, and a collection that has children of its own cannot be moved under anything.
     */
    async collectionsUpdate(requestParameters: CollectionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Collection> {
        const response = await this.collectionsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
