/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Comment,
  CommentError,
  CommentsResponse,
  CreateCommentRequest,
  CreateReportRequest,
  CreateReportResponse,
  DeleteCommentResponse,
  UpdateCommentRequest,
} from '../models/index';
import {
    CommentFromJSON,
    CommentToJSON,
    CommentErrorFromJSON,
    CommentErrorToJSON,
    CommentsResponseFromJSON,
    CommentsResponseToJSON,
    CreateCommentRequestFromJSON,
    CreateCommentRequestToJSON,
    CreateReportRequestFromJSON,
    CreateReportRequestToJSON,
    CreateReportResponseFromJSON,
    CreateReportResponseToJSON,
    DeleteCommentResponseFromJSON,
    DeleteCommentResponseToJSON,
    UpdateCommentRequestFromJSON,
    UpdateCommentRequestToJSON,
} from '../models/index';

export interface BookmarkCommentsCreateRequest {
    id: string;
    createCommentRequest: CreateCommentRequest;
}

export interface BookmarkCommentsListRequest {
    id: string;
}

export interface CommentsRemoveRequest {
    id: string;
}

export interface CommentsUpdateRequest {
    id: string;
    updateCommentRequest: UpdateCommentRequest;
}

export interface ReportsCreateRequest {
    createReportRequest: CreateReportRequest;
}

/**
 * 
 */
export class CommentsApi extends runtime.BaseAPI {

    /**
     * Post a comment or a reply. Rate limited to 10 per minute.  A `parentId` that points at a reply is not an error: the new comment attaches to that reply\'s parent, and the response says where it actually landed.
     */
    async bookmarkCommentsCreateRaw(requestParameters: BookmarkCommentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Comment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarkCommentsCreate().'
            );
        }

        if (requestParameters['createCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'createCommentRequest',
                'Required parameter "createCommentRequest" was null or undefined when calling bookmarkCommentsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/comments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommentRequestToJSON(requestParameters['createCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentFromJSON(jsonValue));
    }

    /**
     * Post a comment or a reply. Rate limited to 10 per minute.  A `parentId` that points at a reply is not an error: the new comment attaches to that reply\'s parent, and the response says where it actually landed.
     */
    async bookmarkCommentsCreate(requestParameters: BookmarkCommentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Comment> {
        const response = await this.bookmarkCommentsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The thread on a bookmark, chronological.  Visible when the bookmark is public or the caller owns it — a comment on a private bookmark is a private note to self. Un-sharing therefore *hides* a thread rather than deleting it: this route starts answering 404 to everyone but the owner, and re-sharing brings the same comments back.
     */
    async bookmarkCommentsListRaw(requestParameters: BookmarkCommentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmarkCommentsList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/comments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentsResponseFromJSON(jsonValue));
    }

    /**
     * The thread on a bookmark, chronological.  Visible when the bookmark is public or the caller owns it — a comment on a private bookmark is a private note to self. Un-sharing therefore *hides* a thread rather than deleting it: this route starts answering 404 to everyone but the owner, and re-sharing brings the same comments back.
     */
    async bookmarkCommentsList(requestParameters: BookmarkCommentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentsResponse> {
        const response = await this.bookmarkCommentsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a comment.  Soft-deletes when it has replies — the row stays as a tombstone so those replies keep a parent — and hard-deletes when it does not. Unlike editing, deleting never expires: a person can always withdraw what they said.
     */
    async commentsRemoveRaw(requestParameters: CommentsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteCommentResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling commentsRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/comments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteCommentResponseFromJSON(jsonValue));
    }

    /**
     * Delete a comment.  Soft-deletes when it has replies — the row stays as a tombstone so those replies keep a parent — and hard-deletes when it does not. Unlike editing, deleting never expires: a person can always withdraw what they said.
     */
    async commentsRemove(requestParameters: CommentsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteCommentResponse> {
        const response = await this.commentsRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit a comment, for 15 minutes after it was written and not a second longer.  The window is a product decision, not a technical one: a comment people have already replied to should not be able to become a different comment underneath them. 403 once it closes, because the caller is the author — it is the comment that is frozen, not the caller who is unauthorised.
     */
    async commentsUpdateRaw(requestParameters: CommentsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Comment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling commentsUpdate().'
            );
        }

        if (requestParameters['updateCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCommentRequest',
                'Required parameter "updateCommentRequest" was null or undefined when calling commentsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/comments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCommentRequestToJSON(requestParameters['updateCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentFromJSON(jsonValue));
    }

    /**
     * Edit a comment, for 15 minutes after it was written and not a second longer.  The window is a product decision, not a technical one: a comment people have already replied to should not be able to become a different comment underneath them. 403 once it closes, because the caller is the author — it is the comment that is frozen, not the caller who is unauthorised.
     */
    async commentsUpdate(requestParameters: CommentsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Comment> {
        const response = await this.commentsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Report a public bookmark or a comment.  Idempotent per reporter per target: reporting the same thing twice is one report and returns 200 either way. A second press is not a second signal, and treating it as one would let a single account flood the review queue.
     */
    async reportsCreateRaw(requestParameters: ReportsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateReportResponse>> {
        if (requestParameters['createReportRequest'] == null) {
            throw new runtime.RequiredError(
                'createReportRequest',
                'Required parameter "createReportRequest" was null or undefined when calling reportsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/reports`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateReportRequestToJSON(requestParameters['createReportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateReportResponseFromJSON(jsonValue));
    }

    /**
     * Report a public bookmark or a comment.  Idempotent per reporter per target: reporting the same thing twice is one report and returns 200 either way. A second press is not a second signal, and treating it as one would let a single account flood the review queue.
     */
    async reportsCreate(requestParameters: ReportsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateReportResponse> {
        const response = await this.reportsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
