/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Digest,
  DigestError,
  LikeResponse,
  ShareDigestResponse,
} from '../models/index';
import {
    DigestFromJSON,
    DigestToJSON,
    DigestErrorFromJSON,
    DigestErrorToJSON,
    LikeResponseFromJSON,
    LikeResponseToJSON,
    ShareDigestResponseFromJSON,
    ShareDigestResponseToJSON,
} from '../models/index';

export interface DigestsGetRequest {
    id: string;
}

export interface DigestsLikeRequest {
    id: string;
}

export interface DigestsShareRequest {
    id: string;
}

export interface DigestsUnlikeRequest {
    id: string;
}

export interface DigestsUnshareRequest {
    id: string;
}

/**
 * 
 */
export class DigestsApi extends runtime.BaseAPI {

    /**
     * Get one digest.  Owner-unless-public, matching the table\'s RLS: the owner always sees their own digest, and everyone else sees it only once it has been shared. Anything else is a 404 rather than a 403 — a private digest does not confirm its own existence.
     */
    async digestsGetRaw(requestParameters: DigestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Digest>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling digestsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/digests/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DigestFromJSON(jsonValue));
    }

    /**
     * Get one digest.  Owner-unless-public, matching the table\'s RLS: the owner always sees their own digest, and everyone else sees it only once it has been shared. Anything else is a 404 rather than a 403 — a private digest does not confirm its own existence.
     */
    async digestsGet(requestParameters: DigestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Digest> {
        const response = await this.digestsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Like a digest
     */
    async digestsLikeRaw(requestParameters: DigestsLikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LikeResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling digestsLike().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/digests/{id}/like`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LikeResponseFromJSON(jsonValue));
    }

    /**
     * Like a digest
     */
    async digestsLike(requestParameters: DigestsLikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LikeResponse> {
        const response = await this.digestsLikeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Share a digest — the feed\'s **Save digest** action.  Resharing a digest saves **the digest**, not its sources. This route publishes the digest itself and never changes the visibility of a single source bookmark: the sources are the user\'s private library, and a provenance row is not a licence to publish what it names.
     */
    async digestsShareRaw(requestParameters: DigestsShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShareDigestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling digestsShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/digests/{id}/share`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShareDigestResponseFromJSON(jsonValue));
    }

    /**
     * Share a digest — the feed\'s **Save digest** action.  Resharing a digest saves **the digest**, not its sources. This route publishes the digest itself and never changes the visibility of a single source bookmark: the sources are the user\'s private library, and a provenance row is not a licence to publish what it names.
     */
    async digestsShare(requestParameters: DigestsShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShareDigestResponse> {
        const response = await this.digestsShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlike a digest
     */
    async digestsUnlikeRaw(requestParameters: DigestsUnlikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LikeResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling digestsUnlike().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/digests/{id}/like`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LikeResponseFromJSON(jsonValue));
    }

    /**
     * Unlike a digest
     */
    async digestsUnlike(requestParameters: DigestsUnlikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LikeResponse> {
        const response = await this.digestsUnlikeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unshare a digest (make it private again)
     */
    async digestsUnshareRaw(requestParameters: DigestsUnshareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShareDigestResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling digestsUnshare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/digests/{id}/share`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShareDigestResponseFromJSON(jsonValue));
    }

    /**
     * Unshare a digest (make it private again)
     */
    async digestsUnshare(requestParameters: DigestsUnshareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShareDigestResponse> {
        const response = await this.digestsUnshareRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
