/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExploreError,
  ExploreRailResponse,
  ExploreResponse,
} from '../models/index';
import {
    ExploreErrorFromJSON,
    ExploreErrorToJSON,
    ExploreRailResponseFromJSON,
    ExploreRailResponseToJSON,
    ExploreResponseFromJSON,
    ExploreResponseToJSON,
} from '../models/index';

export interface ExploreListRequest {
    topic?: string;
    limit?: number;
    cursor?: string;
}

export interface ExploreRailRequest {
    collectionLimit?: number;
    peopleLimit?: number;
}

/**
 * 
 */
export class ExploreApi extends runtime.BaseAPI {

    /**
     * Public saves ranked for discovery, plus the topic control\'s options.  Excludes the caller\'s own saves - Explore is where you find what you do not already have - and everything either side of a block.
     */
    async exploreListRaw(requestParameters: ExploreListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExploreResponse>> {
        const queryParameters: any = {};

        if (requestParameters['topic'] != null) {
            queryParameters['topic'] = requestParameters['topic'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/explore`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExploreResponseFromJSON(jsonValue));
    }

    /**
     * Public saves ranked for discovery, plus the topic control\'s options.  Excludes the caller\'s own saves - Explore is where you find what you do not already have - and everything either side of a block.
     */
    async exploreList(requestParameters: ExploreListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExploreResponse> {
        const response = await this.exploreListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trending collections and people to follow. One request, because it is one column.
     */
    async exploreRailRaw(requestParameters: ExploreRailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExploreRailResponse>> {
        const queryParameters: any = {};

        if (requestParameters['collectionLimit'] != null) {
            queryParameters['collectionLimit'] = requestParameters['collectionLimit'];
        }

        if (requestParameters['peopleLimit'] != null) {
            queryParameters['peopleLimit'] = requestParameters['peopleLimit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/explore/rail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExploreRailResponseFromJSON(jsonValue));
    }

    /**
     * Trending collections and people to follow. One request, because it is one column.
     */
    async exploreRail(requestParameters: ExploreRailRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExploreRailResponse> {
        const response = await this.exploreRailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
