/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeedError,
  FeedFeedbackRequest,
  FeedFeedbackResponse,
  FeedRailResponse,
} from '../models/index';
import {
    FeedErrorFromJSON,
    FeedErrorToJSON,
    FeedFeedbackRequestFromJSON,
    FeedFeedbackRequestToJSON,
    FeedFeedbackResponseFromJSON,
    FeedFeedbackResponseToJSON,
    FeedRailResponseFromJSON,
    FeedRailResponseToJSON,
} from '../models/index';

export interface FeedFeedbackOperationRequest {
    feedFeedbackRequest: FeedFeedbackRequest;
}

export interface FeedRailRequest {
    topicLimit?: number;
    peopleLimit?: number;
}

/**
 * 
 */
export class FeedApi extends runtime.BaseAPI {

    /**
     * Tell the ranker it got one wrong — docs/functional-spec/05-feed.md § Feedback.  Reached from each feed item\'s overflow menu. Takes effect on the next request, visibly: a dismissed item that comes back is a bug, not a ranking nuance.
     */
    async feedFeedbackRaw(requestParameters: FeedFeedbackOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedFeedbackResponse>> {
        if (requestParameters['feedFeedbackRequest'] == null) {
            throw new runtime.RequiredError(
                'feedFeedbackRequest',
                'Required parameter "feedFeedbackRequest" was null or undefined when calling feedFeedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/feed/feedback`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FeedFeedbackRequestToJSON(requestParameters['feedFeedbackRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedFeedbackResponseFromJSON(jsonValue));
    }

    /**
     * Tell the ranker it got one wrong — docs/functional-spec/05-feed.md § Feedback.  Reached from each feed item\'s overflow menu. Takes effect on the next request, visibly: a dismissed item that comes back is a bug, not a ranking nuance.
     */
    async feedFeedback(requestParameters: FeedFeedbackOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedFeedbackResponse> {
        const response = await this.feedFeedbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Home\'s rail: the topics the reader has been saving this week, and the people they follow with their public output for the week.  One request rather than three, because the rail is one column and a column that arrives in three pieces reflows twice.
     */
    async feedRailRaw(requestParameters: FeedRailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedRailResponse>> {
        const queryParameters: any = {};

        if (requestParameters['topicLimit'] != null) {
            queryParameters['topicLimit'] = requestParameters['topicLimit'];
        }

        if (requestParameters['peopleLimit'] != null) {
            queryParameters['peopleLimit'] = requestParameters['peopleLimit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/feed/rail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedRailResponseFromJSON(jsonValue));
    }

    /**
     * Home\'s rail: the topics the reader has been saving this week, and the people they follow with their public output for the week.  One request rather than three, because the rail is one column and a column that arrives in three pieces reflows twice.
     */
    async feedRail(requestParameters: FeedRailRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedRailResponse> {
        const response = await this.feedRailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
