/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CosmicError,
  Pipeline,
} from '../models/index';
import {
    CosmicErrorFromJSON,
    CosmicErrorToJSON,
    PipelineFromJSON,
    PipelineToJSON,
} from '../models/index';

export interface PipelinesFindByRefIdRequest {
    refId: number;
}

/**
 * 
 */
export class PipelinesApi extends runtime.BaseAPI {

    /**
     */
    async pipelinesFindByRefIdRaw(requestParameters: PipelinesFindByRefIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Pipeline>>> {
        if (requestParameters['refId'] == null) {
            throw new runtime.RequiredError(
                'refId',
                'Required parameter "refId" was null or undefined when calling pipelinesFindByRefId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/pipelines/{refId}`.replace(`{${"refId"}}`, encodeURIComponent(String(requestParameters['refId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PipelineFromJSON));
    }

    /**
     */
    async pipelinesFindByRefId(requestParameters: PipelinesFindByRefIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Pipeline>> {
        const response = await this.pipelinesFindByRefIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
