/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookmarkError,
  ContinueReadingResponse,
  CreateHighlightRequest,
  DeleteHighlightResponse,
  GetHighlightsResponse,
  GetReadingProgressResponse,
  Highlight,
  SaveReadingProgressRequest,
  SaveReadingProgressResponse,
  UpdateHighlightRequest,
} from '../models/index';
import {
    BookmarkErrorFromJSON,
    BookmarkErrorToJSON,
    ContinueReadingResponseFromJSON,
    ContinueReadingResponseToJSON,
    CreateHighlightRequestFromJSON,
    CreateHighlightRequestToJSON,
    DeleteHighlightResponseFromJSON,
    DeleteHighlightResponseToJSON,
    GetHighlightsResponseFromJSON,
    GetHighlightsResponseToJSON,
    GetReadingProgressResponseFromJSON,
    GetReadingProgressResponseToJSON,
    HighlightFromJSON,
    HighlightToJSON,
    SaveReadingProgressRequestFromJSON,
    SaveReadingProgressRequestToJSON,
    SaveReadingProgressResponseFromJSON,
    SaveReadingProgressResponseToJSON,
    UpdateHighlightRequestFromJSON,
    UpdateHighlightRequestToJSON,
} from '../models/index';

export interface HighlightsRemoveRequest {
    id: string;
}

export interface HighlightsUpdateRequest {
    id: string;
    updateHighlightRequest: UpdateHighlightRequest;
}

export interface ReadingContinueReadingRequest {
    limit?: number;
}

export interface ReadingCreateHighlightRequest {
    id: string;
    createHighlightRequest: CreateHighlightRequest;
}

export interface ReadingGetProgressRequest {
    id: string;
}

export interface ReadingListHighlightsRequest {
    id: string;
}

export interface ReadingSaveProgressRequest {
    id: string;
    saveReadingProgressRequest: SaveReadingProgressRequest;
}

/**
 * 
 */
export class ReadingApi extends runtime.BaseAPI {

    /**
     * Remove a highlight.
     */
    async highlightsRemoveRaw(requestParameters: HighlightsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteHighlightResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling highlightsRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/highlights/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteHighlightResponseFromJSON(jsonValue));
    }

    /**
     * Remove a highlight.
     */
    async highlightsRemove(requestParameters: HighlightsRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteHighlightResponse> {
        const response = await this.highlightsRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit a highlight\'s note. The anchor itself is never rewritten.
     */
    async highlightsUpdateRaw(requestParameters: HighlightsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Highlight>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling highlightsUpdate().'
            );
        }

        if (requestParameters['updateHighlightRequest'] == null) {
            throw new runtime.RequiredError(
                'updateHighlightRequest',
                'Required parameter "updateHighlightRequest" was null or undefined when calling highlightsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/highlights/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateHighlightRequestToJSON(requestParameters['updateHighlightRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HighlightFromJSON(jsonValue));
    }

    /**
     * Edit a highlight\'s note. The anchor itself is never rewritten.
     */
    async highlightsUpdate(requestParameters: HighlightsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Highlight> {
        const response = await this.highlightsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The caller\'s in-flight reads, newest activity first, for Home\'s Continue reading rail.  In flight means 5-95%: below that a bookmark was opened rather than started, above it the product offers to mark it read. A bookmark the user has explicitly marked read or archived leaves the rail whatever its scroll position says - the rail is for things they mean to come back to.
     */
    async readingContinueReadingRaw(requestParameters: ReadingContinueReadingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContinueReadingResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/continue-reading`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContinueReadingResponseFromJSON(jsonValue));
    }

    /**
     * The caller\'s in-flight reads, newest activity first, for Home\'s Continue reading rail.  In flight means 5-95%: below that a bookmark was opened rather than started, above it the product offers to mark it read. A bookmark the user has explicitly marked read or archived leaves the rail whatever its scroll position says - the rail is for things they mean to come back to.
     */
    async readingContinueReading(requestParameters: ReadingContinueReadingRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContinueReadingResponse> {
        const response = await this.readingContinueReadingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Keep a span of a bookmark\'s extracted content. Only on the caller\'s own save - a highlight is a note about oneself and needs somewhere private to live.
     */
    async readingCreateHighlightRaw(requestParameters: ReadingCreateHighlightRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Highlight>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readingCreateHighlight().'
            );
        }

        if (requestParameters['createHighlightRequest'] == null) {
            throw new runtime.RequiredError(
                'createHighlightRequest',
                'Required parameter "createHighlightRequest" was null or undefined when calling readingCreateHighlight().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/highlights`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateHighlightRequestToJSON(requestParameters['createHighlightRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HighlightFromJSON(jsonValue));
    }

    /**
     * Keep a span of a bookmark\'s extracted content. Only on the caller\'s own save - a highlight is a note about oneself and needs somewhere private to live.
     */
    async readingCreateHighlight(requestParameters: ReadingCreateHighlightRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Highlight> {
        const response = await this.readingCreateHighlightRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Where the caller left off in one bookmark.  The counterpart to `saveProgress`, and the reason progress survives a reload: the reader asks for it once on mount and restores the scroll position before it starts recording a new one. `continueReading` cannot answer this - it is windowed to 5-95% and to a page of items, so a reader 2% or 97% into an article would be told they had never opened it.
     */
    async readingGetProgressRaw(requestParameters: ReadingGetProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetReadingProgressResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readingGetProgress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/progress`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetReadingProgressResponseFromJSON(jsonValue));
    }

    /**
     * Where the caller left off in one bookmark.  The counterpart to `saveProgress`, and the reason progress survives a reload: the reader asks for it once on mount and restores the scroll position before it starts recording a new one. `continueReading` cannot answer this - it is windowed to 5-95% and to a page of items, so a reader 2% or 97% into an article would be told they had never opened it.
     */
    async readingGetProgress(requestParameters: ReadingGetProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetReadingProgressResponse> {
        const response = await this.readingGetProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The caller\'s own highlights on a bookmark. Never anyone else\'s, on a public bookmark or otherwise.
     */
    async readingListHighlightsRaw(requestParameters: ReadingListHighlightsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHighlightsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readingListHighlights().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/highlights`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHighlightsResponseFromJSON(jsonValue));
    }

    /**
     * The caller\'s own highlights on a bookmark. Never anyone else\'s, on a public bookmark or otherwise.
     */
    async readingListHighlights(requestParameters: ReadingListHighlightsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHighlightsResponse> {
        const response = await this.readingListHighlightsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Record how far into a bookmark the reader has got.  High frequency, and built for it: the client throttles to one write per bookmark per 5 seconds plus one on unmount, and the handler is a single guarded upsert.  Percent is **monotonic server-side**. A value below the stored one is refused in SQL - `WHERE excluded.percent >= stored.percent` - so a stale request that overtakes a fresh one, or a second tab scrolled back to the top, cannot walk progress backwards. The response is 200 either way, carrying what is actually stored and `accepted: false` when the submitted value lost.
     */
    async readingSaveProgressRaw(requestParameters: ReadingSaveProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveReadingProgressResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readingSaveProgress().'
            );
        }

        if (requestParameters['saveReadingProgressRequest'] == null) {
            throw new runtime.RequiredError(
                'saveReadingProgressRequest',
                'Required parameter "saveReadingProgressRequest" was null or undefined when calling readingSaveProgress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/bookmarks/{id}/progress`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SaveReadingProgressRequestToJSON(requestParameters['saveReadingProgressRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveReadingProgressResponseFromJSON(jsonValue));
    }

    /**
     * Record how far into a bookmark the reader has got.  High frequency, and built for it: the client throttles to one write per bookmark per 5 seconds plus one on unmount, and the handler is a single guarded upsert.  Percent is **monotonic server-side**. A value below the stored one is refused in SQL - `WHERE excluded.percent >= stored.percent` - so a stale request that overtakes a fresh one, or a second tab scrolled back to the top, cannot walk progress backwards. The response is 200 either way, carrying what is actually stored and `accepted: false` when the submitted value lost.
     */
    async readingSaveProgress(requestParameters: ReadingSaveProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveReadingProgressResponse> {
        const response = await this.readingSaveProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
