/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HybridSearchResponse,
  SearchAskEvent,
  SearchAskRequest,
  SearchDateRange,
  SearchError,
  SearchReadStatus,
} from '../models/index';
import {
    HybridSearchResponseFromJSON,
    HybridSearchResponseToJSON,
    SearchAskEventFromJSON,
    SearchAskEventToJSON,
    SearchAskRequestFromJSON,
    SearchAskRequestToJSON,
    SearchDateRangeFromJSON,
    SearchDateRangeToJSON,
    SearchErrorFromJSON,
    SearchErrorToJSON,
    SearchReadStatusFromJSON,
    SearchReadStatusToJSON,
} from '../models/index';

export interface SearchAskOperationRequest {
    searchAskRequest: SearchAskRequest;
}

export interface SearchHybridSearchRequest {
    q: string;
    limit?: number;
    collectionId?: string;
    tag?: string;
    readStatus?: SearchReadStatus;
    dateRange?: SearchDateRange;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Search with an AI-generated RAG answer, streamed as SSE.  The `sources` event is always emitted first. When it is empty the run stops there: an answer that cites nothing is not an answer, and the server refuses to produce one rather than leaving the client to decide whether to show it.
     */
    async searchAskRaw(requestParameters: SearchAskOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchAskEvent>> {
        if (requestParameters['searchAskRequest'] == null) {
            throw new runtime.RequiredError(
                'searchAskRequest',
                'Required parameter "searchAskRequest" was null or undefined when calling searchAsk().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/search/ask`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchAskRequestToJSON(requestParameters['searchAskRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchAskEventFromJSON(jsonValue));
    }

    /**
     * Search with an AI-generated RAG answer, streamed as SSE.  The `sources` event is always emitted first. When it is empty the run stops there: an answer that cites nothing is not an answer, and the server refuses to produce one rather than leaving the client to decide whether to show it.
     */
    async searchAsk(requestParameters: SearchAskOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchAskEvent> {
        const response = await this.searchAskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Hybrid search combining full-text and vector similarity
     */
    async searchHybridSearchRaw(requestParameters: SearchHybridSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HybridSearchResponse>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchHybridSearch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['collectionId'] != null) {
            queryParameters['collectionId'] = requestParameters['collectionId'];
        }

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['readStatus'] != null) {
            queryParameters['readStatus'] = requestParameters['readStatus'];
        }

        if (requestParameters['dateRange'] != null) {
            queryParameters['dateRange'] = requestParameters['dateRange'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HybridSearchResponseFromJSON(jsonValue));
    }

    /**
     * Hybrid search combining full-text and vector similarity
     */
    async searchHybridSearch(requestParameters: SearchHybridSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HybridSearchResponse> {
        const response = await this.searchHybridSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
