/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Bookmark,
  BookmarkError,
} from '../models/index';
import {
    BookmarkFromJSON,
    BookmarkToJSON,
    BookmarkErrorFromJSON,
    BookmarkErrorToJSON,
} from '../models/index';

export interface SharedBookmarksFindBySlugRequest {
    slug: string;
}

/**
 * 
 */
export class SharedBookmarksApi extends runtime.BaseAPI {

    /**
     * Get a publicly shared bookmark by its share slug
     */
    async sharedBookmarksFindBySlugRaw(requestParameters: SharedBookmarksFindBySlugRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bookmark>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling sharedBookmarksFindBySlug().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/bookmarks/shared/{slug}`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkFromJSON(jsonValue));
    }

    /**
     * Get a publicly shared bookmark by its share slug
     */
    async sharedBookmarksFindBySlug(requestParameters: SharedBookmarksFindBySlugRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bookmark> {
        const response = await this.sharedBookmarksFindBySlugRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
