/* tslint:disable */
/* eslint-disable */
/**
 * Cosmic Dolphin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BlockResponse,
  FollowResponse,
  Profile,
  PublicCollectionListResponse,
  PublicProfile,
  PublicProfileListResponse,
  PublicSavesResponse,
  SocialError,
  UpdateProfileRequest,
} from '../models/index';
import {
    BlockResponseFromJSON,
    BlockResponseToJSON,
    FollowResponseFromJSON,
    FollowResponseToJSON,
    ProfileFromJSON,
    ProfileToJSON,
    PublicCollectionListResponseFromJSON,
    PublicCollectionListResponseToJSON,
    PublicProfileFromJSON,
    PublicProfileToJSON,
    PublicProfileListResponseFromJSON,
    PublicProfileListResponseToJSON,
    PublicSavesResponseFromJSON,
    PublicSavesResponseToJSON,
    SocialErrorFromJSON,
    SocialErrorToJSON,
    UpdateProfileRequestFromJSON,
    UpdateProfileRequestToJSON,
} from '../models/index';

export interface ProfilesUpdateRequest {
    updateProfileRequest: UpdateProfileRequest;
}

export interface UsersBlockRequest {
    handle: string;
}

export interface UsersFollowRequest {
    handle: string;
}

export interface UsersGetCollectionsRequest {
    handle: string;
    limit?: number;
    cursor?: string;
}

export interface UsersGetFollowersRequest {
    handle: string;
    limit?: number;
    cursor?: string;
}

export interface UsersGetFollowingRequest {
    handle: string;
    limit?: number;
    cursor?: string;
}

export interface UsersGetLikesRequest {
    handle: string;
    limit?: number;
    cursor?: string;
}

export interface UsersGetProfileRequest {
    handle: string;
}

export interface UsersGetSavesRequest {
    handle: string;
    limit?: number;
    cursor?: string;
}

export interface UsersUnblockRequest {
    handle: string;
}

export interface UsersUnfollowRequest {
    handle: string;
}

/**
 * 
 */
export class SocialApi extends runtime.BaseAPI {

    /**
     * The caller\'s own profile, including the handle and whether it has been claimed.
     */
    async profilesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/profile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * The caller\'s own profile, including the handle and whether it has been claimed.
     */
    async profilesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.profilesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update name, picture, or handle.  The handle rules live here and nowhere else: format `^[a-z0-9_]{3,30}$`, unique, and changeable once every 30 days. A request that sets `handle` to the value it already has *claims* the reserved handle without spending the 30-day allowance - confirming something is not changing it.
     */
    async profilesUpdateRaw(requestParameters: ProfilesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        if (requestParameters['updateProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProfileRequest',
                'Required parameter "updateProfileRequest" was null or undefined when calling profilesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/profile`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProfileRequestToJSON(requestParameters['updateProfileRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Update name, picture, or handle.  The handle rules live here and nowhere else: format `^[a-z0-9_]{3,30}$`, unique, and changeable once every 30 days. A request that sets `handle` to the value it already has *claims* the reserved handle without spending the 30-day allowance - confirming something is not changing it.
     */
    async profilesUpdate(requestParameters: ProfilesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.profilesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Block. Drops both follow edges in the same transaction and hides the blocker\'s public saves from the blocked user.  Being blocked by someone does not stop you blocking them back, so this route - unlike `follow` - does not 404 on an existing block.
     */
    async usersBlockRaw(requestParameters: UsersBlockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersBlock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/block`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockResponseFromJSON(jsonValue));
    }

    /**
     * Block. Drops both follow edges in the same transaction and hides the blocker\'s public saves from the blocked user.  Being blocked by someone does not stop you blocking them back, so this route - unlike `follow` - does not 404 on an existing block.
     */
    async usersBlock(requestParameters: UsersBlockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockResponse> {
        const response = await this.usersBlockRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Follow. Immediate, public, and reciprocity-free - there is no request and no acceptance, so the response is the final state.  Idempotent: following twice is one edge and one follower. Rate limited to 100 per hour.
     */
    async usersFollowRaw(requestParameters: UsersFollowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FollowResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersFollow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/follow`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FollowResponseFromJSON(jsonValue));
    }

    /**
     * Follow. Immediate, public, and reciprocity-free - there is no request and no acceptance, so the response is the final state.  Idempotent: following twice is one edge and one follower. Rate limited to 100 per hour.
     */
    async usersFollow(requestParameters: UsersFollowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FollowResponse> {
        const response = await this.usersFollowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A profile\'s **public** collections, newest first - the Collections tab on `/u/{handle}`.  A collection is listed when `is_public` is set, whatever is filed inside it. `saveCount` then counts only the public saves in it, so a public collection full of private links reports zero rather than leaking its size.
     */
    async usersGetCollectionsRaw(requestParameters: UsersGetCollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicCollectionListResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersGetCollections().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/collections`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicCollectionListResponseFromJSON(jsonValue));
    }

    /**
     * A profile\'s **public** collections, newest first - the Collections tab on `/u/{handle}`.  A collection is listed when `is_public` is set, whatever is filed inside it. `saveCount` then counts only the public saves in it, so a public collection full of private links reports zero rather than leaking its size.
     */
    async usersGetCollections(requestParameters: UsersGetCollectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicCollectionListResponse> {
        const response = await this.usersGetCollectionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Who follows this profile, newest follower first.
     */
    async usersGetFollowersRaw(requestParameters: UsersGetFollowersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicProfileListResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersGetFollowers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/followers`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicProfileListResponseFromJSON(jsonValue));
    }

    /**
     * Who follows this profile, newest follower first.
     */
    async usersGetFollowers(requestParameters: UsersGetFollowersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicProfileListResponse> {
        const response = await this.usersGetFollowersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Who this profile follows, most recently followed first.
     */
    async usersGetFollowingRaw(requestParameters: UsersGetFollowingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicProfileListResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersGetFollowing().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/following`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicProfileListResponseFromJSON(jsonValue));
    }

    /**
     * Who this profile follows, most recently followed first.
     */
    async usersGetFollowing(requestParameters: UsersGetFollowingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicProfileListResponse> {
        const response = await this.usersGetFollowingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The **public** bookmarks this profile has liked, most recently liked first - the Likes tab on `/u/{handle}`.  A like on a bookmark that is not public is not listed, whoever owns it. A like is a public act on a public thing; it is not a licence to see somebody\'s private library through the back door.
     */
    async usersGetLikesRaw(requestParameters: UsersGetLikesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicSavesResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersGetLikes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/likes`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicSavesResponseFromJSON(jsonValue));
    }

    /**
     * The **public** bookmarks this profile has liked, most recently liked first - the Likes tab on `/u/{handle}`.  A like on a bookmark that is not public is not listed, whoever owns it. A like is a public act on a public thing; it is not a licence to see somebody\'s private library through the back door.
     */
    async usersGetLikes(requestParameters: UsersGetLikesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicSavesResponse> {
        const response = await this.usersGetLikesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A public profile by handle.  Keyed on the handle rather than the id so a profile link survives being pasted somewhere. 404 - never 403 - when the profile has blocked the caller: a 403 would confirm both that the account exists and that something about the caller is why they cannot see it, which is exactly what a block withholds.
     */
    async usersGetProfileRaw(requestParameters: UsersGetProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicProfile>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersGetProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicProfileFromJSON(jsonValue));
    }

    /**
     * A public profile by handle.  Keyed on the handle rather than the id so a profile link survives being pasted somewhere. 404 - never 403 - when the profile has blocked the caller: a 403 would confirm both that the account exists and that something about the caller is why they cannot see it, which is exactly what a block withholds.
     */
    async usersGetProfile(requestParameters: UsersGetProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicProfile> {
        const response = await this.usersGetProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A profile\'s public saves, newest first. Never their private ones, and never anything at all to a user they have blocked.
     */
    async usersGetSavesRaw(requestParameters: UsersGetSavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicSavesResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersGetSaves().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/saves`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicSavesResponseFromJSON(jsonValue));
    }

    /**
     * A profile\'s public saves, newest first. Never their private ones, and never anything at all to a user they have blocked.
     */
    async usersGetSaves(requestParameters: UsersGetSavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicSavesResponse> {
        const response = await this.usersGetSavesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unblock. Does not restore the follow edges the block removed - those were deleted, and re-following is the user\'s decision to make again.
     */
    async usersUnblockRaw(requestParameters: UsersUnblockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersUnblock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/block`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockResponseFromJSON(jsonValue));
    }

    /**
     * Unblock. Does not restore the follow edges the block removed - those were deleted, and re-following is the user\'s decision to make again.
     */
    async usersUnblock(requestParameters: UsersUnblockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockResponse> {
        const response = await this.usersUnblockRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unfollow. Immediate and silent - the followed user is not notified.
     */
    async usersUnfollowRaw(requestParameters: UsersUnfollowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FollowResponse>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling usersUnfollow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/{handle}/follow`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FollowResponseFromJSON(jsonValue));
    }

    /**
     * Unfollow. Immediate and silent - the followed user is not notified.
     */
    async usersUnfollow(requestParameters: UsersUnfollowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FollowResponse> {
        const response = await this.usersUnfollowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
