name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # Replace with the desired Go version

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: go mod tidy

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Start Supabase
        run: docker-compose up -d
        env:
          SUPABASE_URL: http://localhost:54321
          SUPABASE_KEY: your-test-supabase-key # Replace with your Supabase test key

      - name: Run Database Migrations
        run: make db-migrate

      - name: Run Tests
        run: make test

  migrate:
    name: Apply Database Migrations
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Apply Migrations
        run: make db-migrate

  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: migrate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.97.1/doctl-1.97.1-linux-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin/

      - name: Authenticate doctl
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: doctl auth init

      - name: Deploy Application
        run: doctl app create --spec .digitalocean.yaml # Adjust the path if necessary